# -*- coding: utf-8 -*-
"""Handcrafted deep notes for CSE601, CSIT654, CSIT745 (BS605 Module-3 quality).

Run: python _handcraft_all_deep_notes.py
Then: python build_hub.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SUBJECTS = ROOT / "subjects"


def T(name: str, d: str) -> dict:
    return {"t": name, "d": d}


def note(n: str) -> str:
    return n


def pack(terms, concepts, notes, lmr: bool = False) -> dict:
    """Handcrafted deep-note pack. Set lmr=True for exam-priority topics only."""
    return {"terms": terms, "concepts": concepts, "notes": notes, "lmr": bool(lmr)}


# =============================================================================
# CSE601 — Data Structures & Algorithms
# LMR flags follow Live Class 1–2 teacher exam weightage where available;
# modules without live class yet stay syllabus-study only (no LMR badge).
# =============================================================================

CSE601: dict[str, dict] = {
    "m1_root": pack(
        [T("Linear structures", "Stack, queue, linked lists — order and access rules matter."),
         T("Algorithm analysis", "Asymptotics, recurrence, Master theorem — how cost grows with n."),
         T("Sorting", "Compare algorithms by time, space, and stability.")],
        ["Module 1 flow: structures → analysis → divide-and-conquer → sorts.",
         "Exam style: define + one example + characteristics / operations (teacher: Class 1).",
         "Out of syllabus (teacher): ADT — skip deep ADT write-ups."],
        ["LMR (Live Class 1): Stack (ops + overflow/underflow + pseudocode), infix↔postfix/prefix, algorithm characteristics.",
         "Teacher foreshadow: sorting & searching are exam-important in later sessions.",
         "Never give only a name — always add LIFO/FIFO or the five algorithm characteristics when asked."],
    ),
    "m2_root": pack(
        [T("Trees", "Hierarchical linked structures; BST/AVL/B-tree variants balance search cost."),
         T("Graphs", "Vertices + edges; DFS/BFS and shortest paths are core traversals.")],
        ["Trees first, then graph traversals and path algorithms.",
         "Prim vs Kruskal both build MSTs — different selection rules.",
         "Out of syllabus (teacher): binary-tree ADT; level-order traversal."],
        ["LMR (Live Class 2): tree height + binary-tree properties + pre/in/postorder; graph representations.",
         "Next-class (not LMR yet): spanning trees, shortest paths."],
    ),
    "m3_root": pack(
        [T("Dynamic programming", "Optimal substructure + overlapping subproblems; store results."),
         T("Greedy", "Locally optimal choice hoping for global optimum — not always correct."),
         T("Classic problems", "Knapsack variants, activity selection, Huffman, TSP.")],
        ["0/1 knapsack → DP; fractional knapsack → greedy — classic exam trap.",
         "TSP is typically hard; don’t treat it as a simple greedy always."],
        ["No Live Class yet — Module 3 quizzes are SLM hand-picks (DP, optimality, knapsack, greedy).",
         "LMR badges stay on Class 1–2 priorities until a later class weights Module 3."],
    ),
    "m4_root": pack(
        [T("String matching", "Find pattern P in text T — naïve vs Rabin–Karp hashing."),
         T("Approximation / LP themes", "Vertex cover, set cover, subset-sum — often near-optimal algorithms.")],
        ["Rabin–Karp uses rolling hash; naïve compares character by character.",
         "Vertex cover / set cover are classic approximation settings.",
         "Teacher (Class 2) flagged LP as a later complex topic — watch that live class."],
        ["No Live Class yet — Module 4 quizzes are SLM hand-picks (naïve, Rabin–Karp, vertex cover).",
         "Avoid inventing weightage; refine when the live class lands."],
    ),
    "m5_root": pack(
        [T("NP-completeness", "Hard decision problems; reductions show hardness."),
         T("Hamiltonian cycle", "Visit each vertex once and return — classic NP-complete flavour."),
         T("Green technology (syllabus)", "Efficiency/resource angle linked in this module’s framing.")],
        ["NP-complete vs NP-hard: completeness is in NP + hard for NP.",
         "Reducibility is the proof tool — map known hard problem to yours."],
        ["Teacher foreshadow (Class 2): NP-hard / NP-complete — SLM handpick quizzes OK; LMR badge after that live class.",
         "Green-technology framing is syllabus text — skipped from quizzes (not live-class weighted)."],
    ),
    "1.1.1": pack(
        [T("Stack", "LIFO structure: push/pop at the same end (the top)."),
         T("Push", "Insert an element on top."),
         T("Pop", "Remove the top element."),
         T("Peek / top", "Read the top without removing it."),
         T("Underflow / overflow", "Pop on empty / push on full (array stack).")],
        ["Stack ≠ queue: LIFO vs FIFO.",
         "Call stack / undo / postfix evaluation are classic uses.",
         "Array stack needs capacity; linked stack grows with nodes.",
         "Exam write-up: use pseudocode (teacher) — check overflow before push, underflow before pop."],
        ["LMR (Class 1): overflow/underflow + push/pop pseudocode — teacher called these very important.",
         "Trap: do not say FIFO for stack.",
         "Stem “last in first out / top only” → stack."],
        True,
    ),
    "1.1.2": pack(
        [T("Postfix (RPN)", "Operators follow their operands (e.g. 3 4 +)."),
         T("Evaluation with stack", "Scan left→right: push operands; on operator, pop args, push result."),
         T("Infix / prefix conversions", "Teacher stress: infix→postfix and postfix↔prefix are exam favourites.")],
        ["Infix needs precedence/parentheses; postfix does not.",
         "Each operator pops the right number of operands (usually 2 for binary).",
         "Walk one tiny conversion + evaluation on paper every revision."],
        ["LMR (Class 1): infix↔postfix / postfix↔prefix — “very important from the exam standpoint”.",
         "Trap: processing order is left to right, not ‘operator first’.",
         "If expression is infix, convert first — don’t evaluate infix with raw postfix rules."],
        True,
    ),
    "1.1.3": pack(
        [T("Tower of Hanoi", "Move n disks from source to target using auxiliary peg."),
         T("Rule", "Only one disk at a time; never place larger on smaller."),
         T("Recurrence", "T(n)=2T(n−1)+1, T(1)=1 → T(n)=2^n−1 moves.")],
        ["Recursive idea: move n−1 aside, move largest, move n−1 on top.",
         "Shows divide-and-conquer / recursion cost explosion.",
         "Class 1: mentioned as a stack application — not the primary exam weight vs postfix conversions."],
        ["Trap: minimum moves are 2^n−1, not n^2.",
         "Know recurrence + closed form if asked; priority after stack ops and expression conversion."],
    ),
    "1.1.4": pack(
        [T("Queue", "FIFO: enqueue at rear, dequeue at front."),
         T("Enqueue / Dequeue", "Insert rear / remove front."),
         T("Circular queue", "Wrap indices to reuse array space.")],
        ["Queue ≠ stack (FIFO vs LIFO).",
         "BFS uses a queue; DFS uses a stack/recursion."],
        ["Trap: don’t pop from rear for a normal queue.",
         "Stem “first come first served” → queue."],
    ),
    "1.1.5": pack(
        [T("Linked list", "Nodes with data + pointer(s); dynamic size."),
         T("Singly linked", "Each node points to next only."),
         T("Head", "Entry pointer to the first node.")],
        ["Insert/delete can be O(1) given a node reference; search is O(n).",
         "Vs array: no random access O(1), but flexible growth."],
        ["Trap: linked list ≠ array contiguous memory.",
         "Always track head (and sometimes tail) carefully."],
    ),
    "1.1.6": pack(
        [T("Doubly linked list", "Each node has next and prev pointers."),
         T("Bidirectional traversal", "Walk forward or backward."),
         T("Delete convenience", "Easier deletion when you have the node (prev is known).")],
        ["Extra pointer cost vs singly linked.",
         "Still no O(1) index access like arrays."],
        ["Trap: update both next and prev on insert/delete — half-updates break the list."],
    ),
    "1.2.1": pack(
        [T("Algorithm", "Finite, unambiguous sequence of steps producing output from input."),
         T("Characteristics (5)", "Input, output, definiteness, finiteness, effectiveness/feasibility — teacher Class 1 list."),
         T("Exam answer shape", "Definition + one simple example (e.g. tea/recipe) + the five characteristics.")],
        ["Program implements an algorithm in a language.",
         "Finiteness: must terminate; definiteness: each step clear.",
         "Effectiveness/feasibility: runnable with available resources."],
        ["LMR (Class 1): “what is an algorithm + characteristics” — teacher said this is the exam ask.",
         "Trap: infinite loop is not a valid algorithm characteristic."],
        True,
    ),
    "1.2.2": pack(
        [T("Big-O", "Upper bound on growth rate (worst-case flavour in teaching)."),
         T("Ω (Omega)", "Lower bound on growth."),
         T("Θ (Theta)", "Tight bound — both O and Ω."),
         T("Little-o / ~", "Stricter / asymptotic equivalence ideas (if taught).")],
        ["Asymptotics ignore constants and lower-order terms.",
         "O(n^2) does not mean ‘exactly n^2 steps’.",
         "Teacher (Class 1): knowing the symbols is enough for many papers — deep complexity proofs rarely appear."],
        ["Trap: O is not the same as Θ unless also Ω.",
         "Spelling in syllabus: ‘Asymtotic’ = asymptotic notations.",
         "Still learn definitions — book uses them everywhere — but don’t over-invest vs stack/trees."],
    ),
    "1.2.3": pack(
        [T("Time complexity", "How running time grows with input size n."),
         T("Best / average / worst", "Different cases; exams often want worst-case Big-O."),
         T("Space complexity", "Extra memory growth with n.")],
        ["Count dominant operations, not wall-clock alone.",
         "Nested loops often multiply costs.",
         "Teacher: important for understanding algorithms; heavy exam questions on complexity rare in recent papers he has seen."],
        ["Trap: ‘faster machine’ does not change asymptotic class."],
    ),
    "1.2.4": pack(
        [T("Recurrence", "T(n) defined in terms of T(smaller)."),
         T("Recursion tree / substitution / Master", "Strategies to solve recurrences."),
         T("Base case", "Stops recursion; needed for well-founded analysis.")],
        ["Wrong base case ⇒ wrong closed form.",
         "Unfold a few levels before guessing the pattern."],
        ["Trap: forgetting the +f(n) combine cost in divide-and-conquer."],
    ),
    "1.2.5": pack(
        [T("Master theorem", "Solves T(n)=aT(n/b)+f(n) for many standard f."),
         T("Cases", "Compare f(n) with n^{log_b a} (three main cases)."),
         T("Limitations", "Not all recurrences fit; need regularity conditions.")],
        ["Identify a, b, f(n) first — then case.",
         "Merge sort: a=2,b=2,f=Θ(n) → Θ(n log n)."],
        ["Trap: applying Master when split is uneven or f doesn’t fit cases."],
    ),
    "1.3.1": pack(
        [T("Divide and conquer", "Divide → conquer recursively → combine."),
         T("Recurrence form", "Often T(n)=aT(n/b)+f(n)."),
         T("Examples", "Merge sort, binary search, some matrix methods.")],
        ["Combine cost f(n) matters as much as subproblem count.",
         "Not every recursive algorithm is efficient D&C."],
        ["Trap: confusing D&C with DP (DP stores overlapping results)."],
    ),
    "1.4.1": pack(
        [T("Bubble sort", "Repeatedly swap adjacent out-of-order pairs."),
         T("Time", "O(n^2) typical/worst; can be O(n) if already sorted with early exit."),
         T("Stable?", "Can be implemented stable.")],
        ["Simple but slow for large n.",
         "After pass i, largest elements ‘bubble’ to the end."],
        ["Trap: don’t claim O(n log n) for bubble sort."],
    ),
    "1.4.2": pack(
        [T("Insertion sort", "Build sorted prefix; insert next element into place."),
         T("Time", "O(n^2) worst; O(n) best on nearly sorted data."),
         T("Stable", "Yes (typical implementation).")],
        ["Good for small or nearly sorted arrays.",
         "Online: can sort as data arrives."],
        ["Trap: best-case O(n) ≠ average O(n)."],
    ),
    "1.4.3": pack(
        [T("Selection sort", "Repeatedly select min (or max) from unsorted part and swap into place."),
         T("Time", "Θ(n^2) comparisons roughly always."),
         T("Not stable", "Typical swap-based version is unstable.")],
        ["Fewer writes than some sorts, but still quadratic comparisons.",
         "Unlike insertion, does not benefit much from nearly sorted input."],
        ["Trap: selection ≠ insertion — selection always scans remaining min."],
    ),
    "1.4.4": pack(
        [T("Merge sort", "Divide array, sort halves, merge sorted runs."),
         T("Time", "Θ(n log n) in all cases — predictable guaranteed bound."),
         T("Space", "Needs Θ(n) auxiliary memory for the classic merge."),
         T("Stable", "Yes — equal keys keep their relative order after sorting.")],
        ["Predictable performance — good exam ‘guaranteed n log n’ answer.",
         "Merge is the combine step."],
        ["Trap: merge sort is not in-place in the standard form."],
    ),
    "1.4.5": pack(
        [T("Heap sort", "Build heap, repeatedly extract max/min to place next sorted item."),
         T("Time", "O(n log n) overall; build-heap is O(n), then n extracts."),
         T("In-place", "Yes (array heap); not typically stable.")],
        ["Uses heap property: parent ordered vs children.",
         "Build-heap is O(n); extracts cost O(n log n)."],
        ["Trap: heap sort ≠ priority-queue ADT lecture alone — it’s a sorting algorithm."],
    ),
    "1.4.6": pack(
        [T("Quick sort", "Partition around pivot; recurse on parts."),
         T("Average time", "O(n log n); worst O(n^2) on bad pivots."),
         T("In-place", "Mostly yes (small stack); not stable typically.")],
        ["Pivot choice affects balance.",
         "Often fastest in practice despite worst case."],
        ["Trap: worst case is quadratic — mention randomised/median-of-three if asked."],
    ),
    "2.1.1": pack(
        [T("Tree", "Connected acyclic graph; hierarchical parent–child."),
         T("Root / leaf / internal", "Top node / no children / has children."),
         T("Height / level", "Teacher: height of a tree is a recurring exam question — practise on a drawn tree."),
         T("Applications", "File systems, expression trees, search structures, heaps.")],
        ["Tree ≠ general graph with cycles.",
         "Height/depth definitions vary slightly — use the convention the teacher used in Class 2.",
         "Also know parent/child/ancestor/descendant vocabulary."],
        ["LMR (Class 2): “there’s always a question… how you can find out the height of the tree.”",
         "Trap: ‘tree’ in CS usually means rooted tree in DSA units."],
        True,
    ),
    "2.1.2": pack(
        [T("Binary tree", "Each node has at most two children (left/right)."),
         T("Full / complete / perfect", "Variants about occupancy of levels (syllabus defs)."),
         T("Max nodes for height H", "Teacher exam expect: properties / formulas for binary trees of height H."),
         T("Traversals (in syllabus)", "Preorder, inorder, postorder — Class 2: expect these in end-term.")],
        ["Binary tree ≠ BST (BST adds ordering invariant).",
         "Array representation possible for complete trees (heaps).",
         "Out of syllabus (teacher): binary-tree ADT; level-order traversal — do not spend exam time on them."],
        ["LMR (Class 2): binary-tree properties + pre/in/postorder (not level-order).",
         "Trap: don’t assume sorted order without BST property.",
         "Time for traversal is O(n) — visit every node once."],
        True,
    ),
    "2.1.3": pack(
        [T("BST", "Left keys < node < right keys (standard ordering)."),
         T("Search / insert", "Follow comparisons down a path."),
         T("Inorder traversal", "Yields keys in sorted order.")],
        ["Balanced BST ⇒ O(log n); skewed ⇒ O(n).",
         "Deletion has cases: leaf / one child / two children (successor/predecessor).",
         "Class 2 focus was height/properties/traversals first — BST is syllabus, lower live-class weight so far."],
        ["Trap: binary tree without order is not a BST.",
         "State ordering invariant clearly when asked."],
    ),
    "2.1.4": pack(
        [T("Optimal BST", "BST arranged to minimise expected search cost given key probabilities."),
         T("DP construction", "Classic dynamic-programming optimisation on key ranges.")],
        ["Not the same as ‘any balanced BST’ — optimality uses frequencies.",
         "Related to matrix-chain style interval DP."],
        ["Trap: AVL/Red-Black balance ≠ probability-optimal BST."],
    ),
    "2.1.5": pack(
        [T("Red-Black tree", "Self-balancing BST with coloured nodes and rotation/recolour rules."),
         T("Balance guarantee", "Height O(log n); operations O(log n).")],
        ["Alternative to AVL with slightly different balance strictness.",
         "Used widely in libraries (e.g. some map implementations)."],
        ["Trap: colour rules are invariants — don’t invent ‘just paint randomly’."],
    ),
    "2.1.6": pack(
        [T("AVL tree", "BST where |height(left)−height(right)| ≤ 1 at every node."),
         T("Rotations", "LL, RR, LR, RL fix imbalance after insert/delete."),
         T("Complexity", "Search/insert/delete O(log n).")],
        ["Stricter balance than Red-Black often ⇒ more rotations.",
         "Balance factor is the height difference."],
        ["Trap: AVL is a BST plus height invariant — not a heap."],
    ),
    "2.1.7": pack(
        [T("B-tree", "Multiway balanced search tree for disk/block storage."),
         T("High fanout", "Many keys per node ⇒ shallow tree ⇒ fewer disk reads."),
         T("Properties", "All leaves at same level; node occupancy bounds (order).")],
        ["Designed for secondary storage, not only RAM.",
         "B+ trees (if taught) keep data in leaves — don’t conflate blindly."],
        ["Trap: B-tree ≠ binary tree; ‘B’ is not ‘binary’."],
    ),
    "2.1.8": pack(
        [T("Spanning tree", "Subgraph that is a tree connecting all vertices."),
         T("MST", "Spanning tree of minimum total edge weight.")],
        ["Exists for connected undirected graphs.",
         "Prim/Kruskal compute MSTs.",
         "Teacher (Class 2): spanning-tree concept flagged for the next session — not LMR-badged until that class."],
        ["Trap: spanning tree has V−1 edges — no cycles.",
         "Watch the next live class for exam weight on MST/Prim/Kruskal."],
    ),
    "2.1.9": pack(
        [T("Prim’s algorithm", "Grow MST from a start vertex by always adding lightest safe edge out."),
         T("Data structure", "Often priority queue for cut edges.")],
        ["Cut property: lightest edge crossing the cut is safe for MST.",
         "Prim is vertex-centric growth."],
        ["Trap: Prim ≠ Kruskal (Kruskal sorts edges globally)."],
    ),
    "2.1.10": pack(
        [T("Kruskal’s algorithm", "Sort edges by weight; add if it doesn’t form a cycle (Union–Find)."),
         T("Union–Find", "Tracks components to detect cycles efficiently.")],
        ["Edge-centric; works well on sparse graphs.",
         "Same MST cut/cycle properties as Prim’s goal."],
        ["Trap: adding lightest edge blindly without cycle check is wrong."],
    ),
    "2.2.1": pack(
        [T("Graph", "G=(V,E); directed/undirected; weighted/unweighted."),
         T("Adjacency matrix", "Teacher: undirected missing edge → ∞ (or no edge mark); directed missing → 0 as taught."),
         T("Adjacency list", "List neighbours of each vertex — good for sparse graphs."),
         T("Traversal", "Systematic visit: DFS/BFS.")],
        ["Matrix: O(1) edge query, O(V^2) space; list: better for sparse.",
         "Degree, path, cycle, connected/disconnected are core terms.",
         "Class 2 spent exam-weight time on representations and basic graph types."],
        ["LMR (Class 2): graph types + matrix vs list representation rules.",
         "Trap: pick representation based on density — not always matrix."],
        True,
    ),
    "2.2.2": pack(
        [T("DFS", "Explore deep along a path; backtrack; stack/recursion."),
         T("Uses", "Cycle detect, topological sort, components, path finding.")],
        ["DFS forest / timestamps appear in CLRS-style analysis.",
         "Not optimal shortest path in weighted graphs by itself."],
        ["Trap: DFS ≠ BFS order; DFS not for unweighted shortest path."],
    ),
    "2.2.3": pack(
        [T("BFS", "Explore level by level using a queue."),
         T("Unweighted shortest path", "BFS layers give fewest edges from source.")],
        ["Queue is essential; mark visited to avoid reprocessing.",
         "Contrast with Dijkstra for weighted graphs."],
        ["Trap: BFS on weighted edges with different weights ≠ Dijkstra."],
    ),
    "2.2.4": pack(
        [T("Single-source shortest path", "Shortest paths from one source to all vertices."),
         T("Dijkstra", "Non-negative weights; greedy with priority queue."),
         T("Bellman–Ford", "Handles negative edges; detects negative cycles.")],
        ["Dijkstra fails with negative edges.",
         "Relaxation is the common primitive.",
         "Teacher (Class 2): shortest path flagged for the next session — not LMR-badged until that class."],
        ["Trap: using Dijkstra with negatives — wrong.",
         "Study the idea now; badge after the live class weights it."],
    ),
    "2.2.5": pack(
        [T("All-pairs shortest path", "Shortest paths between every pair."),
         T("Floyd–Warshall", "DP over intermediate vertices; O(V^3)."),
         T("Johnson’s (if taught)", "Reweighting + Dijkstra from each source.")],
        ["Floyd works with negatives but not negative cycles.",
         "Matrix DP update: d[i][j] = min(d[i][j], d[i][k]+d[k][j])."],
        ["Trap: Floyd ≠ single BFS from each node on weighted graphs."],
    ),
    "3.1.1": pack(
        [T("Dynamic programming", "Solve overlapping subproblems once; store answers."),
         T("Memoisation vs tabulation", "Top-down cache vs bottom-up table."),
         T("When", "Optimal substructure + overlapping subproblems.")],
        ["DP ≠ divide-and-conquer alone (D&C may not overlap).",
         "DP ≠ greedy (greedy never revisits choices systematically)."],
        ["No live-class weight yet — study from SLM; say both DP conditions when asked.",
         "Trap: calling every recursion ‘DP’ without storage of overlaps."],
    ),
    "3.1.2": pack(
        [T("Principle of optimality", "Optimal solution contains optimal solutions to subproblems."),
         T("Role in DP", "Justifies composing sub-results into global optimum.")],
        ["If principle fails, DP formulation is invalid.",
         "Check on a small example before coding a table."],
        ["No live-class weight yet — one-line definition is still worth memorising from SLM.",
         "Trap: optimality principle ≠ ‘greedy choice property’ (that’s greedy)."],
    ),
    "3.1.3": pack(
        [T("Strassen multiplication", "Faster matrix multiply than naïve O(n^3) using 7 recursive multiplies."),
         T("Idea", "Algebraic recombination reduces multiplications; adds more additions.")],
        ["Asymptotically better; constants/practicality may vary.",
         "Still divide-and-conquer on quadrants."],
        ["No live-class weight yet — ‘7 products instead of 8’ is the SLM memorable fact.",
         "Trap: Strassen is not related to shortest paths."],
    ),
    "3.1.4": pack(
        [T("Matrix chain multiplication", "Parenthesise matrix product to minimise scalar multiplies."),
         T("DP", "Interval DP over chain length.")],
        ["Order of multiplication changes cost, not the mathematical product.",
         "Classic DP table m[i][j]."],
        ["Trap: this is about cost of parenthesisation — not Strassen’s algorithm itself."],
    ),
    "3.1.5": pack(
        [T("LCS", "Longest common subsequence of two strings (not necessarily contiguous)."),
         T("DP table", "If chars equal, diagonal+1; else max of skip either.")],
        ["Subsequence ≠ substring (substring is contiguous).",
         "Used in diff tools / bioinformatics examples."],
        ["Trap: LCS vs longest common substring — contiguousness."],
    ),
    "3.1.6": pack(
        [T("0/1 knapsack", "Each item take or not; maximise value under weight limit."),
         T("DP", "dp[i][w] style; pseudo-polynomial in capacity."),
         T("Not fractional", "Cannot break items.")],
        ["Contrast fractional knapsack (greedy by value/weight).",
         "NP-hard as optimisation in general; DP works for integer capacity."],
        ["Trap: using greedy value/weight for 0/1 — incorrect in general."],
    ),
    "3.2.1": pack(
        [T("Greedy approach", "Build solution by locally best choice at each step."),
         T("Greedy choice property", "Local optimum can lead to global (when algorithm is correct)."),
         T("Exchange argument", "Proof style that swaps to show optimality.")],
        ["Greedy is fast but not always optimal — need a proof or known pattern.",
         "Examples: activity selection, Huffman, fractional knapsack."],
        ["Trap: ‘greedy always works’ — false."],
    ),
    "3.2.2": pack(
        [T("Activity selection", "Select max non-overlapping activities."),
         T("Greedy rule", "Usually earliest finishing time first.")],
        ["Sort by finish time, then pick compatible next.",
         "Classic proof via greedy choice + optimal substructure."],
        ["Trap: sorting by start time alone is not the standard optimal greedy."],
    ),
    "3.2.3": pack(
        [T("Huffman codes", "Optimal prefix codes using frequency-greedy tree."),
         T("Prefix-free", "No codeword is prefix of another — unique decode."),
         T("Build", "Repeatedly merge two least frequent nodes.")],
        ["More frequent symbols → shorter codes.",
         "Related to binary trees and priority queues."],
        ["Trap: Huffman is for encoding efficiency — not encryption security."],
    ),
    "3.2.4": pack(
        [T("Fractional knapsack", "May take fraction of an item."),
         T("Greedy", "Sort by value/weight ratio; take until capacity fills.")],
        ["Optimal for fractional case; not for 0/1.",
         "Last item may be taken partially."],
        ["Trap: applying fractional greedy to 0/1 knapsack."],
    ),
    "3.3.1": pack(
        [T("TSP", "Visit each city once and return; minimise tour length."),
         T("Hardness", "Classic NP-hard optimisation problem."),
         T("Approaches", "Brute force, DP (Held–Karp), heuristics/approx.")],
        ["Brute force is factorial — not scalable.",
         "Don’t claim a simple greedy always optimal for general TSP."],
        ["Trap: confusing TSP with MST (MST is not a tour)."],
    ),
    "3.3.2": pack(
        [T("Knapsack problem (general)", "Select items under capacity to maximise value."),
         T("Variants", "0/1, fractional, unbounded — different algorithms.")],
        ["Name the variant before choosing DP vs greedy.",
         "Syllabus may revisit knapsack under ‘problems’ cluster."],
        ["Trap: one word ‘knapsack’ — always specify 0/1 vs fractional."],
    ),
    "3.3.3": pack(
        [T("Job sequencing", "Schedule jobs to maximise profit under constraints (often deadlines/slots)."),
         T("Greedy pattern", "Often sort by profit; place in latest free slot before deadline.")],
        ["Related to deadline scheduling themes.",
         "Check whether multiple slots / unit time jobs assumed."],
        ["Trap: sequencing ≠ OS process scheduling vocabulary unless syllabus links them."],
    ),
    "3.3.4": pack(
        [T("Job sequencing with deadline", "Unit-time jobs with deadlines and profits; maximise profit."),
         T("Method", "Sort profits descending; assign to feasible time slot.")],
        ["Feasibility: finish by deadline.",
         "Greedy placement into latest possible slot is common."],
        ["Trap: ignoring deadline when taking highest profit first blindly."],
    ),
    "4.1.1": pack(
        [T("Naïve string matching", "Try P at every shift of T; compare chars."),
         T("Time", "O((n−m+1)m) worst case.")],
        ["Simple baseline for Rabin–Karp / KMP comparisons.",
         "Many mismatches still cost comparisons."],
        ["No live-class weight yet — state complexity clearly from SLM.",
         "Trap: naïve is not hashing-based."],
    ),
    "4.1.3": pack(
        [T("Rabin–Karp", "Rolling hash of windows; verify on hash hit."),
         T("Spurious hit", "Hash match but strings differ — must verify."),
         T("Average", "Good with strong hash; worst can degrade.")],
        ["Rolling hash updates in O(1) per shift.",
         "Multiple patterns can share hashing ideas."],
        ["No live-class weight yet — hash then verify (never skip verify).",
         "Trap: hash equality ≠ string equality."],
    ),
    "4.2.1": pack(
        [T("Vertex cover", "Set of vertices incident to every edge."),
         T("Approx algorithm", "Classic 2-approx: pick both ends of an uncovered edge, repeat.")],
        ["Decision version is NP-complete; approx is taught for algorithms design.",
         "Minimal vs minimum — wording matters."],
        ["No live-class weight yet — definition + 2-approx idea from SLM.",
         "Trap: vertex cover ≠ vertex colouring."],
    ),
    "4.2.2": pack(
        [T("Set cover", "Cover universe with minimum number of subsets."),
         T("Greedy approx", "Repeatedly pick set covering most remaining elements.")],
        ["NP-hard; greedy gives logarithmic approximation classically.",
         "Related to hitting-set formulations."],
        ["Trap: set cover ≠ vertex cover (different universe structure)."],
    ),
    "4.2.3": pack(
        [T("Randomisation", "Algorithms that use randomness for speed/simplicity (expected performance)."),
         T("Linear programming", "Optimise linear objective under linear constraints — algorithmic tool.")],
        ["Syllabus pairs ideas for advanced design techniques.",
         "Randomised algorithms need expected/high-probability analysis."],
        ["Trap: randomised ≠ incorrect; analyse failure probability."],
    ),
    "4.2.4": pack(
        [T("Subset-sum", "Decision problem: decide whether any subset of numbers adds exactly to target t."),
         T("Hardness / DP", "NP-complete as a decision problem; solvable in pseudo-polynomial time via DP.")],
        ["Related to the knapsack decision version.",
         "Meet-in-the-middle is sometimes taught for moderate n."],
        ["Trap: subset-sum is not always polynomial — numeric magnitude matters."],
    ),
    "5.1.1": pack(
        [T("Green technology (in this module)", "Efficiency/resource-conscious computing themes tied to algorithmic cost."),
         T("Link to complexity", "Fewer operations / less energy as a motivation for better algorithms.")],
        ["Treat as syllabus framing unless SLM gives a narrower definition.",
         "Connect to choosing efficient algorithms over naïve ones.",
         "Not live-class weighted so far — lower revision priority than NP topics."],
        ["Trap: don’t invent unrelated ecology essays — stay CS-framed."],
    ),
    "5.1.2": pack(
        [T("Hamiltonian cycle", "Cycle visiting each vertex exactly once and returning."),
         T("Hardness", "Deciding existence is NP-complete (classic).")],
        ["Vs Euler tour: Euler uses every edge; Hamiltonian every vertex.",
         "TSP optimisation builds on Hamiltonian ideas."],
        ["Useful NP-complete example from SLM; teacher named NP-hard/complete generally (Class 2).",
         "Trap: Hamiltonian ≠ Eulerian."],
    ),
    "5.2.1": pack(
        [T("NP-completeness proof", "Show problem in NP + polynomial reduction from known NP-complete problem."),
         T("Certificate", "Short verifiable witness for yes instances (for NP).")],
        ["Reduction direction: known hard ≤p your problem.",
         "Polynomial-time verification ≠ polynomial-time solving.",
         "Teacher (Class 2): NP-hard / NP-complete coming later — no LMR badge until that class."],
        ["Trap: reducing your problem to SAT shows yours is ‘no harder’ — wrong direction for hardness.",
         "Know the two-part proof shape from SLM; live-class weight comes later."],
    ),
    "5.2.2": pack(
        [T("NP-complete problems", "Hardest problems in NP (under poly reductions)."),
         T("Examples", "SAT, vertex cover decision, Hamiltonian cycle, subset-sum, …")],
        ["If any NP-complete problem has poly algorithm, P=NP.",
         "Practice recognising ‘decision version’ wording."],
        ["Trap: optimisation TSP vs decision Hamiltonian — related but not identical statements."],
    ),
    "5.2.3": pack(
        [T("NP-hard", "At least as hard as NP-complete; may not be in NP."),
         T("SAT", "Satisfiability of Boolean formulas — central NP-complete problem.")],
        ["NP-hard includes problems outside NP (e.g. some optimisation/undecidable-adjacent teaching examples).",
         "SAT is the usual reduction source.",
         "Teacher (Class 2) named NP-hard / NP-complete as upcoming — badge after that live class."],
        ["Trap: NP-hard ≠ NP-complete unless also in NP."],
    ),
    "5.2.4": pack(
        [T("Reducibility", "Problem A ≤p B if A transforms to B in poly time."),
         T("Meaning", "B is at least as hard as A (for hardness proofs).")],
        ["Cook–Levin historically links SAT to NP-completeness theory.",
         "Always state what reduces to what."],
        ["Trap: arrow direction mistakes fail proofs."],
    ),
}
