# -*- coding: utf-8 -*-
"""Handcrafted deep notes for CSIT654 — Network Security and Cryptography.

BS605 Module-3 / CSE601 pack quality: exam one-liners, compare/contrast, stem traps.
Importable: from _handcraft_csit654_deep import CSIT654
"""
from __future__ import annotations


def T(name, d):
    return {"t": name, "d": d}


def pack(terms, concepts, notes, lmr=False):
    return {"terms": terms, "concepts": concepts, "notes": notes}


# =============================================================================
# CSIT654 — Network Security and Cryptography
# =============================================================================

CSIT654: dict[str, dict] = {
    # ----- module roots -----
    "m1_root": pack(
        [T("CIA triad", "Confidentiality, Integrity, Availability — core security goals."),
         T("Attacks vs services vs mechanisms", "Threats → what we want (services) → how we achieve it (mechanisms)."),
         T("Classical crypto", "Substitution and transposition; cryptanalysis recovers key/plaintext."),
         T("Cipher family", "Stream vs block; steganography hides existence, not just meaning.")],
        ["Module 1 maps threats → security services/mechanisms → classical ciphers → crypto basics.",
         "Hardware security is overview only here; modern block ciphers land in Module 2.",
         "Exam habit: define + one contrast (e.g. passive vs active; stream vs block)."],
        ["Prioritise LMR: attacks, services/mechanisms, classical techniques.",
         "Never answer “encryption” when the stem asks for a service name (confidentiality)."],
    ),
    "m2_root": pack(
        [T("Modern block ciphers", "Feistel/DES lineage; AES is the SPN standard."),
         T("Confusion & diffusion", "Shannon: hide key–ciphertext link; spread plaintext influence."),
         T("Modes", "ECB/CBC/CFB/OFB/CTR change how a block cipher is used on messages."),
         T("Public-key maths", "Fermat/Euler, CRT; RSA for encryption and signatures.")],
        ["Symmetric block work (2.1) then number theory + RSA (2.2).",
         "DES strength and differential ideas explain why AES replaced DES.",
         "Triple DES bridges DES legacy; AES is the current exam “modern” cipher."],
        ["LMR first: block principles, Shannon C&D, Feistel.",
         "Trap: confusing Feistel rounds with AES SubBytes/ShiftRows/MixColumns."],
    ),
    "m3_root": pack(
        [T("Message authentication", "Prove origin and integrity — not secrecy alone."),
         T("MAC vs hash", "MAC needs a shared secret; plain hash does not."),
         T("Digital signatures", "Asymmetric integrity + non-repudiation; DSS/DSA family.")],
        ["Authentication requirements → MAC/hash constructions → signatures.",
         "SHA/MD are hash tools inside MAC and signature schemes.",
         "Signature ≠ encryption: verify with public key, not decrypt for secrecy."],
        ["LMR: intro MACs, authentication functions, requirements.",
         "Stem “shared secret tag” → MAC; “no shared secret digest” → hash."],
    ),
    "m4_root": pack(
        [T("Kerberos", "Ticket-based network authentication with a trusted KDC."),
         T("ACL", "Subject–object permission lists for access control."),
         T("Email crypto", "PGP and S/MIME for end-to-end mail confidentiality/auth."),
         T("Network layers", "IPsec at IP; SSL/TLS at transport; SET for payment.")],
        ["Apps (Kerberos, ACL, mail) then protocol stacks (IPsec, SSL, SET).",
         "PGP = web of trust; S/MIME = CA/X.509 style PKI — classic contrast.",
         "IPsec ≠ SSL: different layer and deployment model."],
        ["LMR: Kerberos, ACL, PGP.",
         "Don’t mix SET payment flow with generic SSL shopping sites."],
    ),
    "m5_root": pack(
        [T("Intrusion & malware", "Detect misuse; viruses/worms differ in replication."),
         T("Perimeter & VPN", "Firewalls filter; VPN tunnels private traffic over public nets."),
         T("Law & forensics", "IT Acts + evidence-preserving investigation processes."),
         T("Emerging themes", "Blockchain, privacy/piracy, recent attack patterns.")],
        ["Ops security (IDS, malware, firewalls, VPN) then legal/forensic track (5.2).",
         "Forensics needs chain of custody and tool methodology, not only “find the hacker”.",
         "Privacy prevention ≠ piracy prevention — different goals."],
        ["LMR: intrusion idea, IDS techniques, viruses/worms.",
         "Email tracing belongs under forensics (headers), not PGP crypto."],
    ),

    # ----- Module 1 -----
    "1.1.1": pack(
        [T("Security attack", "Any action that compromises information security (CIA or related goals)."),
         T("Passive attack", "Eavesdropping / traffic analysis — learn without altering data."),
         T("Active attack", "Modify, fabricate, replay, or interrupt — alters system/data behaviour."),
         T("Interruption", "Availability attack: destroy or block an asset (DoS flavour)."),
         T("Interception", "Confidentiality attack: unauthorised access to an asset."),
         T("Modification / Fabrication", "Integrity attacks: change data or insert bogus objects.")],
        ["Passive vs active: secrecy of monitoring vs alteration/disruption.",
         "CIA map: interception→C, modification/fabrication→I, interruption→A.",
         "Traffic analysis is passive even if no plaintext is recovered.",
         "Masquerade and replay are active authenticity/integrity threats."],
        ["LMR: classify the stem as passive or active first.",
         "Stem “only listening / sniffing” → passive; “altering packets” → active.",
         "DoS / crash service → interruption (availability), not interception.",
         "Fabrication ≠ modification: insert new fake object vs change existing one.",
         "Trap: calling traffic analysis “active” because it feels invasive — it is passive.",
         "One-line: attacks threaten CIA; mechanisms implement services that counter them."],
        True,
    ),
    "1.1.2": pack(
        [T("Security service", "A service that enhances security of systems/data transfers (what we want)."),
         T("Security mechanism", "A process or device that detects, prevents, or recovers from attacks (how)."),
         T("Confidentiality", "Information not disclosed to unauthorised parties."),
         T("Authentication", "Assure that a communicating entity is who it claims to be."),
         T("Integrity", "Data not altered in an unauthorised manner."),
         T("Non-repudiation", "Prevent denying previous commitments or actions.")],
        ["Service = goal/abstract need; mechanism = concrete technique (e.g. encryption, MAC).",
         "Encryption is a mechanism that primarily supports confidentiality (and can support others).",
         "Access control and availability are also standard service categories in textbooks.",
         "One mechanism can support multiple services; one service may need several mechanisms."],
        ["LMR: “what vs how” — service vs mechanism is the classic stem.",
         "Stem asks for service name → confidentiality/authentication/… not “AES”.",
         "Stem asks for mechanism → cipher, hash, digital signature, firewall, etc.",
         "Authentication ≠ authorisation: identity proof vs permission to act.",
         "Non-repudiation usually needs signatures/trusted third party — not only a MAC.",
         "Trap: listing CIA alone when the question asks for ITU/X.800-style service list."],
        True,
    ),
    "1.1.3": pack(
        [T("Classical encryption", "Pre-computer / simple ciphers based on substitution and/or transposition."),
         T("Plaintext / Ciphertext", "Original message / encrypted message."),
         T("Key", "Secret parameter that selects a specific transformation from a cipher family."),
         T("Encryption / Decryption", "Plaintext→ciphertext / reverse using the key (symmetric classical case)."),
         T("Cryptography", "Art/science of designing secure transformative schemes."),
         T("Cryptanalysis", "Art/science of breaking ciphers without the key (or testing strength).")],
        ["Classical systems rely on secrecy of the algorithm+key historically; modern Kerckhoffs: algorithm public, key secret.",
         "Substitution changes symbols; transposition reorders positions — often combined.",
         "Security of classical ciphers collapses under frequency analysis and known plaintext."],
        ["LMR: define plaintext, ciphertext, key, and the two classical families.",
         "Trap: saying classical = only Caesar; Caesar is one substitution instance.",
         "Stem “rearrange letters” → transposition; “replace letters” → substitution.",
         "Don’t confuse cryptography (design) with cryptanalysis (attack/analysis).",
         "Kerckhoffs principle: assume adversary knows the algorithm.",
         "Exam one-liner: classical crypto = substitution + transposition under a shared key."],
        True,
    ),
    "1.1.4": pack(
        [T("Substitution cipher", "Replace each plaintext unit with a ciphertext unit by a mapping."),
         T("Caesar cipher", "Shift each letter by a fixed k (mod 26); key space only 25 nontrivial shifts."),
         T("Monoalphabetic", "Fixed substitution alphabet for the whole message."),
         T("Polyalphabetic", "Multiple substitution alphabets (e.g. Vigenère) — varies with position."),
         T("Playfair", "Digraph substitution using a 5×5 key square.")],
        ["Monoalphabetic preserves letter frequencies; polyalphabetic flattens them somewhat.",
         "Caesar is a tiny monoalphabetic special case — trivial brute force.",
         "Playfair works on pairs (digraphs), not single letters."],
        ["Stem “shift by 3 / ROT” → Caesar.",
         "Stem “one mapping for all letters” → monoalphabetic.",
         "Trap: claiming polyalphabetic is unbreakable — Kasiski/Friedman still apply.",
         "Frequency analysis hits monoalphabetic hardest."],
    ),
    "1.1.5": pack(
        [T("Transposition cipher", "Permute positions of plaintext symbols; symbols themselves unchanged."),
         T("Rail fence", "Write plaintext in zigzag rows; read off by rows."),
         T("Columnar transposition", "Write in a rectangle by rows; read columns in key order."),
         T("Permutation key", "The reordering rule (often derived from a keyword).")],
        ["Transposition keeps frequencies of letters; digraph/position stats change.",
         "Substitution changes identity of symbols; transposition changes order only.",
         "Product ciphers combine both for stronger classical schemes."],
        ["Stem “same letters, different order” → transposition.",
         "Trap: calling columnar a substitution because a keyword is used — keyword orders columns.",
         "Rail fence key is often the number of rails.",
         "Cryptanalysis may use anagramming / multiple anagramming on short texts."],
    ),
    "1.1.6": pack(
        [T("Cryptanalysis", "Recover plaintext and/or key by exploiting cipher weaknesses."),
         T("Ciphertext-only", "Attacker has only ciphertext."),
         T("Known-plaintext", "Attacker has plaintext–ciphertext pairs."),
         T("Chosen-plaintext / Chosen-ciphertext", "Attacker can encrypt chosen texts / decrypt chosen ciphertexts."),
         T("Brute force", "Try all keys until decryption is meaningful.")],
        ["Attack models ordered roughly by power: ciphertext-only < known < chosen.",
         "Classical monoalphabetic → frequency analysis; Vigenère → Kasiski examination.",
         "Security claims must state the assumed attack model."],
        ["Stem lists known pairs → known-plaintext, not ciphertext-only.",
         "Trap: equating “cryptanalysis” with only brute force.",
         "Exhaustive search cost scales with key space size.",
         "Modern ciphers aim to make all practical attack models infeasible."],
    ),
    "1.1.7": pack(
        [T("Steganography", "Hide the existence of a message inside cover media (image, audio, text)."),
         T("Cover / Stego-object", "Innocent carrier / carrier after embedding."),
         T("Payload", "Hidden secret data embedded in the cover."),
         T("LSB embedding", "Common image method: alter least-significant bits.")],
        ["Cryptography hides meaning; steganography hides presence — often used together.",
         "Detecting stego (steganalysis) ≠ recovering plaintext of a cipher.",
         "Security of stego often relies on undetectability, not large key spaces alone."],
        ["Stem “hide that a message exists” → steganography.",
         "Stem “make message unreadable” → cryptography.",
         "Trap: calling watermarking the same as secret messaging — related but goals differ.",
         "Capacity vs undetectability is the usual trade-off."],
    ),
    "1.1.8": pack(
        [T("Stream cipher", "Encrypts plaintext bit/byte stream, typically with a keystream XOR."),
         T("Block cipher", "Encrypts fixed-size blocks (e.g. 64 or 128 bits) under one key."),
         T("Keystream", "Pseudorandom sequence combined with plaintext (classically by XOR)."),
         T("Synchronous vs self-synchronising", "Keystream independent of ciphertext vs depends on prior ciphertext."),
         T("Padding", "Block ciphers need padding when message length is not a multiple of block size.")],
        ["Stream: low latency, no block padding; reuse of keystream is catastrophic.",
         "Block: richer algebraic structure; modes (Module 2) turn blocks into message encryption.",
         "OTP is perfect stream idea with truly random one-time keystream — impractical at scale."],
        ["Stem “XOR with running keystream” → stream cipher.",
         "Stem “encrypt 128-bit chunks” → block cipher.",
         "Trap: reusing the same stream keystream for two messages → plaintext recovery.",
         "ECB/CBC are modes of block ciphers, not stream ciphers themselves."],
    ),
    "1.1.9": pack(
        [T("Hardware security", "Protecting systems via physical/hardware roots of trust and isolation."),
         T("TPM / secure element", "Dedicated chip storing keys and performing crypto in isolation."),
         T("Side-channel", "Leakage via timing, power, EM — attacks beyond pure maths of the cipher."),
         T("Hardware Root of Trust", "Immutable/boot-anchored component that verifies later software stages.")],
        ["Software crypto can be correct yet leak via side channels on real hardware.",
         "Secure boot chains trust from ROM/firmware upward.",
         "PUFs and HSMs appear in advanced hardware-security syllabi as key storage/attestation ideas."],
        ["Stem “power analysis / timing leak” → side-channel, not cryptanalysis of the math alone.",
         "Trap: assuming AES in software is automatically safe on embedded devices.",
         "Hardware security complements, does not replace, algorithmic crypto strength.",
         "Exam: define + one example (TPM, smart card, secure enclave)."],
    ),

    # ----- Module 2.1 -----
    "2.1.1": pack(
        [T("Block cipher", "Keyed invertible transformation on n-bit blocks (typical n=64 or 128)."),
         T("Product cipher", "Composition of substitutions and permutations (Shannon-style)."),
         T("Round", "Repeated keyed mixing step; more rounds increase diffusion/confusion cost."),
         T("Key schedule", "Derives round keys from the master key."),
         T("Ideal properties", "Pseudorandom permutation behaviour under secret key; avalanche effect.")],
        ["Principles: confusion + diffusion realised via SPN or Feistel structures.",
         "Block size and key size both matter: small blocks enable codebook attacks.",
         "Modes of operation are separate from the block cipher primitive itself."],
        ["LMR: state block size, key, rounds, and why product ciphers.",
         "Stem “fixed-size chunk encryption” → block cipher principles.",
         "Trap: calling AES a Feistel cipher — AES is SPN; DES is Feistel.",
         "Avalanche: one-bit plaintext/key change should flip ~half the ciphertext bits.",
         "Don’t confuse key length with number of rounds.",
         "Exam: principles precede named algorithms (DES/AES)."],
        True,
    ),
    "2.1.2": pack(
        [T("Confusion", "Make the relationship between ciphertext and key as complex as possible."),
         T("Diffusion", "Spread plaintext statistical structure over many ciphertext bits."),
         T("Substitution", "Primary tool for confusion (S-boxes)."),
         T("Permutation / linear mixing", "Primary tool for diffusion (P-boxes, MixColumns)."),
         T("Avalanche effect", "Small input change yields large, unpredictable output change.")],
        ["Shannon: both properties needed; either alone is insufficient against cryptanalysis.",
         "DES: S-boxes (confusion) + permutation (diffusion) inside Feistel rounds.",
         "AES: SubBytes (confusion) + ShiftRows/MixColumns (diffusion)."],
        ["LMR: define confusion vs diffusion in one line each.",
         "Stem “hide key–ciphertext relation” → confusion.",
         "Stem “spread influence of each plaintext bit” → diffusion.",
         "Trap: swapping the two definitions — common MCQ fail.",
         "S-box without diffusion still leaves structure; permutation without nonlinear S-boxes is weak.",
         "Link answer to a concrete layer (S-box vs MixColumns) when asked “how AES achieves…”."],
        True,
    ),
    "2.1.3": pack(
        [T("Feistel structure", "Split block into L∥R; round function F updates one half using the other + round key."),
         T("Round function F", "Need not be invertible; overall Feistel cipher remains invertible."),
         T("Swap / combine", "Classic: L_i = R_{i−1}; R_i = L_{i−1} ⊕ F(R_{i−1}, K_i)."),
         T("Decryption", "Same structure with reverse round-key order — major engineering advantage."),
         T("DES as Feistel", "16-round Feistel network with 64-bit block (56-bit effective key).")],
        ["Feistel vs SPN: Feistel encrypts one half per round; SPN mixes the whole block each round.",
         "Invertibility of F is not required — why Feistel is flexible for design.",
         "Final swap (or not) is a DES detail — check the exact variant in the stem."],
        ["LMR: write the Li/Ri recurrence and say decryption = reverse keys.",
         "Stem “same algorithm for encrypt/decrypt” → Feistel property.",
         "Trap: AES is not Feistel; don’t force Feistel equations on AES.",
         "Why F needn’t be invertible: XOR undoes the combination if F output is known from the other half.",
         "More rounds ≠ automatically secure if F is weak — design of F matters.",
         "Exam sketch: diagram L0 R0 → rounds → ciphertext halves."],
        True,
    ),
    "2.1.4": pack(
        [T("DES", "64-bit block Feistel cipher; 56-bit effective key (+8 parity bits in 64-bit keying material)."),
         T("Initial / Final permutation", "IP and FP (IP⁻¹) bookend the 16 Feistel rounds."),
         T("f-function", "Expansion E, XOR round key, 8 S-boxes, then permutation P."),
         T("S-box", "Nonlinear 6→4 bit substitution — primary DES confusion source."),
         T("Round keys", "48-bit subkeys from key schedule (PC-1, rotations, PC-2).")],
        ["Effective security is ~56-bit key — historically breakable by brute force.",
         "S-boxes were designed against differential cryptanalysis (secret criteria historically).",
         "DES encrypt/decrypt share structure with reversed subkeys."],
        ["Stem “56-bit key / 64-bit block / 16 rounds” → DES fingerprint.",
         "Trap: saying DES key is 64-bit secure — 8 bits are parity.",
         "Don’t confuse DES f-function expansion with AES MixColumns.",
         "IP/FP add no cryptographic strength alone — they are fixed permutations."],
    ),
    "2.1.5": pack(
        [T("Brute-force vulnerability", "2^56 key space is searchable with specialised hardware (DES cracker era)."),
         T("Complementary property", "DES has a known complementary relationship exploitable in some analyses."),
         T("Weak / semi-weak keys", "Pathological keys with poor schedule behaviour (must be avoided)."),
         T("Analytical attacks", "Differential and linear cryptanalysis reduce complexity vs pure brute force (still costly for full DES).")],
        ["Practical insecurity today is mainly short key length, not failure of Feistel idea.",
         "3DES lengthens effective keying to extend life of DES hardware/software.",
         "AES was selected for larger blocks/keys and stronger design margins."],
        ["Stem “why DES is insecure now” → 56-bit exhaustive search, not “Feistel is broken”.",
         "Trap: claiming differential cryptanalysis “breaks DES instantly” — historically guided design; full attack still expensive.",
         "Weak keys are rare but examiners love the term.",
         "Security of DES ≠ security of a DES-like cipher with longer keys."],
    ),
    "2.1.6": pack(
        [T("Differential cryptanalysis", "Study how differences in plaintext pairs propagate to ciphertext differences."),
         T("Differential", "Chosen ΔP and observed ΔC statistics that leak key bits of S-boxes/rounds."),
         T("Characteristic", "Predicted difference path through rounds with some probability."),
         T("Chosen-plaintext flavour", "Typically needs many chosen pairs to amplify probabilistic biases.")],
        ["Attacks nonlinear components (S-boxes) via difference distribution tables.",
         "DES S-boxes resist DC better than random boxes — design target.",
         "Related idea: linear cryptanalysis uses linear approximations instead of differences."],
        ["Stem “plaintext difference → ciphertext difference” → differential cryptanalysis.",
         "Trap: confusing with traffic analysis or side-channel power analysis.",
         "Not the same as a simple known-plaintext lookup.",
         "Mention probability of characteristics if asked for method outline."],
    ),
    "2.1.7": pack(
        [T("ECB", "Independent encryption of each block — identical plaintext blocks → identical ciphertext."),
         T("CBC", "C_i = E_K(P_i ⊕ C_{i−1}); needs IV; hides patterns better than ECB."),
         T("CFB / OFB", "Stream-like modes from a block cipher; CFB self-synchronising; OFB keystream independent of plaintext."),
         T("CTR", "Encrypt counter values to make a keystream; parallelisable; never reuse counter under same key."),
         T("IV / nonce", "Initialisation vector or unique counter start — secrecy less critical than uniqueness (mode-dependent).")],
        ["Mode ≠ algorithm: AES-CBC is AES used in CBC mode.",
         "ECB is insecure for structured images/messages despite correct block encryption.",
         "CBC error propagation and padding oracle issues are common exam add-ons."],
        ["Stem “same blocks look same in ciphertext” → ECB weakness.",
         "Stem “XOR previous ciphertext” → CBC.",
         "Trap: OFB vs CFB — OFB does not feed ciphertext into the next encrypt input the same way.",
         "CTR: parallel encrypt, but nonce reuse is catastrophic (like stream keystream reuse)."],
    ),
    "2.1.8": pack(
        [T("Triple DES (3DES)", "Apply DES three times: typically EDE (encrypt–decrypt–encrypt) with 2 or 3 keys."),
         T("Two-key 3DES", "K1–K2–K1 pattern; intended ~112-bit security (meet-in-the-middle caveats)."),
         T("Three-key 3DES", "Independent K1,K2,K3 — strongest 3DES variant."),
         T("Why EDE", "Compatibility: if K1=K2=K3, 3DES collapses to single DES for legacy interop.")],
        ["3DES block size remains 64 bits — birthday bound limits large-volume use.",
         "Slower than AES; modern guidance prefers AES-128/256.",
         "Meet-in-the-middle means effective security is less than naïve 3×56."],
        ["Stem “encrypt decrypt encrypt with DES” → 3DES EDE.",
         "Trap: claiming 3DES has 192-bit security for three 56-bit keys — MITM reduces it.",
         "Not “three different algorithms” — three DES operations.",
         "AES replaces 3DES for new designs; 3DES is transitional/legacy."],
    ),

    # ----- Module 2.2 -----
    "2.2.1": pack(
        [T("AES", "Rijndael-based SPN standard: 128-bit block; keys 128/192/256 → 10/12/14 rounds."),
         T("SubBytes", "Nonlinear byte substitution via S-box (confusion)."),
         T("ShiftRows", "Row-wise byte rotation (helps diffusion)."),
         T("MixColumns", "Column mixing over GF(2^8) (diffusion); omitted in final round."),
         T("AddRoundKey", "XOR state with round key.")],
        ["AES is not Feistel: full-block layers each round.",
         "Key expansion generates round keys from the cipher key.",
         "Security rests on SPN design + adequate rounds, not secrecy of the algorithm."],
        ["Stem “128-bit block / SubBytes MixColumns” → AES.",
         "Trap: listing DES IP/FP as AES steps.",
         "Final round skips MixColumns — classic detail question.",
         "AES-128 means 128-bit key (and still 128-bit block), not “128 rounds”."],
    ),
    "2.2.2": pack(
        [T("Fermat’s Little Theorem", "If p prime and gcd(a,p)=1, then a^(p−1) ≡ 1 (mod p)."),
         T("Euler’s totient φ(n)", "Count of integers in 1..n−1 coprime to n."),
         T("Euler’s theorem", "If gcd(a,n)=1, then a^φ(n) ≡ 1 (mod n)."),
         T("Use in RSA", "Encryption/decryption exponents related via e·d ≡ 1 (mod φ(n)).")],
        ["Fermat is the special case of Euler when n is prime (φ(p)=p−1).",
         "These theorems justify why RSA decryption undoes encryption under modular exponentiation.",
         "Need gcd(a,n)=1 for Euler; RSA chooses primes so plaintext space is handled carefully."],
        ["Stem “a^(p−1)≡1 mod p” → Fermat.",
         "Stem “a^φ(n)≡1 mod n” → Euler.",
         "Trap: applying Fermat when modulus is composite.",
         "Link to RSA: ed=1 mod φ(n) (or mod λ(n) in modern statements)."],
    ),
    "2.2.3": pack(
        [T("Chinese Remainder Theorem (CRT)", "System x≡a_i (mod m_i) has unique solution mod M=∏m_i if moduli pairwise coprime."),
         T("Constructive use", "Combine residues to recover x modulo product of moduli."),
         T("RSA speedup", "Compute mod p and mod q separately, then CRT-combine for decryption."),
         T("Pairwise coprime", "Necessary condition for the standard unique CRT statement.")],
        ["CRT reduces large modular exponentiation to two smaller ones in RSA.",
         "Also used in some secret-sharing / multiprime constructions.",
         "If moduli not coprime, solvability needs extra congruence conditions."],
        ["Stem “unique solution modulo product of coprime moduli” → CRT.",
         "Trap: forgetting pairwise coprime hypothesis.",
         "RSA CRT decryption is an optimisation, not a different cryptosystem.",
         "Be ready for a tiny numeric example (mod 3 and mod 5)."],
    ),
    "2.2.4": pack(
        [T("Public-key cryptography", "Key pair: public key for encrypt/verify; private key for decrypt/sign."),
         T("Trapdoor one-way function", "Easy one way, hard to invert without trapdoor (private key)."),
         T("Key distribution relief", "No shared secret needed before first confidential message (vs symmetric)."),
         T("Hybrid encryption", "Use public-key to wrap a symmetric session key; bulk data uses AES/etc.")],
        ["Public-key ops are slower — practically always hybrid with symmetric ciphers.",
         "Confidentiality: encrypt with recipient’s public key; authenticity: sign with sender’s private key.",
         "Trust in public keys needs PKI or web-of-trust (later modules)."],
        ["Stem “two keys, public/private” → asymmetric principles.",
         "Trap: encrypting with private key for secrecy — that is signing territory, not confidentiality.",
         "Diffie–Hellman is key agreement, not a full encryption scheme by itself.",
         "Security assumes hard problems (factoring, discrete log) — not “public key is secret”."],
    ),
    "2.2.5": pack(
        [T("RSA setup", "Choose primes p,q; n=pq; pick e with gcd(e,φ(n))=1; d≡e⁻¹ (mod φ(n))."),
         T("Encrypt", "C = M^e mod n (public: n,e)."),
         T("Decrypt", "M = C^d mod n (private: d, and usually p,q)."),
         T("φ(n)", "(p−1)(q−1) for distinct primes p,q."),
         T("Signing variant", "Sign with d; verify with e — same maths, different goal.")],
        ["Correctness follows from Euler/Fermat: M^{ed} ≡ M (mod n) under standard conditions.",
         "Padding (OAEP etc.) is required in practice — raw RSA is malleable.",
         "Public exponent e is often 65537 for efficiency/safety conventions."],
        ["Stem “mod n with e and d inverses mod φ(n)” → RSA.",
         "Trap: publishing p and q — private factors must stay secret.",
         "n is public; factoring n yields φ(n) and thus d.",
         "Message must be encoded as integer 0 < M < n (with padding scheme)."],
    ),
    "2.2.6": pack(
        [T("Factoring threat", "If n=pq is factored, φ(n) and d are recovered — RSA breaks."),
         T("Small/exponent attacks", "Bad choices (tiny e with small M, Wiener small-d) leak information."),
         T("Common modulus", "Reusing n with different e’s for same M can be fatal."),
         T("Side channels", "Timing/power on modular exponentiation can leak d."),
         T("Padding necessity", "Textbook RSA without padding is insecure against multiple practical attacks.")],
        ["RSA security ≈ hardness of factoring n (and related RSA problems) under good parameters.",
         "Key size must grow over time (historically 1024→2048+ bits).",
         "Implementation bugs often kill RSA faster than asymptotic factoring breakthroughs."],
        ["Stem “why RSA fails if p,q known” → compute φ then d.",
         "Trap: “RSA is secure because e is secret” — e is public.",
         "Don’t claim quantum-safe: Shor’s algorithm threatens factoring/DL based schemes.",
         "Hybrid use doesn’t remove need for strong RSA parameters on the key wrap."],
    ),

    # ----- Module 3.1 -----
    "3.1.1": pack(
        [T("Message authentication", "Verify that a message is from the claimed sender and was not altered."),
         T("MAC (idea)", "Short authentication tag computed with a shared secret key."),
         T("Impersonation / alteration threats", "Active attacks that authentication aims to detect."),
         T("Secrecy vs authenticity", "Encryption alone does not always authenticate; auth alone does not encrypt.")],
        ["Introduces why confidentiality mechanisms are insufficient for integrity/origin.",
         "MACs are symmetric; digital signatures are asymmetric counterparts.",
         "Replay may still succeed unless freshness (nonces/timestamps) is added."],
        ["LMR: authentication ≠ encryption — say both explicitly in answers.",
         "Stem “shared secret tag on a message” → MAC introduction.",
         "Stem “anyone can verify with public key” → signature, not MAC.",
         "Trap: equating checksum/CRC with cryptographic MAC — CRC has no key.",
         "Active modification without detection is the motivating attack.",
         "One-liner: MAC provides integrity + origin authentication under shared key."],
        True,
    ),
    "3.1.2": pack(
        [T("Authentication function", "Function producing an authenticator from message (±key/secret)."),
         T("Message encryption as authenticator", "Sometimes ciphertext itself is used — weak/ambiguous without structure."),
         T("Message authentication code", "Keyed function; verifier recomputes tag with shared key."),
         T("Hash function authenticator", "Unkeyed digest; needs additional binding (e.g. encrypt digest, or HMAC).")],
        ["Three classical textbook classes: encryption, MAC, hash-based schemes.",
         "Hash alone is public — attacker can recompute digest after modification.",
         "MAC binds secret key so only parties with K can forge tags (computationally)."],
        ["LMR: list the three authentication-function classes.",
         "Stem “no key, fixed-length digest” → hash function path.",
         "Stem “keyed tag” → MAC path.",
         "Trap: saying encrypted message automatically authenticates — malleable ciphers break this.",
         "HMAC = hash used inside a keyed MAC construction.",
         "Compare: MAC secret shared; signature private signing key."],
        True,
    ),
    "3.1.3": pack(
        [T("Disclosure protection", "Not the primary MAC goal — that’s confidentiality."),
         T("Content integrity", "Detect modification of message content."),
         T("Origin authentication", "Assure message originated from claimed sender."),
         T("Sequencing / timeliness", "Detect replay, reordering, delay when required by the application."),
         T("Non-repudiation (optional)", "Usually needs signatures/TTP — not provided by ordinary MAC.")],
        ["Requirements depend on threat model: integrity alone vs integrity+freshness.",
         "MAC meets integrity+origin among parties sharing K; not non-repudiation to third parties.",
         "Encryption requirements are separate — mix only when the stem asks for both."],
        ["LMR: integrity + authenticity are the core MAC requirements.",
         "Stem “prove to a judge Alice sent it” → signature/non-repudiation, not MAC.",
         "Stem “detect altered bits in transit” → integrity requirement.",
         "Replay: same valid MAC can be resent — need nonce/timestamp countermeasures.",
         "Trap: listing confidentiality as a MAC requirement.",
         "Be ready to contrast MAC requirements vs digital signature requirements."],
        True,
    ),
    "3.1.4": pack(
        [T("MAC", "MAC_K(M) → tag; verify by recomputing and comparing tags."),
         T("HMAC", "Keyed-hash MAC: hash with key mixed via ipad/opad construction."),
         T("CBC-MAC / CMAC", "MAC from block cipher chaining (careful with variable-length messages)."),
         T("Forgery resistance", "Without K, producing a valid tag for a new message should be infeasible.")],
        ["MAC uses shared secret → both sides can generate tags (no non-repudiation).",
         "Truncating tags reduces security bits — length is an exam parameter sometimes.",
         "Encrypt-then-MAC vs MAC-then-encrypt ordering matters in protocol design."],
        ["Stem “recompute tag with shared key” → MAC verification.",
         "Trap: publishing the MAC key with the message.",
         "HMAC needs a cryptographic hash (SHA family), not a CRC.",
         "Unlike signatures, verifier must already share K with sender."],
    ),
    "3.1.5": pack(
        [T("SHA family", "Secure Hash Algorithm standards (SHA-1 legacy; SHA-2/SHA-3 modern)."),
         T("SHA-1", "160-bit digest — collision-broken for practical attacks; avoid for new security."),
         T("SHA-256", "SHA-2 variant with 256-bit digest — common integrity workhorse."),
         T("One-way / compression", "Fixed-length output from arbitrary-length input via iterated compression.")],
        ["Hash properties: preimage, second-preimage, collision resistance.",
         "SHA used inside HMAC, digital signatures, and fingerprinting.",
         "SHA-3 (Keccak) is a different sponge construction from SHA-2 Merkle–Damgård."],
        ["Stem “160-bit NIST hash” → SHA-1 (historical).",
         "Trap: treating SHA as encryption — hashes are not secret-key reversible transforms.",
         "Collision ≠ preimage: collision finds any two messages; preimage inverts a digest.",
         "Longer digest generally raises brute-force collision cost (birthday bound)."],
    ),
    "3.1.6": pack(
        [T("Message digest", "Fixed-length hash output representing a message’s fingerprint."),
         T("MD5", "128-bit digest — broken for collisions; legacy checksum only."),
         T("Integrity check", "Compare digests to detect accidental/malicious change (if digest protected)."),
         T("Digest vs MAC", "Digest unkeyed; MAC keyed — digests alone don’t authenticate origin.")],
        ["“Message digest” often means the hash value in exam language (MD5/SHA).",
         "Signing a digest is how practical digital signatures work on large files.",
         "Unprotected digest sent with a message can be recomputed by an attacker after tampering."],
        ["Stem “128-bit fingerprint / Ron Rivest MD” → MD5.",
         "Trap: using MD5 for security-critical signatures today.",
         "Digest length is not confidentiality strength.",
         "Protect the digest (MAC/sign/encrypt) or the channel — don’t rely on bare MD."],
    ),

    # ----- Module 3.2 -----
    "3.2.1": pack(
        [T("Digital signature", "Asymmetric authenticator binding message to signer’s private key."),
         T("Sign / Verify", "Sign with private key; verify with corresponding public key."),
         T("Non-repudiation", "Signer cannot credibly deny the signature if private key was not compromised."),
         T("Hash-then-sign", "Hash message first; sign the digest for efficiency.")],
        ["Signatures provide integrity + origin + non-repudiation; MACs do not give third-party non-repudiation.",
         "Anyone with the public key can verify — no shared secret required.",
         "Key compromise invalidates past trust — revocation matters."],
        ["Stem “private key creates, public key checks” → digital signature.",
         "Trap: encrypting with public key and calling it a signature.",
         "Signature does not hide message content unless combined with encryption.",
         "Contrast with MAC: shared secret vs key pair."],
    ),
    "3.2.2": pack(
        [T("DSS", "NIST Digital Signature Standard specifying approved signature algorithms."),
         T("DSA", "Digital Signature Algorithm (original DSS algorithm) based on discrete log in a subgroup."),
         T("Parameters", "Global domain parameters (p,q,g) plus per-user key pair."),
         T("Modern DSS scope", "May include DSA, RSA signatures, ECDSA depending on revision era.")],
        ["DSS is the standard framework; DSA is a specific algorithm often taught under DSS.",
         "DSA signatures use per-message randomness k — reuse of k is catastrophic.",
         "Unlike RSA, classical DSA is signature-only (not encryption)."],
        ["Stem “NIST signature standard” → DSS.",
         "Stem “discrete log subgroup signature” → DSA.",
         "Trap: saying DSS encrypts files — it standardises signatures.",
         "Random nonce k must be unique and secret per signature."],
    ),
    "3.2.3": pack(
        [T("DSA signing", "Compute r from g^k mod p; s from k⁻¹(H(M)+x·r) mod q — schematic form."),
         T("DSA verify", "Recompute using public y=g^x and check r matches reconstructed value."),
         T("Correctness idea", "Verification equation holds iff s,r came from private x and hash H(M)."),
         T("Security basis", "Hardness of discrete logarithm in the chosen group.")],
        ["Proof/correctness shows verify accepts honest signatures and rejects altered M (w.h.p.).",
         "Private key x never leaves the signer; public y is published.",
         "Hash function strength is part of the overall signature security."],
        ["Stem asks to “prove/show DSA works” → expand verify equals r using algebra mod q.",
         "Trap: omitting the hash H(M) in the equations.",
         "If k leaks or repeats, x can be recovered — implementation proof obligation.",
         "Don’t paste RSA ed≡1 proof when the question is DSA discrete-log proof."],
    ),

    # ----- Module 4.1 -----
    "4.1.1": pack(
        [T("Kerberos", "Trusted third-party authentication protocol using tickets and symmetric crypto."),
         T("KDC", "Key Distribution Center: Authentication Server (AS) + Ticket Granting Server (TGS)."),
         T("TGT", "Ticket-Granting Ticket — proves AS authentication to obtain service tickets."),
         T("Service ticket", "Credential presented to an application server for access."),
         T("Authenticator", "Fresh encrypted blob (timestamp) proving possession of session key — anti-replay.")],
        ["Client authenticates to AS → TGT → TGS issues service ticket → server verifies.",
         "Passwords typically used to derive key for AS exchange; long-term keys stay with KDC/servers.",
         "Kerberos assumes loosely synchronised clocks because of timestamp authenticators.",
         "Provides mutual authentication options; does not by itself encrypt all application data."],
        ["LMR: AS → TGT → TGS → service ticket flow in order.",
         "Stem “ticket-based campus login / KDC” → Kerberos.",
         "Trap: calling Kerberos a public-key PKI system — classic teaching version is symmetric.",
         "TGT ≠ service ticket: TGT talks to TGS; service ticket talks to the app server.",
         "Clock skew failures are a classic operational Kerberos symptom.",
         "Contrast with SSL: Kerberos is SSO/authn in a realm; SSL secures a transport session."],
        True,
    ),
    "4.1.2": pack(
        [T("ACL", "Access Control List: permissions attached to an object listing allowed subjects/actions."),
         T("Subject / Object", "Active entity (user/process) / passive resource (file, socket)."),
         T("Access right", "Operation permitted: read, write, execute, delete, etc."),
         T("Capability (contrast)", "Unforgeable token held by subject naming allowed object operations."),
         T("DAC flavour", "Owner-controlled ACLs are common discretionary access control realisation.")],
        ["ACL is object-centric; capability list is subject-centric — dual views of an access matrix.",
         "ACLs scale by resource; checking “all objects user X can access” may be costly.",
         "Authentication identifies subject; ACL authorises actions afterward."],
        ["LMR: define ACL as per-object subject→rights list.",
         "Stem “permissions on the file listing users” → ACL.",
         "Stem “token carried by process” → capability, not ACL.",
         "Trap: mixing authentication (Kerberos) with authorisation (ACL).",
         "Empty/default-deny vs default-allow policies change security posture.",
         "Exam contrast: access matrix row = capability list; column = ACL."],
        True,
    ),
    "4.1.3": pack(
        [T("PGP", "Pretty Good Privacy — email/file encryption and signing with hybrid crypto."),
         T("Web of trust", "Users sign others’ keys; trust is decentralised, not only CA-based."),
         T("Session key", "Random symmetric key encrypts the message; RSA/ElGamal wraps that key."),
         T("Signature in PGP", "Hash of message signed with sender’s private key for authenticity."),
         T("Key rings", "Local collections of public/private keys and trust metadata.")],
        ["Confidentiality: symmetric bulk + public-key wrap; authenticity: detached/inline signatures.",
         "PGP trust model ≠ S/MIME X.509 CA hierarchy — frequent exam contrast.",
         "Compression often precedes encryption in the PGP message pipeline."],
        ["LMR: hybrid encryption + web of trust are the PGP headlines.",
         "Stem “friends sign keys / no central CA required” → PGP.",
         "Trap: saying PGP only uses RSA on the whole email body — bulk is symmetric.",
         "Private key decrypts the session key, not each byte directly.",
         "Revocation and key authenticity remain user-managed problems.",
         "Contrast with S/MIME: corporate PKI vs web of trust."],
        True,
    ),
    "4.1.4": pack(
        [T("S/MIME", "Secure/Multipurpose Internet Mail Extensions — MIME + crypto based on PKI."),
         T("X.509 certificates", "CA-issued bindings of identity to public keys used by S/MIME."),
         T("Enveloped data", "Encrypted content for confidentiality."),
         T("Signed data", "Cryptographic signature over MIME entities for authenticity/integrity.")],
        ["S/MIME integrates with existing CA hierarchies familiar to enterprises.",
         "Same hybrid crypto idea as PGP, different trust and formatting model.",
         "Certificate validation and CRL/OCSP issues dominate real deployments."],
        ["Stem “MIME security with X.509 / CA” → S/MIME.",
         "Trap: web of trust answer when the stem says corporate CA.",
         "S/MIME ≠ SSL: mail end-to-end vs transport session to a server.",
         "Both signed-only and encrypted+signed messages are possible."],
    ),

    # ----- Module 4.2 -----
    "4.2.1": pack(
        [T("IPsec", "Security architecture for the Internet Protocol — AH, ESP, and key management."),
         T("AH", "Authentication Header — integrity/authenticity of IP packet parts (no encryption)."),
         T("ESP", "Encapsulating Security Payload — confidentiality ± integrity for payload."),
         T("SA / SPD", "Security Association (crypto params) / Security Policy Database (what to protect)."),
         T("Transport vs tunnel", "Protect upper-layer payload vs encapsulate whole IP packet (VPN-style).")],
        ["IPsec operates at network layer — transparent to many apps.",
         "IKE (or IKEv2) negotiates SAs and keys.",
         "AH alone does not provide confidentiality; ESP can provide both."],
        ["Stem “AH vs ESP” → integrity-only vs encrypting payload.",
         "Tunnel mode common for VPNs between gateways.",
         "Trap: placing IPsec at the application layer like PGP.",
         "SPD decides; SA describes the actual negotiated connection."],
    ),
    "4.2.2": pack(
        [T("SSL/TLS", "Secure transport-layer protocol providing confidentiality, integrity, and authentication."),
         T("Handshake", "Negotiate version/ciphers, authenticate (usually server cert), derive session keys."),
         T("Record protocol", "Fragments, optionally compresses, MACs, and encrypts application data."),
         T("Certificates", "X.509 server (and optional client) certificates bind names to public keys.")],
        ["SSL is historical name; TLS is the standardised successor — exams often say SSL loosely.",
         "Ends at transport: protects hop to the server, not necessarily end-to-end through intermediaries.",
         "Cipher suites select key exchange, bulk cipher, and MAC/AEAD."],
        ["Stem “browser padlock / HTTPS” → SSL/TLS.",
         "Trap: equating SSL with end-to-end mail crypto (PGP/S/MIME).",
         "Handshake failure ≠ record encryption bug — different subprotocols.",
         "IPsec vs SSL: IP layer vs TCP/application-above-TCP deployment."],
    ),
    "4.2.3": pack(
        [T("SET", "Secure Electronic Transaction — payment-card purchase protocol with dual signatures."),
         T("Dual signature", "Links order info for merchant and payment info for bank without cross-revealing."),
         T("Payment gateway", "Interface between merchant and card issuer/acquirer networks."),
         T("Certificates", "Cardholder, merchant, and bank certificates in the SET PKI.")],
        ["SET aims: authenticate parties, protect payment data, ensure integrity, privacy split merchant/bank.",
         "Merchant need not see full payment credentials; bank need not see full order details.",
         "Historically important exam topic; real web payments often use TLS + tokenisation instead."],
        ["Stem “dual signature / merchant vs bank views” → SET.",
         "Trap: describing SET as “just SSL on a shop website”.",
         "SET is application-level payment security, not a general VPN.",
         "Remember three certificate roles: cardholder, merchant, payment gateway."],
    ),

    # ----- Module 5.1 -----
    "5.1.1": pack(
        [T("Intrusion", "Unauthorised act of using, misusing, or attempting to misuse a system."),
         T("Intruder classes", "Masquerader (outsider), misfeasor (insider abuse), clandestine user (seizes control)."),
         T("Attack stages", "Reconnaissance → gain access → privilege escalation → maintain/cover tracks (typical pattern)."),
         T("Security audit trail", "Logs that later support detection and forensics.")],
        ["Intrusion is broader than “virus” — includes account abuse and unauthorised access attempts.",
         "Prevention, detection, and recovery are complementary controls.",
         "Insider misfeasor already has credentials — different detection profile than outsider."],
        ["LMR: define intrusion + name the three intruder classes.",
         "Stem “legitimate user exceeds authority” → misfeasor.",
         "Stem “outsider pretends to be legitimate” → masquerader.",
         "Trap: treating every malware incident as the definition of intrusion (overlap, not identity).",
         "Clandestine user seizes supervisory control to evade auditing.",
         "Link forward to IDS techniques (5.1.2) as the detection response."],
        True,
    ),
    "5.1.2": pack(
        [T("IDS", "Intrusion Detection System — monitors for suspicious activity and alerts/responds."),
         T("Host-based IDS (HIDS)", "Watches OS logs, files, processes on a single host."),
         T("Network-based IDS (NIDS)", "Watches packets/traffic on a network segment."),
         T("Signature detection", "Match known attack patterns — low novelty, fewer novel false mysteries."),
         T("Anomaly detection", "Flag deviation from baseline behaviour — can catch unknowns, more false positives.")],
        ["Detection ≠ prevention: IDS may be passive; IPS actively blocks.",
         "Hybrid deployments combine HIDS + NIDS and signature + anomaly.",
         "Tuning thresholds trades false positives vs false negatives."],
        ["LMR: contrast signature vs anomaly; HIDS vs NIDS.",
         "Stem “known CVE exploit pattern in DB” → signature-based.",
         "Stem “user suddenly downloads 50GB at 3am” → anomaly-based.",
         "Trap: claiming anomaly detection has no false positives.",
         "NIDS may miss encrypted payload details; HIDS sees host outcomes.",
         "Exam: state where sensors sit and what data they consume."],
        True,
    ),
    "5.1.3": pack(
        [T("Virus", "Malware that attaches to a host program/file and spreads when that host runs/shares."),
         T("Worm", "Standalone malware that self-replicates across networks without needing a host file."),
         T("Trojan", "Malware disguised as legitimate software — does not self-replicate by classic definition."),
         T("Payload", "Damaging or spying action delivered after infection (erase, encrypt ransomware, backdoor)."),
         T("Infection vectors", "Email attachments, removable media, network services, drive-by downloads.")],
        ["Virus needs human/host execution chain; worm emphasises autonomous network propagation.",
         "Polymorphic/metamorphic viruses change code to evade signatures.",
         "Prevention: patching, least privilege, filtering, user awareness — plus AV/EDR detection."],
        ["LMR: virus vs worm one-line contrast is the highest-yield stem.",
         "Stem “needs a program to attach to” → virus.",
         "Stem “self-propagates through network services” → worm.",
         "Trap: calling all malware “viruses”.",
         "Trojan ≠ worm: deception vs replication mechanism.",
         "Macro viruses live in documents — still viruses by attachment model."],
        True,
    ),
    "5.1.4": pack(
        [T("Firewall", "Policy enforcement point controlling traffic between networks (typically perimeter)."),
         T("Packet filter", "Allow/deny by header fields (IP, port, protocol) — stateless or stateful."),
         T("Stateful inspection", "Tracks connection state, not only isolated packets."),
         T("Application proxy / gateway", "Intermediates application protocols; can enforce deep policy."),
         T("DMZ", "Screened subnet for public services separated from internal LAN.")],
        ["Default-deny is safer than default-allow when designing rulebases.",
         "Firewalls do not replace patching, authn, or encryption — choke-point control only.",
         "Egress filtering limits data exfiltration and botnet callbacks."],
        ["Stem “filter packets by port/IP at boundary” → packet-filtering firewall.",
         "Trap: assuming firewalls stop all insider USB malware.",
         "Proxy vs packet filter: application awareness vs speed/simplicity.",
         "DMZ hosts are semi-trusted — still hardened, not “internal”."],
    ),
    "5.1.5": pack(
        [T("IT Act (India context)", "Legal framework addressing cyber offences, electronic records, and intermediary issues (exam locale often IT Act 2000/amendments)."),
         T("Cyber crime categories", "Unauthorised access, data theft, fraud, obscenity, identity offences, etc., as defined in statute."),
         T("Electronic evidence", "Digital records admissible subject to procedural authenticity requirements."),
         T("Compliance duties", "Organisations may need reasonable security practices and privacy safeguards under applicable rules.")],
        ["Law defines offences and penalties; technical controls implement compliance.",
         "Jurisdiction and attribution are hard — logs and forensics matter in prosecution.",
         "Global flavours: CFAA-like unauthorised access laws, GDPR-style privacy, etc., depending on syllabus focus."],
        ["Stem “legal act for cyber offences in India” → IT Act family.",
         "Trap: citing only technical firewalls when asked for legal measures.",
         "Know that amendments expanded offence coverage after early IT Act.",
         "Privacy/piracy topics (5.1.9) overlap but are not identical to the Act overview."],
    ),
    "5.1.6": pack(
        [T("VPN", "Virtual Private Network — private connectivity over a public network using tunnelling + crypto."),
         T("Tunnel", "Encapsulation of private packets inside outer packets across the Internet."),
         T("Remote-access VPN", "User to gateway (road warrior)."),
         T("Site-to-site VPN", "Gateway to gateway linking networks."),
         T("IPsec / SSL VPN", "Common technology choices for tunnel security.")],
        ["VPN provides confidentiality and integrity of transit; endpoints still need hardening.",
         "Splits tunnelling vs full tunnel is a policy/security trade-off.",
         "Related to IPsec tunnel mode (4.2.1) as a primary realisation."],
        ["Stem “secure private link over Internet” → VPN.",
         "Trap: VPN = anonymity network (Tor) — different goals.",
         "Remote-access ≠ site-to-site topology.",
         "Weak auth on VPN concentrators undoes strong tunnel crypto."],
    ),
    "5.1.7": pack(
        [T("DDoS", "Distributed denial of service — overwhelm availability with many sources."),
         T("Phishing / social engineering", "Trick users into revealing credentials or running malware."),
         T("Ransomware", "Encrypts or locks data for extortion."),
         T("APT", "Advanced Persistent Threat — long-term targeted intrusion."),
         T("Mitigations", "Patching, MFA, segmentation, backups, filtering, threat intel, least privilege.")],
        ["Attacks evolve; measures combine prevention, detection, and resilience (backups/IR).",
         "Technical and human layers both required — phishing bypasses crypto.",
         "Zero-day vs n-day: unknown vs known-unpatched exploits."],
        ["Stem “many bots flood a website” → DDoS.",
         "Trap: single antivirus as complete answer to APTs.",
         "Ransomware defence emphasises offline/immutable backups.",
         "Map each attack to CIA: DDoS→A, ransomware→A/I/C mix, sniffing→C."],
    ),
    "5.1.8": pack(
        [T("Blockchain", "Append-only distributed ledger of chained, hashed blocks agreed by consensus."),
         T("Block", "Batch of transactions plus hash linking to previous block."),
         T("Consensus", "Protocol (PoW/PoS/etc.) for agreeing on the next valid chain state."),
         T("Immutability (practical)", "Altering history requires redoing consensus work / controlling majority — costly."),
         T("Smart contract", "Programmable logic executed by the chain’s VM (platform-dependent).")],
        ["Integrity and transparency are strengths; confidentiality and key custody are not automatic.",
         "Public vs permissioned ledgers change who may validate.",
         "Hash chaining detects tampering; consensus prevents easy forks by attackers."],
        ["Stem “hash-linked distributed ledger” → blockchain.",
         "Trap: “blockchain = Bitcoin only” or “blockchain encrypts all data”.",
         "Lost private keys ⇒ lost assets — crypto custody risk.",
         "Not a substitute for access control inside enterprise apps by default."],
    ),
    "5.1.9": pack(
        [T("Internet privacy", "Control over personal data collection, use, and disclosure online."),
         T("PII", "Personally Identifiable Information — data that identifies a person."),
         T("Piracy prevention", "Technical/legal measures against unauthorised copying/distribution of copyrighted works."),
         T("DRM", "Digital Rights Management — access-control mechanisms on digital content."),
         T("Tracking / cookies", "Common privacy threats via behavioural profiling.")],
        ["Privacy focuses on personal data rights; piracy focuses on IP infringement — related policy space, different aims.",
         "HTTPS, minimisation, consent, and anonymisation support privacy.",
         "Watermarking/DRM/legal takedowns support anti-piracy."],
        ["Stem “stop illegal movie copies” → piracy/DRM/legal — not VPN alone.",
         "Stem “limit profiling of users” → privacy controls.",
         "Trap: equating encryption with complete privacy (metadata still leaks).",
         "IT Acts/IP law provide legal backing; tech provides enforcement aids."],
    ),

    # ----- Module 5.2 -----
    "5.2.1": pack(
        [T("Cyber forensics", "Collection, preservation, analysis, and presentation of digital evidence."),
         T("Goal", "Reconstruct events for investigation/court while maintaining evidential integrity."),
         T("Volatile vs non-volatile", "RAM/network state vs disk — acquisition order matters."),
         T("Chain of custody", "Documented handling history proving evidence was not tampered with.")],
        ["Forensics is process-heavy: methodology beats ad-hoc “looking around”.",
         "Differs from incident response containment — though they interact.",
         "Legal admissibility constrains tools and procedures."],
        ["Stem “preserve and analyse digital evidence for court” → cyber forensics.",
         "Trap: modifying the live suspect disk without imaging first.",
         "Overview before process details (5.2.2) and tools (5.2.4).",
         "Hashing images verifies integrity of copies."],
    ),
    "5.2.2": pack(
        [T("Identification", "Recognise potential evidence sources and scope."),
         T("Preservation", "Isolate, image, write-block — prevent change."),
         T("Collection / acquisition", "Bit-for-bit imaging and labelling of media."),
         T("Examination / analysis", "Recover artefacts, timelines, deleted data, logs."),
         T("Presentation", "Report findings clearly for investigators/court.")],
        ["Order of volatility guides what to capture first on a live system.",
         "Write blockers and hash verification protect preservation claims.",
         "Analysis must be reproducible from the forensic image."],
        ["Stem lists phases — give them in standard order.",
         "Trap: analysing the original disk read/write instead of a verified image.",
         "Presentation without chain-of-custody docs weakens the case.",
         "Documentation is continuous, not only the final report."],
    ),
    "5.2.3": pack(
        [T("Criminal investigation", "Support prosecution of hacking, fraud, abuse, etc."),
         T("Civil / corporate", "IP theft, employee misuse, policy violations."),
         T("Incident response support", "Scope breach, attribute activity, guide recovery."),
         T("Intelligence / threat hunting", "Longer-term artefact study across cases.")],
        ["Same forensic process adapts to different legal/business contexts.",
         "Corporate cases still need careful preservation if litigation is possible.",
         "Applications span endpoints, servers, mobile, and cloud artefacts."],
        ["Stem “use in court vs HR case” → criminal vs corporate application framing.",
         "Trap: assuming only police perform forensics — enterprises run internal teams.",
         "Cloud apps add provider logs and legal process constraints.",
         "Tie application back to evidence types (5.2.5)."],
    ),
    "5.2.4": pack(
        [T("Imaging tools", "Create forensic disk images (e.g. dd-family, FTK Imager-class tools)."),
         T("Analysis suites", "EnCase, Autopsy/Sleuth Kit-class platforms for browsing artefacts."),
         T("Write blocker", "Hardware/software preventing writes to evidence media."),
         T("Hashing utilities", "MD5/SHA digests to verify image integrity (MD5 legacy for checksumming)."),
         T("Memory tools", "Capture/analyse RAM for volatile evidence.")],
        ["Tool choice must be defensible and validated; version notes belong in reports.",
         "Open-source and commercial tools can both be acceptable if procedures are sound.",
         "Network packet captures (Wireshark-class) complement host forensics."],
        ["Stem “prevent writes while imaging” → write blocker.",
         "Trap: installing analysis software on the suspect disk.",
         "Always hash before/after acquisition and record algorithms.",
         "Memory tools matter when disk alone lacks encryption keys/malware."],
    ),
    "5.2.5": pack(
        [T("Digital evidence", "Information of probative value stored or transmitted in digital form."),
         T("Locard’s principle (digital)", "Contact leaves traces — logs, metadata, remnants."),
         T("Metadata", "Data about data: timestamps, authors, EXIF, filesystem attributes."),
         T("Integrity of evidence", "Protected via imaging, hashing, custody, and controlled analysis.")],
        ["Evidence may be latent (deleted/slack) or active files/logs.",
         "Timestamps need timezone and clock-skew interpretation.",
         "Original vs working copy: analyse copies; preserve originals."],
        ["Stem “hash of image matches” → integrity verification of evidence.",
         "Trap: editing screenshots as “primary evidence” without raw sources.",
         "Metadata can be forged — corroborate across multiple artefacts.",
         "Admissibility needs relevance, authenticity, and lawful collection."],
    ),
    "5.2.6": pack(
        [T("Windows artefacts", "Event logs, Registry, Prefetch, LNK, USN journal, user profiles."),
         T("Unix/Linux artefacts", "syslog/journald, auth logs, shell history, cron, package logs, /proc."),
         T("Filesystem differences", "NTFS vs ext4/XFS — different metadata and recovery quirks."),
         T("Live response", "Collect volatile data with known-good tools before power-down decisions.")],
        ["OS-specific knowledge drives where evidence lives.",
         "Admin privileges and rootkits can undermine live collection trustworthiness.",
         "Same investigative questions; different artefact maps per OS."],
        ["Stem “Windows Registry persistence” → Windows investigation artefacts.",
         "Stem “/var/log/auth.log brute force” → Unix investigation.",
         "Trap: applying only Windows tool paths on a Linux disk image.",
         "Note timezone and UTC in log correlation across systems."],
    ),
    "5.2.7": pack(
        [T("Email tracing", "Follow Received headers and related metadata to reconstruct message path."),
         T("Received headers", "Added by MTAs; read typically bottom-up for origin path."),
         T("Message-ID", "Unique identifier useful for correlation across servers."),
         T("Spoofing caveat", "From: can be forged; trust server-added Received chains more."),
         T("Supporting logs", "MTA logs, spam gateway logs, DNS/IP WHOIS for hop investigation.")],
        ["Tracing establishes path/attribution hypotheses — not always a single “smoking gun”.",
         "Combine headers with server logs; headers alone can be incomplete or forged in parts.",
         "Different from PGP crypto: tracing is forensic reconstruction of delivery."],
        ["Stem “analyse Received: lines” → email tracing.",
         "Trap: trusting visible From: address as proof of origin.",
         "Bottom-most Received often closest to originating MTA (with caveats).",
         "Timezones and relay delays matter when building timelines."],
    ),
}
