#!/usr/bin/env python3
"""CSIT745 v2 — Module 4 (Models and Hypothesis) content pack.

Merges into subjects/csit745/v2/data/ without wiping other modules.
Source: subjects/csit745/v2/source/module_4.txt (PDF pp. 87–130).
Conceptual focus; skips pure calculation-table drills.
"""
from __future__ import annotations

from merge_util import merge_module

MODULE_ID = "m4"
MODULE_NUM = 4
MODULE_TITLE = "Module IV · Models and Hypothesis"


def C(
    section: str,
    title: str,
    pages: list[int],
    quick: str,
    key_ideas: list[str],
    detail: list[str],
    source_quote: str,
    related: list[str],
    *,
    compare: str | None = None,
    example: str | None = None,
) -> dict:
    cid = section
    out = {
        "id": cid,
        "title": title,
        "module": MODULE_NUM,
        "section": section,
        "pages": pages,
        "quick": quick,
        "keyIdeas": key_ideas,
        "detail": detail,
        "sourceQuote": source_quote,
        "related": related,
    }
    if compare:
        out["compare"] = compare
    if example:
        out["example"] = example
    return out


def Q(
    section: str,
    n: int,
    stem: str,
    options: list[str],
    correct: int,
    explanation: str,
    *,
    difficulty: str = "medium",
) -> dict:
    assert len(options) == 4 and 0 <= correct <= 3
    return {
        "id": f"m4-{section}-q{n}",
        "conceptId": section,
        "module": MODULE_NUM,
        "stem": stem,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "difficulty": difficulty,
    }


TREE_CHILDREN = [
    {
        "id": "4.1",
        "title": "4.1 Hypothesis Testing",
        "children": [
            {"id": "4.1.1", "title": "4.1.1 Introduction to Hypothesis", "conceptId": "4.1.1"},
            {"id": "4.1.2", "title": "4.1.2 Null and Alternate Hypothesis", "conceptId": "4.1.2"},
            {"id": "4.1.3", "title": "4.1.3 Type I and Type II Error", "conceptId": "4.1.3"},
            {"id": "4.1.4", "title": "4.1.4 One-Tailed and Two-Tailed Test", "conceptId": "4.1.4"},
            {"id": "4.1.5", "title": "4.1.5 Degree of Freedom", "conceptId": "4.1.5"},
            {"id": "4.1.6", "title": "4.1.6 Confidence Intervals", "conceptId": "4.1.6"},
            {"id": "4.1.7", "title": "4.1.7 Level of Significance / Confidence Coefficient", "conceptId": "4.1.7"},
            {"id": "4.1.8", "title": "4.1.8 Rejection and Non-rejection Regions", "conceptId": "4.1.8"},
            {"id": "4.1.9", "title": "4.1.9 Hypothesis Testing Procedure", "conceptId": "4.1.9"},
            {"id": "4.1.10", "title": "4.1.10 Types of Tests", "conceptId": "4.1.10"},
            {"id": "4.1.11", "title": "4.1.11 How to Select a Test", "conceptId": "4.1.11"},
        ],
    },
    {
        "id": "4.2",
        "title": "4.2 Parametric Test",
        "children": [
            {"id": "4.2.1", "title": "4.2.1 Important Parametric Tests", "conceptId": "4.2.1"},
            {"id": "4.2.2", "title": "4.2.2 Single Mean Using Z-statistic", "conceptId": "4.2.2"},
            {"id": "4.2.3", "title": "4.2.3 Single Mean Using T-statistic", "conceptId": "4.2.3"},
            {"id": "4.2.4", "title": "4.2.4 Hypothesis Testing for Population Proportions", "conceptId": "4.2.4"},
            {"id": "4.2.5", "title": "4.2.5 Variance vs Hypothesised Population Variance", "conceptId": "4.2.5"},
            {"id": "4.2.6", "title": "4.2.6 Equality of Variances (Two Populations)", "conceptId": "4.2.6"},
            {"id": "4.2.7", "title": "4.2.7 ANOVA for Fixed Effect Model", "conceptId": "4.2.7"},
            {"id": "4.2.8", "title": "4.2.8 Total, Treatment & Error Sum of Squares", "conceptId": "4.2.8"},
            {"id": "4.2.9", "title": "4.2.9 ANOVA for Random Effect Model", "conceptId": "4.2.9"},
            {"id": "4.2.10", "title": "4.2.10 Single Factor Experiment", "conceptId": "4.2.10"},
            {"id": "4.2.11", "title": "4.2.11 Model Adequacy Checking", "conceptId": "4.2.11"},
        ],
    },
]

CONCEPTS = {
    "4.1.1": C(
        "4.1.1",
        "Introduction to Hypothesis",
        [87, 88, 89],
        "A hypothesis is a tentative, testable statement about a research problem that may or may not be true and must be verified empirically.",
        [
            "“Hypo” = subject to verification; “thesis” = statement of a problem’s solution.",
            "Unlike a theory (tested, well-substantiated explanation), a hypothesis is provisional.",
            "Types include simple, complex, empirical/working, null, alternative, logical, and statistical.",
            "Simple: relation between two variables (cause → effect); complex: more than two variables.",
            "Mutual-fund illustration: H0 / H1 / H2 phrased so decisions (launch or not) follow which claim is supported.",
        ],
        [
            "Hypothesis testing compares mutually exclusive statements about a population using sample data; a statistically significant finding means strong evidence for one of the hypotheses.",
            "Formulation draws on hypothesis types. A simple hypothesis links one independent and one dependent variable (e.g., smoking leads to cancer). A complex hypothesis links several causes and effects. An empirical/working hypothesis starts as an assumption and becomes testable. Logical hypotheses are rationally validated (J.S. Mill’s principles). Statistical hypotheses can be verified statistically whether or not they seem logical.",
        ],
        "Thus, “hypothesis” is “ a tentative statement, which is subject to verification and states the solution of a problem”.",
        ["4.1.2", "4.1.9"],
        compare="A theory is a tested, well-substantiated explanation; a hypothesis is tentative and still requires empirical verification.",
        example="Mutual fund launch: H1 (≥20% invest) → launch; H2 (<20% invest) → do not launch.",
    ),
    "4.1.2": C(
        "4.1.2",
        "Developing Hypothesis: Null and Alternate",
        [89, 90],
        "The null hypothesis (H0) states no relationship between variables; the alternative (H1) is the competing claim chosen after modifying the prior statement.",
        [
            "Null (H0 / h0): contrary to the positive empirical claim — no relationship between dependent and independent variables.",
            "Alternative (H1 / h1): the feasible, effective competing hypothesis after refinement.",
            "Test statistic: estimator from sample data used for the decision.",
            "Rejection region (RR): values of the test statistic that reject H0 in favour of H1.",
            "Significance level (often 5% or 1%): chance of rejecting H0 when it is actually true.",
        ],
        [
            "If the calculated test statistic falls in the rejection region, reject H0 and accept H1; if it does not, accept H0 (the non-rejection / acceptance region).",
            "The significance level is the threshold probability for choosing between null and alternative. At 5%, the material notes a long-run risk of incorrect judgement about 5% of the time when the hypothesis is accepted at that level.",
        ],
        "It is contrary to the positive statement of the empirical hypothesis, which has no relationship between dependent and independent variables.",
        ["4.1.1", "4.1.3", "4.1.8", "4.1.9"],
        compare="H0 = no relationship / status quo claim; H1 = the refined competing claim you hope the data support.",
    ),
    "4.1.3": C(
        "4.1.3",
        "Type I and Type II Error",
        [90, 91],
        "Type I error wrongly rejects a true H0 (wrongly accepts H1); Type II wrongly accepts a false H0 (wrongly rejects H1).",
        [
            "Type I: H0 true but rejected; H1 wrongly accepted.",
            "Type II: H0 false but accepted; H1 wrongly rejected.",
            "Correct decisions: accept H0 when H0 true; accept H1 when H1 true — no error.",
            "Children’s-channel ad example: wrong H0 rejection → skip needed ads; wrong H1 rejection → pay for unnecessary ads.",
            "“State of nature” = the authentic situation; mistakes can arise when linking states to actions or when study findings misrepresent nature.",
        ],
        [
            "Hypothesis pairs are designed so they cannot both be true and false at once; action 1 follows if the first hypothesis is true, action 2 if the second is true.",
            "Decision tables map true state vs conclusion: Type I when H0 is true but you conclude H1; Type II when H1 is true but you conclude H0.",
        ],
        "H0 wrongly rejected and H1 wrongly accepted",
        ["4.1.2", "4.1.7", "4.1.8"],
        example="H0: adults ≥20% of children’s TV audience (advertise); H1: adults <20% (don’t advertise).",
    ),
    "4.1.4": C(
        "4.1.4",
        "One-Tailed and Two-Tailed Test",
        [91, 92],
        "A one-tailed test allows the alternative to go only higher or only lower than H0; a two-tailed test allows departure in either direction (≠).",
        [
            "One-tailed: H0: μ = μ0; H1: μ < μ0 or μ > μ0 (not both at once).",
            "Two-tailed: H0: μ = μ0; H1: μ ≠ μ0 — care about both higher and lower.",
            "Drug example: only “more effective” matters → one-tailed setup.",
            "Supplier strength vs target: higher or lower both matter → two-tailed.",
            "Compare p-value to α; sign of the test statistic shows which tail.",
        ],
        [
            "In the new-medication illustration, failing to reject H0 or rejecting in the wrong direction both stop further production/study, so a one-tailed test focuses on greater effectiveness.",
            "For a two-sided 1-sample t-test of mean strength against a target, a negative t-value in the left critical region means the mean is smaller than the target.",
        ],
        "In a one-tailed test, the alternative hypothesis allows for the parameter being tested to be either bigger or less than the parameter under the null hypothesis, but not both simultaneously.",
        ["4.1.8", "4.1.11", "4.2.3"],
        compare="One-tailed = directional alternative; two-tailed = non-directional (≠) alternative.",
    ),
    "4.1.5": C(
        "4.1.5",
        "Degree of Freedom",
        [92, 93],
        "Degrees of freedom are how many values in a calculation are free to vary; often df = N − 1 (or observations minus parameters).",
        [
            "Needed for validity of chi-square, t, and F tests.",
            "General idea: df = (number of observations) − (number of parameters).",
            "Common sample formula: Degree of Freedom = N − 1.",
            "Example: values 15, 30, 25, 10 → mean 20 → df = 4 − 1 = 3 can vary while mean stays 20.",
        ],
        [
            "Because df identifies how many values in the final calculation may vary, they contribute to outcome validity. Calculations often depend on sample size and parameters being estimated.",
            "In the vaccine heart-rate illustration, df enters the significance calculation when comparing vaccinated vs not vaccinated groups.",
        ],
        "Degrees of freedom equal the number of values in a data set minus 1 in a statistical formula like : Degree of Freedom = N-1",
        ["4.2.1", "4.2.5", "4.2.8"],
    ),
    "4.1.6": C(
        "4.1.6",
        "Confidence Intervals",
        [93, 94],
        "A confidence interval is the estimate ± its variation — the range expected to contain the estimate if the study is redone at a stated confidence level.",
        [
            "Confidence in statistics is another way to describe probability.",
            "95% CI: expect the estimate between the bounds in 95 of 100 similar retests.",
            "Relation: Confidence level = 1 − α (e.g., α = 0.05 → 95%).",
            "Used for proportions, means, differences of means/proportions, and variation among groups.",
            "Same point estimate can have a wider CI when data are more volatile.",
        ],
        [
            "Point estimates alone give no sense of surrounding range; CIs convey the variance around the estimate.",
            "India vs America TV-hours survey: both groups average 35 hours/week, but greater disparity among Indian respondents yields a broader CI than the American estimate.",
        ],
        "A confidence interval is the mean of our estimate plus and minus the variation in that estimate.",
        ["4.1.7", "4.2.1"],
        example="Both groups mean 35 TV hours/week; more volatile Indian responses → wider CI.",
    ),
    "4.1.7": C(
        "4.1.7",
        "Level of Significance: The Confidence Coefficient",
        [94, 95],
        "The confidence coefficient (confidence level) shades the central portion of the sampling distribution (e.g., 95%) that defines the confidence interval around the sample mean.",
        [
            "Graphically: centre the interval on the sample mean and shade the central 95% of the distribution.",
            "That shaded range of sample means is the 95% confidence interval.",
            "Fuel-price illustration: population mean said to fall between 267 and 394 at 95% confidence.",
            "Ties back to α via confidence level = 1 − α from the prior section.",
        ],
        [
            "Section 4.1.7 focuses on interpreting the confidence coefficient visually: the sampling distribution covered by 95% of sample means in the shaded range is the 95% CI for the data.",
            "For the fuel-price example, the material states the population mean for fuel prices falls between 267 and 394 with a 95% confidence interval.",
        ],
        "The sampling distribution is covered by 95% of the sample means in the shaded range [267 394]. For our sample data, this range represents the 95% confidence interval.",
        ["4.1.6", "4.1.2", "4.1.3"],
    ),
    "4.1.8": C(
        "4.1.8",
        "Rejection and Non-rejection Regions",
        [95, 96],
        "The rejection (critical) region is all test-statistic values that reject H0; a critical value separates it from the non-rejection region.",
        [
            "α = probability the test statistic falls in the critical region when H0 is true.",
            "Left-tailed: H1 uses < ; right-tailed: H1 uses > ; two-tailed: H1 uses ≠ with α/2 in each tail.",
            "Decision: z/t in rejection region → reject H0; otherwise fail to reject H0.",
            "Failing to reject ≠ proving H0 true — only insufficient evidence to reject.",
            "Type I probability = α; Type II probability typically denoted β.",
        ],
        [
            "Calculate the standardised test statistic (z or t). If it falls in the rejection region, reject H0; if not, fail to reject H0.",
            "The same section also introduces Bayesian probability as degree of certainty (0–1), prior vs posterior probabilities, and Bayes’ Box updates — complementary framing of belief revision after data.",
        ],
        "The critical region, also known as the rejection region, encompasses all values of the test statistic that lead to the rejection of the null hypothesis.",
        ["4.1.2", "4.1.3", "4.1.4", "4.1.9"],
        compare="Reject H0 only if the statistic is in the critical region; otherwise fail to reject (do not claim H0 proven).",
    ),
    "4.1.9": C(
        "4.1.9",
        "Hypothesis Testing Procedure",
        [100, 101],
        "Hypothesis testing is a stepwise process: formulate H0/Ha, sample, choose a method, compute the statistic and p-value, compare to α, then conclude.",
        [
            "Formulate null (no relationship) and alternative (predicted relationship).",
            "Collect representative sample data.",
            "Choose an appropriate testing method for the data and question.",
            "Calculate a test statistic (e.g., z-score, t-statistic).",
            "p-value: probability of results as extreme as observed if H0 is true.",
            "Low p (< α) → reject H0; high p (≥ α) → fail to reject H0.",
        ],
        [
            "Example pair: H0 — no average height difference between men and women; Ha — men are taller on average.",
            "A low p-value suggests the observed difference is unlikely by chance alone (supports Ha); a high p-value suggests random variation (supports H0). Draw the conclusion in the research-question context.",
        ],
        "The p-value quantifies the probability of observing results as extreme as those obtained, assuming the null hypothesis is true.",
        ["4.1.2", "4.1.8", "4.1.11"],
    ),
    "4.1.10": C(
        "4.1.10",
        "Types of Tests",
        [101, 102],
        "Statistical tests for hypothesis-based inference fall into parametric (distributional assumptions) and non-parametric (fewer distribution assumptions) families.",
        [
            "Parametric: assume normality / homogeneity of variance, etc. — e.g., t-tests, ANOVA, linear regression.",
            "Non-parametric: no distribution assumption required — e.g., Wilcoxon signed-rank, Mann-Whitney U, Kruskal-Wallis.",
            "Also categorised by research focus: quantitative (numerical) vs qualitative/categorical analysis.",
            "Qualitative/categorical tests uncover associations among categorical variables.",
        ],
        [
            "Parametric tests rely on assumptions about the underlying data distribution to make accurate inferences; non-parametric tests are more robust when those assumptions are violated.",
            "Choice also depends on whether the work is quantitative or qualitative; categorical statistical tests matter for qualitative-style categorical data.",
        ],
        "These tests are broadly classified into two categories: parametric and non-parametric.",
        ["4.1.11", "4.2.1"],
        compare="Parametric needs distributional assumptions; non-parametric does not require them.",
    ),
    "4.1.11": C(
        "4.1.11",
        "How to Select a Test",
        [102],
        "Selecting a test follows seven steps: question → null → α → one- vs two-tailed → number of variables → data type → study design (paired vs unpaired).",
        [
            "Define the research question that guides collection and analysis.",
            "Formulate a null of no statistical significance.",
            "Set the significance level in the protocol.",
            "Choose one-tailed (clear direction) or two-tailed (no anticipated direction).",
            "Match tests to single-variable vs multivariable problems.",
            "Assess continuous / categorical / binary data and normality vs skew for continuous data.",
            "Account for paired (dependent) vs unpaired (independent) designs.",
        ],
        [
            "One-tailed tests suit clear directional evidence; two-tailed when no specific direction is anticipated.",
            "Paired designs compare dependent samples; unpaired designs compare independent samples — this distinction drives many parametric choices later in 4.2.",
        ],
        "One-tailed tests are suitable when evidence points clearly in one direction, while two-tailed tests are appropriate when no specific direction is anticipated.",
        ["4.1.4", "4.1.9", "4.1.10", "4.2.1"],
    ),
    "4.2.1": C(
        "4.2.1",
        "Important Parametric Tests",
        [102, 103, 104],
        "Key parametric tests assuming normality include the t-test (small n, unknown σ), Z-test (large n or known σ), and F-test (comparing variances / ANOVA).",
        [
            "Parametric tests assume fixed population parameters (mean, SD) and typically normal populations (CLT may justify approximate normality).",
            "t-test (Student/Gossett): means of groups; n < 30; unknown variance; df = n − 1; one-sample, independent two-sample, paired.",
            "Z-test: sample vs population mean when n > 30 or variance known; also large-sample two-mean comparisons.",
            "F-test: compare variances of two samples; also central to ANOVA for ≥3 group means.",
        ],
        [
            "Uses listed for parametric work include CIs for a mean (known or unknown σ), for variance, and for the difference of two means with unknown SD (t).",
            "Examples in the text: paired t for BP before/after medication; Z for comparing men’s and women’s salaries; F for bolt-diameter variability across machines.",
        ],
        "Parametric tests are statistical tests that assume the underlying data follows a normal distribution.",
        ["4.1.10", "4.2.2", "4.2.3", "4.2.6"],
        compare="t for small samples / unknown σ; Z for large samples / known σ; F for variances (and ANOVA).",
    ),
    "4.2.2": C(
        "4.2.2",
        "Single Population Mean Using Z-statistic",
        [104, 105],
        "A Z-test checks whether a sample mean differs from a known population mean when σ is known — especially useful for large samples (n > 30).",
        [
            "Also used when the test-statistic distribution can be approximated as normal.",
            "Applications: sample mean vs population mean; two sample means with known variances and large n (≥ 30).",
            "One-sample Z: sample mean vs population mean.",
            "Two-sample Z: compare means of two different samples (uses group means, population SDs, and n).",
        ],
        [
            "The section frames Z as the large-sample / known-σ route for mean hypotheses, contrasting later with the t-route when σ is unknown and n is small.",
            "Two-sample notation references x̄1, x̄2, σ1, σ2, and n as inputs to the standardised comparison.",
        ],
        "A Z-test is a statistical method used to determine whether the mean of a sample is significantly different from a known population mean when the population standard deviation is known.",
        ["4.2.1", "4.2.3"],
        compare="Prefer Z when σ known and/or n large; prefer t when σ unknown and n small.",
    ),
    "4.2.3": C(
        "4.2.3",
        "Single Population Mean Using T-statistic",
        [105, 106],
        "The t-test uses Student’s t-distribution for mean differences when n is small (< 30) and the population standard deviation is unknown.",
        [
            "Assumptions: normal population; random independent samples; small n; unknown σ.",
            "One-sample t: sample mean vs known population mean.",
            "Independent two-sample t: means of two independent samples.",
            "Paired t: related samples (before/after).",
            "Statistic uses sample mean, sample SD (s), n, and μ.",
        ],
        [
            "Parametric t-testing is the small-sample counterpart to Z when σ must be estimated from the sample.",
            "Two-sample form uses each group’s sample mean and sample SD rather than known population σ.",
        ],
        "It is primarily used to determine if there is a significant difference between the means of two groups, especially when the sample size is small (i.e., less than 30) and the population standard deviation is unknown.",
        ["4.2.1", "4.2.2", "4.1.5"],
    ),
    "4.2.4": C(
        "4.2.4",
        "Hypothesis Testing for Population Proportions",
        [106, 107],
        "Proportion tests ask whether a sample proportion differs from a hypothesised population proportion — suited to categorical data.",
        [
            "H0: population proportion equals a specified value; Ha: differs (one- or two-tailed).",
            "Common α choices: 0.05, 0.01, 0.10.",
            "Large samples: Z-score test statistic from the proportion formula.",
            "Two-tailed α = 0.05 → critical values ±1.96 on the standard normal.",
            "Reject H0 if Z is in the rejection region; otherwise fail to reject; then conclude about Ha.",
        ],
        [
            "Steps mirror general hypothesis testing: state hypotheses, set α, compute Z, apply the critical-value decision rule, and conclude whether evidence supports the alternative.",
            "Focus remains conceptual: categorical proportion claims with large-sample normal (Z) critical regions.",
        ],
        "Hypothesis testing for population proportions involves determining whether a sample proportion significantly differs from a known or hypothesised population proportion.",
        ["4.1.9", "4.2.2"],
    ),
    "4.2.5": C(
        "4.2.5",
        "Variance vs Hypothesised Population Variance",
        [107, 108],
        "A chi-square test compares a sample variance to a hypothesised population variance for normally distributed populations.",
        [
            "Can be two-tailed (σ² = σ0² vs ≠), right-tailed (σ² > σ0²), or left-tailed (σ² < σ0²).",
            "Chi-square distribution has df = n − 1; starts at zero and is asymmetric.",
            "As df grow, the shape approaches normality.",
            "Two-tailed α = 0.10 with 10 df: critical values ≈ 3.94 and 18.307 (α/2 = 0.05 each tail).",
            "Reject H0 if the statistic is below the lower or above the upper critical value.",
        ],
        [
            "Because variance cannot be negative, the chi-square curve is asymmetrical from zero upward.",
            "Table-reading illustration: split α for two tails, look up right-tail 0.05 and 0.95 columns for the given df, then apply the dual critical-value rule.",
        ],
        "The chi-square test is a statistical method used to determine whether there is a significant difference between the observed variance of a sample and a hypothesised population variance.",
        ["4.1.5", "4.2.6"],
    ),
    "4.2.6": C(
        "4.2.6",
        "Equality of Variances of Two Normal Populations",
        [108, 109, 110],
        "The F-test (Snedecor & Cochran) compares whether two normal populations have equal variances, using the ratio of the larger sample variance to the smaller.",
        [
            "H0 usually: variances equal; Ha: not equal (one- or two-tailed as needed).",
            "Draw samples, compute variances and sizes; F = larger s² / smaller s².",
            "df for numerator and denominator = each sample size − 1.",
            "Reject H0 if calculated F exceeds the critical value.",
            "Conditions: random samples, independent observations, approximately normal populations.",
        ],
        [
            "Related material also covers testing a population correlation coefficient ρ via sample r (H0: ρ = 0; Ha: ρ ≠ 0) with a t-statistic on n − 2 df — significant r means evidence of a linear relationship.",
            "Conceptual takeaway: F for variance equality between two normals; correlation significance is a separate t-based check that ρ ≠ 0.",
        ],
        "The F-test, developed by Snedecor and Cochran (1983), is used to determine if the variances of two populations are equal.",
        ["4.2.1", "4.2.5", "4.2.7"],
        compare="F-test here compares two variances; ANOVA uses F to compare several means via mean squares.",
    ),
    "4.2.7": C(
        "4.2.7",
        "ANOVA for Fixed Effect Model",
        [110, 111, 112],
        "Fixed-effect ANOVA models a response as treatment mean (or overall mean + fixed treatment effect) plus error, to compare mean responses across fixed treatments.",
        [
            "Response = f(factor) + error; natural variation always remains even under similar settings.",
            "Means model: yij = μi + εij — compare average response across treatments (e.g., fuel types’ mpg).",
            "Effects model: yij = μ + τi + εij — overall mean plus ith treatment effect.",
            "εij assumed identical, independent, normally distributed.",
            "Error sources: experimental (treatment / stochastic EU / selection) and observational (measurement / sampling).",
        ],
        [
            "The fuel-economy research question asks whether average mpg differs by fuel type; the means model generalises sample treatment means to the population and is linear in μ.",
            "Isolating additive effects from a base response yields the effects form with τi. Earlier “variance analysis” business examples (material/labour/overhead) illustrate deviation-from-plan thinking, but the fixed-effect ANOVA core is the means/effects models above.",
        ],
        "The model is referred to as the means model since it is based on the mean treatment effect.",
        ["4.2.8", "4.2.9", "4.2.10"],
        example="Fuel types as treatments; response = mpg; ask if mean mpg differs across fuels.",
    ),
    "4.2.8": C(
        "4.2.8",
        "Total, Treatment & Error Sum of Squares",
        [112, 113],
        "ANOVA partitions variability into SSE (error), SSTR (treatment), and SST (total), then forms MSE/MSTR for the F test statistic.",
        [
            "After SSE, compute SSTR and SST; then MSE and MSTR for the test statistic.",
            "SSTR measures how much treatment means differ (e.g., battery-type lifetimes).",
            "Low SSTR → treatment averages are similar.",
            "SSTR steps: for each treatment, (column mean − grand mean)² × n_column.",
            "SST = SSTR + SSE.",
        ],
        [
            "Battery example: three types × four batteries; grand mean 2.1; column means 2.3, 1.85, 2.15 — SSTR from squared deviations times 4 per column; SST is SSTR + SSE.",
            "Conceptual role: treatment SS captures between-group structure; error SS captures within-group noise; their mean squares feed the ANOVA F.",
        ],
        "The total sum of squares (SST) equals the sum of the SSTR and the SSE.",
        ["4.2.7", "4.2.10"],
    ),
    "4.2.9": C(
        "4.2.9",
        "ANOVA for Random Effect Model",
        [113, 114, 115, 116],
        "Random-effect / two-factor (randomised block) ANOVA adds a blocking factor so units are grouped; treatments of interest are compared within more homogeneous blocks.",
        [
            "Two-way factorial expands one-factor work with a second factor often used as blocks.",
            "Compiler example: better to run the same programmes on each compiler (blocks) than assign different programmes to each.",
            "Assumptions (one obs per cell): approximate normality per cell; common variance σ²; no interaction (effect of one factor consistent across levels of the other).",
            "Interaction example: sugar × stirring on tea sweetness — stirring matters only with sugar.",
            "Two-factor table: SSR (rows), SSC (columns), SSE with df (r−1)(c−1), F = MSR/MSE and MSC/MSE.",
        ],
        [
            "Design (2) — four copies of five programmes, one per compiler — avoids confounding programme difficulty with compiler speed and yields a randomised block layout.",
            "When interaction cannot be estimated (single observation per cell), the material assumes no interaction; sugar/stirring shows what interaction means conceptually.",
        ],
        "Therefore, it is sometimes referred to as a blocking factor as it categorises topics or units into similar groupings known as blocks. The design is referred to as a randomised block design.",
        ["4.2.7", "4.2.10"],
        compare="Fixed effects: specific treatment levels of interest; random/block structures control nuisance variation across units.",
    ),
    "4.2.10": C(
        "4.2.10",
        "Single Factor Experiment",
        [116, 117, 118],
        "A single-factor experiment varies levels of one independent factor to study its effect on a response; CRD randomly assigns treatments to homogeneous units.",
        [
            "Popular designs: CRD, randomised block, Latin square, balanced incomplete block.",
            "CRD: no grouping; allocate v treatments randomly; flexible unequal replications; all unit variability → error.",
            "CRD suited to homogeneous material, labs, small numbers of treatments; often inefficient outdoors.",
            "Model: yij = μ + τi + εij; H0: all τi = 0; SSTreatments (a−1 df) vs SSE (N−a df).",
            "Lambs/diets illustration: fail to reject equal diet effects when F is small / p large.",
        ],
        [
            "CRD layout: divide into n units, fix replications, randomly assign treatments without local control beyond choosing homogeneous units.",
            "SSTreatments measures differences among treatment means; SSE is within-treatment random error with E(MSE) = σ². The diet example ends with F0 = 0.77 and fail to reject H0.",
        ],
        "Frequently we wish to investigate the effect of a factor (independent variable) on a response (dependent variable). Then we carried out an experiment where the levels of the factor are varied. Such an experiment is known as a single-factor experiment.",
        ["4.2.7", "4.2.8", "4.2.9"],
        example="Four treatments on 20 units with unequal replications (3, 5, 6, 6) under CRD.",
    ),
    "4.2.11": C(
        "4.2.11",
        "Model Adequacy Checking",
        [126, 127, 128],
        "Model adequacy checking verifies regression assumptions (linearity, zero-mean errors, constant variance, independence, normality) mainly via residual diagnostics.",
        [
            "Assumptions: roughly linear study–explanatory link; E(error)=0; constant variance; uncorrelated errors; normal errors.",
            "Minor violations may be tolerable; major ones can make the model unstable across samples.",
            "One predictor: scatter plot of y vs X for linearity.",
            "Multiple predictors: scatter-plot matrix (off-diagonal plots; optional correlations).",
            "Residual ei = yi − ŷi; residuals should reveal assumption failures; OLS residuals have mean zero.",
        ],
        [
            "Assumptions are about the population while we observe a sample, so diagnostics on residuals (graphical) are the practical bridge.",
            "Residuals quantify how far the fit misses the data and act as realised errors; examining them exposes model shortcomings.",
        ],
        "The residual is outlined because of the distinction between the discovered and fitted worth of study variable.",
        ["4.2.7", "4.2.10"],
    ),
}

QUESTIONS = [
    # 4.1.1
    Q("4.1.1", 1, "In the study material, what is a hypothesis?",
      ["A proven fact that needs no testing",
       "A tentative statement subject to verification that states a solution to a problem",
       "A complete, well-substantiated explanation of proven factors",
       "Any assumption that cannot be checked empirically"],
      1, "The extract defines hypothesis via hypo + thesis as a tentative, verifiable statement of a problem’s solution.", difficulty="easy"),
    Q("4.1.1", 2, "How does the material distinguish a hypothesis from a theory?",
      ["They are identical once written down",
       "A hypothesis is tested and complete; a theory is still tentative",
       "A theory is a tested, well-substantiated explanation; a hypothesis is tentative and testable",
       "A theory only applies to mutual-fund research"],
      2, "Theory = tested, well-substantiated explanation; hypothesis = tentative relationship still needing verification.", difficulty="easy"),
    # 4.1.2 — high weight (3)
    Q("4.1.2", 1, "What does the null hypothesis (H0) assert in the extract?",
      ["A strong positive relationship between variables",
       "No relationship between dependent and independent variables",
       "That the alternative must always be true",
       "That sampling is unnecessary"],
      1, "Null is contrary to the positive empirical claim and states no relationship between the variables.", difficulty="easy"),
    Q("4.1.2", 2, "When does the material say you reject H0 in favour of H1?",
      ["Whenever the sample size exceeds 30",
       "When the test statistic falls inside the rejection region (RR)",
       "When the significance level is set to 50%",
       "Only if H0 and H1 are both true"],
      1, "If the calculated test statistic falls in RR, reject H0 and accept H1.", difficulty="medium"),
    Q("4.1.2", 3, "What is the significance level (e.g., 5%) described as?",
      ["The probability of a Type II error only",
       "The chance of rejecting the null hypothesis when it is actually true",
       "The minimum required sample size",
       "The population mean under H1"],
      1, "At 5%, it is the chance of rejecting H0 when H0 is actually true.", difficulty="medium"),
    # 4.1.3 — high weight (3)
    Q("4.1.3", 1, "Which description matches a Type I error?",
      ["H0 wrongly accepted; H1 wrongly rejected",
       "H0 wrongly rejected; H1 wrongly accepted",
       "Both hypotheses accepted simultaneously",
       "Failing to collect any sample data"],
      1, "Type I = H0 wrongly rejected and H1 wrongly accepted.", difficulty="easy"),
    Q("4.1.3", 2, "Which description matches a Type II error?",
      ["H0 wrongly rejected; H1 wrongly accepted",
       "Correctly accepting H1 when H1 is true",
       "H0 wrongly accepted; H1 wrongly rejected",
       "Setting α = 0"],
      2, "Type II = H0 wrongly accepted and H1 wrongly rejected.", difficulty="easy"),
    Q("4.1.3", 3, "In the children’s-channel advertising illustration, unnecessary advertising costs arise from which mistake?",
      ["Correctly accepting H0 when adults are ≥20% of viewers",
       "Type II error — H1 wrongly rejected / H0 wrongly accepted",
       "Type I error — skipping ads when H0 was true",
       "Using a two-tailed test instead of one-tailed"],
      1, "Table: Type II → unnecessary costs incurred due to advertisements.", difficulty="medium"),
    # 4.1.4
    Q("4.1.4", 1, "For a one-tailed test, how is the alternative hypothesis framed?",
      ["H1: μ ≠ μ0 only",
       "H1: μ < μ0 or μ > μ0, but not both directions at once",
       "H1 must include both greater and less simultaneously",
       "H1 is identical to H0"],
      1, "One-tailed H1 is directional: either < or >, not both.", difficulty="easy"),
    Q("4.1.4", 2, "When does the material prefer a two-tailed test?",
      ["Only when sample size is below 5",
       "When it matters whether the mean is higher or lower than the target",
       "Only for Bayesian analyses",
       "Whenever σ is known"],
      1, "Supplier strength vs target uses two-tailed because higher or lower both matter.", difficulty="medium"),
    # 4.1.5
    Q("4.1.5", 1, "What formula for degrees of freedom does the extract give for a simple data set?",
      ["df = N + 1",
       "df = N − 1",
       "df = N²",
       "df = α × N"],
      1, "Degree of Freedom = N − 1.", difficulty="easy"),
    Q("4.1.5", 2, "Why are degrees of freedom important according to the text?",
      ["They replace the need for any sample",
       "They help ensure statistical validity of chi-square, t, and F tests",
       "They set the marketing budget",
       "They define Type II error only"],
      1, "df are crucial for validity of chi-square, t-tests, and F-tests.", difficulty="easy"),
    # 4.1.6
    Q("4.1.6", 1, "What is a confidence interval in the extract’s wording?",
      ["Only the single point estimate with no range",
       "The estimate plus and minus the variation in that estimate — a range at a stated confidence",
       "The probability of a Type I error alone",
       "A synonym for the null hypothesis"],
      1, "CI = mean of estimate ± variation; range expected under a confidence level.", difficulty="easy"),
    Q("4.1.6", 2, "If α = 0.05, what confidence level does the material give?",
      ["5%", "50%", "95%", "0.05%"],
      2, "Confidence level = 1 − α = 0.95 or 95%.", difficulty="easy"),
    # 4.1.7
    Q("4.1.7", 1, "In the fuel-price illustration, what does the shaded 95% range of sample means represent?",
      ["The rejection region for a Type II error only",
       "The 95% confidence interval for the sample data",
       "The population size N",
       "The alternative hypothesis wording"],
      1, "Shaded range [267, 394] is described as the 95% confidence interval.", difficulty="medium"),
    Q("4.1.7", 2, "Where is the sample mean placed in the confidence-interval graph described?",
      ["Always at zero",
       "At the centre of the confidence interval graph",
       "Outside both tails by definition",
       "Only in the left rejection region"],
      1, "The sample mean is the centre of the confidence interval graph.", difficulty="easy"),
    # 4.1.8
    Q("4.1.8", 1, "What is the critical (rejection) region?",
      ["All values that force acceptance of H0 as proven true",
       "All values of the test statistic that lead to rejection of H0",
       "The set of all possible sample sizes",
       "Only the Bayesian prior column"],
      1, "Rejection region = values of the test statistic that reject H0.", difficulty="easy"),
    Q("4.1.8", 2, "If the standardised test statistic does not fall in the rejection region, what should you do?",
      ["Prove H0 is absolutely true",
       "Fail to reject H0 (insufficient evidence to reject)",
       "Automatically accept H1",
       "Switch to a non-parametric test only"],
      1, "Fail to reject H0; that does not imply accepting it as true.", difficulty="medium"),
    # 4.1.9
    Q("4.1.9", 1, "What does the p-value quantify in the procedure section?",
      ["The population mean under H1",
       "The probability of results as extreme as observed, assuming H0 is true",
       "The required marketing spend",
       "The number of treatments in ANOVA"],
      1, "p-value = probability of observed (or more extreme) results under H0.", difficulty="easy"),
    Q("4.1.9", 2, "If p-value < α, what decision follows?",
      ["Fail to reject H0",
       "Reject the null hypothesis",
       "Increase α until p exceeds it",
       "Declare the sample invalid"],
      1, "Low p (< α): reject H0; high p (≥ α): fail to reject.", difficulty="easy"),
    # 4.1.10
    Q("4.1.10", 1, "Which pair correctly matches the extract’s classification?",
      ["Parametric tests never assume normality; non-parametric always do",
       "Parametric tests rely on distributional assumptions (e.g., t, ANOVA); non-parametric do not require them (e.g., Mann-Whitney)",
       "Both types require known population σ",
       "Non-parametric tests include only linear regression"],
      1, "Parametric vs non-parametric split is exactly that assumption contrast.", difficulty="medium"),
    Q("4.1.10", 2, "Which are listed as parametric examples?",
      ["Wilcoxon, Mann-Whitney, Kruskal-Wallis",
       "t-tests, ANOVA, and linear regression",
       "Only chi-square goodness-of-fit",
       "Only Bayesian Boxes"],
      1, "Parametric examples: t-tests, ANOVA, linear regression.", difficulty="easy"),
    # 4.1.11
    Q("4.1.11", 1, "Which is one of the seven essential steps for selecting a test?",
      ["Always ignore data type",
       "Assess whether data are continuous, categorical, or binary (and normality if continuous)",
       "Skip formulating a null hypothesis",
       "Use only two-tailed tests forever"],
      1, "Step: assess data type / normality vs skew for continuous data.", difficulty="easy"),
    Q("4.1.11", 2, "When are one-tailed tests described as suitable?",
      ["When no direction is anticipated",
       "When evidence points clearly in one direction",
       "Only for qualitative interviews",
       "Only when N < 5"],
      1, "One-tailed when evidence points clearly in one direction; two-tailed otherwise.", difficulty="easy"),
    # 4.2.1
    Q("4.2.1", 1, "When does the material prefer a t-test over a Z-test for means?",
      ["Large n (>30) with known population variance",
       "Small samples (<30) with unknown population variance",
       "Only when comparing three or more variances",
       "Never — t and Z are identical"],
      1, "t-test for small n and unknown variance; Z for large n or known variance.", difficulty="medium"),
    Q("4.2.1", 2, "What is the F-test used for in the “important parametric tests” section?",
      ["Only paired before/after means",
       "Comparing variances of two samples (and in ANOVA for ≥3 group means)",
       "Estimating ISBN numbers",
       "Replacing the null hypothesis"],
      1, "F compares variances; also integral to ANOVA for three or more means.", difficulty="easy"),
    # 4.2.2
    Q("4.2.2", 1, "A Z-test for a single mean is especially useful when:",
      ["n is small and σ is unknown",
       "Population standard deviation is known and/or n > 30",
       "Data are ranks only",
       "You must avoid any normal approximation"],
      1, "Z when σ known; particularly useful for large samples n > 30.", difficulty="easy"),
    Q("4.2.2", 2, "Which application is listed for the Z-test?",
      ["Only testing equality of three variances",
       "Comparing a sample mean to a population mean",
       "Computing degrees of freedom as N+1",
       "Replacing residual plots"],
      1, "Application: comparing sample mean to population mean (and large-sample two means).", difficulty="easy"),
    # 4.2.3
    Q("4.2.3", 1, "Which is an assumption of the t-test in the extract?",
      ["Population standard deviation is known",
       "Sample size is typically large (>1000)",
       "Population is normally distributed; samples random and independent; σ unknown; n small",
       "Data must be purely categorical proportions"],
      2, "Assumptions: normal population, random independent samples, small n, unknown σ.", difficulty="medium"),
    Q("4.2.3", 2, "A paired t-test is described as comparing:",
      ["Variances of two machines only",
       "Means of two related samples (e.g., before and after)",
       "Three or more independent group means without error",
       "Only Bayesian posteriors"],
      1, "Paired t: related samples, often before/after.", difficulty="easy"),
    # 4.2.4
    Q("4.2.4", 1, "Hypothesis tests for population proportions are particularly useful for:",
      ["Only continuous normally distributed heights",
       "Categorical data comparing a sample proportion to a hypothesised value",
       "Latin square designs exclusively",
       "Estimating residual means only"],
      1, "Proportion tests suit categorical data vs a hypothesised population proportion.", difficulty="easy"),
    Q("4.2.4", 2, "For a two-tailed proportion test with α = 0.05, which critical values are cited?",
      ["±0.05", "±1.96", "±3.94 and 18.307", "0 and 1 only"],
      1, "Standard normal critical values ±1.96 for two-tailed α = 0.05.", difficulty="medium"),
    # 4.2.5
    Q("4.2.5", 1, "Which distribution is used to compare a sample variance to a hypothesised population variance?",
      ["Standard normal only",
       "Chi-square with n − 1 degrees of freedom",
       "Binomial with p = 0.5",
       "Uniform(0,1)"],
      1, "Chi-square variance test uses df = n − 1.", difficulty="easy"),
    Q("4.2.5", 2, "Why is the chi-square variance distribution described as asymmetrical from zero?",
      ["Because means can be negative",
       "Because variance cannot be negative",
       "Because α is always 0.5",
       "Because F ratios are undefined"],
      1, "Variance cannot be negative → chi-square starts at zero and is asymmetrical.", difficulty="medium"),
    # 4.2.6
    Q("4.2.6", 1, "In the F test for equality of two variances, the test statistic is:",
      ["The difference of the two sample means",
       "The ratio of the larger sample variance to the smaller sample variance",
       "Always equal to α",
       "The sum of all residuals"],
      1, "F = larger sample variance / smaller sample variance.", difficulty="easy"),
    Q("4.2.6", 2, "Which condition is required for a valid F test of two variances?",
      ["Populations need not be near normal",
       "Observations may be dependent within samples",
       "Samples drawn randomly; observations independent; populations approximately normal",
       "Sample sizes must both exceed 1000"],
      2, "Random samples, independence, approximate normality.", difficulty="medium"),
    # 4.2.7 — high weight ANOVA intro (3)
    Q("4.2.7", 1, "In the means model for fixed-effect ANOVA, what does yij = μi + εij express?",
      ["Only measurement error with no treatment means",
       "Response as the ith treatment mean plus error",
       "That all treatment means are forced equal to zero",
       "A non-parametric rank sum"],
      1, "Means model: yij = μi + εij based on mean treatment effect.", difficulty="medium"),
    Q("4.2.7", 2, "How does the effects model write the response?",
      ["yij = μ + τi + εij (overall mean + treatment effect + error)",
       "yij = εij only",
       "yij = μi²",
       "yij = α always"],
      0, "Effects model: yij = μ + τi + εij.", difficulty="medium"),
    Q("4.2.7", 3, "In the fuel-economy illustration, what research question does the means model address?",
      ["Whether compilers differ on blocked programmes",
       "Whether average mpg differs across fuel types (treatments)",
       "Whether a single proportion equals 0.5",
       "Whether residuals have infinite variance"],
      1, "Ask if there is disparity among fuel types in average mpg.", difficulty="easy"),
    # 4.2.8
    Q("4.2.8", 1, "What does SST equal in the extract?",
      ["Only SSE",
       "SSTR + SSE",
       "MSE × MSTR",
       "α × β"],
      1, "Total sum of squares SST = SSTR + SSE.", difficulty="easy"),
    Q("4.2.8", 2, "What does a low SSTR indicate in the battery-lifetime discussion?",
      ["Treatment averages differ dramatically",
       "Average lifespans of the battery types are comparable",
       "SSE must be zero",
       "The design must be Latin square"],
      1, "Low SSTR → average lifespans of various battery types are comparable.", difficulty="medium"),
    # 4.2.9
    Q("4.2.9", 1, "Why is design (2) preferred in the compiler evaluation example?",
      ["It confounds programmes with compilers on purpose",
       "Each programme runs on every compiler, so programme differences do not bias compiler comparisons (randomised blocks)",
       "It uses twenty unrelated programmes with no replication",
       "It forbids any blocking factor"],
      1, "Same programmes on each compiler → blocking; compiler is factor of interest.", difficulty="medium"),
    Q("4.2.9", 2, "What does “no interaction” mean among the two-way ANOVA assumptions?",
      ["Effects of one factor depend strongly on the level of the other",
       "The impact of one factor is consistent across levels of the other",
       "Variances must differ in every cell",
       "Only Type I errors are allowed"],
      1, "Assumption 3: impact of one factor consistent across levels of the other (no interaction).", difficulty="medium"),
    # 4.2.10
    Q("4.2.10", 1, "What characterises a completely randomised design (CRD)?",
      ["Mandatory blocking into homogeneous groups before assignment",
       "Treatments allocated randomly to experimental units without grouping for homogeneity",
       "Only Latin squares are allowed",
       "No randomisation is used"],
      1, "CRD randomly allocates treatments without grouping units for more homogeneity.", difficulty="easy"),
    Q("4.2.10", 2, "In the single-factor effects model, what is H0?",
      ["All treatment effects τi equal zero",
       "All residuals infinite",
       "σ² < 0",
       "Only two treatments may exist"],
      0, "H0: α1 = … = αv = 0 (all treatment effects zero).", difficulty="medium"),
    # 4.2.11
    Q("4.2.11", 1, "Which is listed as an assumption checked in model adequacy?",
      ["Errors must have infinite mean",
       "Mistakes follow a normal distribution; mean zero; constant variance; uncorrelated; roughly linear mean structure",
       "Predictors must be ordinal ranks only",
       "Sample size must equal α"],
      1, "Five listed assumptions include linearity, zero-mean errors, constant variance, independence, normality.", difficulty="medium"),
    Q("4.2.11", 2, "How is a residual defined in the extract?",
      ["The population mean μ",
       "The difference between the observed and fitted value of the study variable",
       "The critical value ±1.96 only",
       "The prior probability in a Bayes Box"],
      1, "ei = yi − ŷi — observed minus fitted.", difficulty="easy"),
]


def main() -> None:
    assert len(CONCEPTS) == 22
    merge_module(
        module_id=MODULE_ID,
        module_title=MODULE_TITLE,
        tree_children=TREE_CHILDREN,
        concepts=CONCEPTS,
        questions=QUESTIONS,
        status="approved",
    )
    # quick counts
    from collections import Counter
    c = Counter(q["conceptId"] for q in QUESTIONS)
    missing = [cid for cid in CONCEPTS if c[cid] < 2]
    if missing:
        raise SystemExit(f"Concepts with <2 MCQs: {missing}")
    print(f"MCQ total: {len(QUESTIONS)}; per-concept min={min(c.values())} max={max(c.values())}")


if __name__ == "__main__":
    main()
