"""CSIT745 v2 Module 5 pack — Report Writing. Merges into subjects/csit745/v2/data/."""
from __future__ import annotations

from merge_util import merge_module

MODULE_ID = "m5"
MODULE_TITLE = "Module V · Report Writing"
MODULE_NUM = 5


def C(
    cid: str,
    title: str,
    section: str,
    pages: list[int],
    quick: str,
    key_ideas: list[str],
    detail: list[str],
    source_quote: str,
    *,
    compare: str | None = None,
    example: str | None = None,
    related: list[str] | None = None,
) -> dict:
    return {
        "id": cid,
        "title": title,
        "module": MODULE_NUM,
        "section": section,
        "pages": pages,
        "quick": quick,
        "keyIdeas": key_ideas,
        "detail": detail,
        "sourceQuote": source_quote,
        **({"compare": compare} if compare else {}),
        **({"example": example} if example else {}),
        "related": related or [],
    }


def Q(qid: str, concept_id: str, stem: str, options: list[str], correct: int, explanation: str) -> dict:
    return {
        "id": qid,
        "module": MODULE_NUM,
        "conceptId": concept_id,
        "stem": stem,
        "options": options,
        "correct": correct,
        "explanation": explanation,
    }


TREE_CHILDREN = [
    {
        "id": "5.1",
        "title": "Research Report",
        "children": [
            {"id": "5.1.1", "title": "5.1.1 Meaning of Research Report", "conceptId": "5.1.1"},
            {"id": "5.1.2", "title": "5.1.2 Structure of Scientific Report", "conceptId": "5.1.2"},
            {"id": "5.1.3", "title": "5.1.3 Components of a Scientific Report", "conceptId": "5.1.3"},
            {"id": "5.1.4", "title": "5.1.4 Types of Reports", "conceptId": "5.1.4"},
            {"id": "5.1.5", "title": "5.1.5 Steps in Report Writing", "conceptId": "5.1.5"},
            {"id": "5.1.6", "title": "5.1.6 Format and Writing Style", "conceptId": "5.1.6"},
            {"id": "5.1.7", "title": "5.1.7 Illustrations and Tables", "conceptId": "5.1.7"},
            {"id": "5.1.8", "title": "5.1.8 Citing and Referencing Sources", "conceptId": "5.1.8"},
            {"id": "5.1.9", "title": "5.1.9 Footnotes", "conceptId": "5.1.9"},
        ],
    },
    {
        "id": "5.2",
        "title": "Presentation",
        "children": [
            {"id": "5.2.1", "title": "5.2.1 Oral Presentation", "conceptId": "5.2.1"},
            {"id": "5.2.2", "title": "5.2.2 Making Presentation", "conceptId": "5.2.2"},
            {"id": "5.2.3", "title": "5.2.3 Use of Visual Aids", "conceptId": "5.2.3"},
            {"id": "5.2.4", "title": "5.2.4 Importance of Effective Communication", "conceptId": "5.2.4"},
            {"id": "5.2.5", "title": "5.2.5 Convention and Strategies of Authentication", "conceptId": "5.2.5"},
        ],
    },
    {
        "id": "5.3",
        "title": "Research Paper",
        "children": [
            {"id": "5.3.1", "title": "5.3.1 Preparing Research Papers for Journals", "conceptId": "5.3.1"},
            {"id": "5.3.2", "title": "5.3.2 Design of Paper Using Template", "conceptId": "5.3.2"},
            {"id": "5.3.3", "title": "5.3.3 Calculation of Impact Factor of a Journal", "conceptId": "5.3.3"},
            {"id": "5.3.4", "title": "5.3.4 Citation Index", "conceptId": "5.3.4"},
            {"id": "5.3.5", "title": "5.3.5 ISBN and ISSN", "conceptId": "5.3.5"},
        ],
    },
    {
        "id": "5.4",
        "title": "Project Proposal",
        "children": [
            {"id": "5.4.1", "title": "5.4.1 Identifying and Defining Problem", "conceptId": "5.4.1"},
            {"id": "5.4.2", "title": "5.4.2 Research Problem Aspects and Considerations", "conceptId": "5.4.2"},
            {"id": "5.4.3", "title": "5.4.3 Research Plan", "conceptId": "5.4.3"},
        ],
    },
]


CONCEPTS = {
    "5.1.1": C(
        "5.1.1",
        "Meaning of Research Report",
        "5.1.1",
        [131],
        "A research report is a formal, structured document that records an investigation and reaches impartial conclusions; workplaces treat reports as legal papers.",
        [
            "Three defining traits: predefined structure, independent sections, unbiased conclusions.",
            "Structure headers (introduction, discussion, conclusion) guide the reader.",
            "Sections can be read selectively without requiring a top-to-bottom read.",
        ],
        [
            "The module opens by defining a report as a formal document used across sciences, social sciences, engineering, and business — essentially documenting the process of pursuing a defined assignment.",
            "At a basic level, report writing is characterised by a predefined structure, independently written sections, and unbiased (impartial, objective) conclusions.",
            "Independent sections matter because readers often jump to the parts they need rather than reading the whole report linearly.",
        ],
        "There are three fundamental characteristics that define report writing at a basic level:",
        compare="Unlike informal notes or opinion pieces, a research report is expected to be structured, sectionally independent, and objective.",
        related=["5.1.2", "5.1.4"],
    ),
    "5.1.2": C(
        "5.1.2",
        "Structure of Scientific Report",
        "5.1.2",
        [131, 132],
        "A scientific report has preliminaries (title, TOC, etc.), contents (introduction; analysis/results), and reference materials (references, appendices, glossary, index).",
        [
            "Preliminaries: title page, preface/acknowledgements, graphs/illustrations/tables/charts, table of contents.",
            "Introduction covers aims, problem characterisation, hypotheses, concepts, literature, scope/assumptions/limitations, sampling, and methods.",
            "Analysis presents factual results, quantitative analysis, summary and suggested actions; reference block holds refs, appendices, glossary, index.",
        ],
        [
            "Preliminaries frame the document before the main narrative: title page, preface or foreword and acknowledgements, visuals lists, and table of contents.",
            "The introduction is where aims, problem definition, hypotheses, key concepts, literature review, survey logistics (time/location/resources), scope/assumptions/limitations, sampling organisation, and data-collection approaches belong.",
            "Results analysis covers type/volume/dimensions of findings, quantitative analysis, and a summary with suggested actions. Reference materials close with references, appendices (surveys, tables), glossary, and index.",
        ],
        "Analysis and presentation of results:",
        related=["5.1.3", "5.1.5"],
    ),
    "5.1.3": C(
        "5.1.3",
        "Components of a Scientific Report",
        "5.1.3",
        [132, 133],
        "A technical scientific report emphasises methods and sample design for peer academics: nature of work, methodology, data analysis, findings, bibliography, technical appendices.",
        [
            "Written mainly for other academics; techniques and sample design must be well elucidated.",
            "Main search/contents often limited to two or three pages; findings may span several chapters with tables/figures.",
            "Bibliography lists secondary sources; technical appendices hold surveys, derivations, detailed methods.",
        ],
        [
            "Technical reports differ in emphasis: colleagues care most about techniques used, and the extent of the search is tied to those strategies.",
            "Core components include a short main-contents overview; nature of the research (objectives, operational problem, working hypothesis, analysis type, data required); research methodology with constraints (e.g. sample size/selection); data analysis covering sources, qualities, limits, and collection procedures for surveys; findings presentation with corroborating tables/figures; bibliography; and technical appendices.",
        ],
        "A technical report is primarily intended for other academics and, as such, may be structured in a fundamentally different manner.",
        compare="Technical reports stress methods and sample design; non-technical audiences (e.g. finance heads) often want outcomes, not process (see Types of Reports).",
        related=["5.1.2", "5.1.4"],
    ),
    "5.1.4": C(
        "5.1.4",
        "Types of Reports",
        "5.1.4",
        [133, 134],
        "Reports are oral or written; written forms vary by time interval and by type (short/long, formal/informal, technical/non-technical, government).",
        [
            "Oral reports demand live interaction, careful planning of what/how/how much to say, and Q&A readiness.",
            "Written reports: short (narrow issue, ~5 pages e.g. monthly sales) vs long (technical + non-technical fusion).",
            "Technical reports detail sources, methods, sample, tools, analysis, appendix, conclusions; non-technical focus on managerial implications.",
        ],
        [
            "Oral presentation structure: opening (project nature, origins, objectives), findings/conclusions backed by evidence, suggestions tied to conclusions, then Q&A; visuals and tabular stats help. Prefer notes-driven extempore over memorisation or dull manuscript reading.",
            "Written categories by interval: daily, weekly, monthly, quarterly, yearly. By type: short, long, formal, informal, government.",
            "Examples: formal — marketing head’s quarterly test-marketing report to VP; informal — shift log book; government — rural employment strategy in a five-year plan.",
        ],
        "There are two types of reports (1) Oral report (2) Written report",
        example="A monthly sales report spanning about five pages for a product in a specified area is a short written report.",
        related=["5.2.1", "5.1.5"],
    ),
    "5.1.5": C(
        "5.1.5",
        "Steps in Report Writing",
        "5.1.5",
        [134, 135, 136],
        "After choosing the report type, structure it as: title page, contents, executive summary, body, conclusions/recommendations, bibliography, appendix.",
        [
            "Executive summary (1–2 pages): objectives, brief methodology, important findings, key results, conclusion — often all top executives read.",
            "Body: introduction, methodology/approach, limitations/constraints, analysis and interpretation.",
            "Appendix holds non-essential but supporting materials (questionnaires, cuttings, diagrams, interviewer instructions).",
        ],
        [
            "Title page states subject and preparing individual/organisation. Table of contents lists divisions with chapter titles and page numbers (declaration through appendix).",
            "The body introduction describes the decision issue and research purpose with organisational background; approach covers primary vs secondary data, instruments, sample size/plan, analysis method, exploratory vs conclusive design; constraints include time, geography, technique, response accuracy.",
            "Conclusions answer what outcomes were drawn; recommendations answer what you advise based on the study. Bibliography lists secondary sources with title, journal, volume, pages, edition.",
        ],
        "Once the type of report has been determined, the subsequent stage is to prepare the report.",
        related=["5.1.2", "5.1.6"],
    ),
    "5.1.6": C(
        "5.1.6",
        "Format and Writing Style",
        "5.1.6",
        [136, 137],
        "Physical layout creates first impression and navigability; style must simplify, justify with data, quantify, and inform rather than impress.",
        [
            "Layout: strong title page/TOC, uniform margins/spacing, consistent heading fonts (e.g. 16–18 chapter, 14 section, 12 subsection), quality print, numbered figures/tables, precise citations.",
            "Readers are short on time, busy, and often unfamiliar with research jargon.",
            "Prefer short sentences, active voice, logical presentation; avoid exaggeration and vague passives.",
        ],
        [
            "A well-formed physical layout creates a favourable first impression, shows organisational structure, and lets readers choose which section to read first.",
            "Style rules from the extract: simplify to essentials; justify every statement with facts/data; quantify (say 50% or one in three, not 'large'/'small'); be precise; inform not impress; use short sentences and spare adjectives; avoid passive voice that creates vagueness; stay logical and systematic.",
        ],
        "Justify. Make no statement that is not based on facts and data.",
        related=["5.1.5", "5.1.7"],
    ),
    "5.1.7": C(
        "5.1.7",
        "Illustrations and Tables",
        "5.1.7",
        [137, 138, 139],
        "Tables/figures need consistent titles/captions, legible text (≥2 mm), sequential numbering, and consistent placement; copyrighted material needs replacement notices.",
        [
            "Number sequentially through the thesis or as chapter.item (Table 1.1); never mix styles (Table 1 with Figure 1.3).",
            "Placement options: after first mention, end of chapter, or before bibliography — pick one and stay consistent.",
            "After reduction, lettering must remain readable; long reports use separate Lists of Figures/Tables.",
        ],
        [
            "Designate items as Table/Figure (etc.) with title/caption included in the relevant list; replicate headings on continued multi-page tables and break at sensible subheading boundaries.",
            "If a caption cannot fit on the same page as the visual, put it on a separate page. If visuals are grouped at the end, TOC must point to that location.",
            "For excluded copyrighted visuals: assert removal due to copyright, describe the material (with link if available), and give the full original reference.",
        ],
        "Regardless of the chosen technique, the numbering style must be consistent for all numbered items.",
        related=["5.1.6", "5.1.8"],
    ),
    "5.1.8": C(
        "5.1.8",
        "Citing and Referencing Sources",
        "5.1.8",
        [139, 140],
        "Numerical footnotes map to a consecutive reference list; bibliography entries follow Harvard-like formatting; use Op. cit., Loc. cit., and Ibid. for repeats.",
        [
            "List only publications actually referenced; title the section 'References' rather than 'Bibliography' when that is the case.",
            "Op. cit. = work previously cited (author, date, page as needed); Loc. cit. = same page previously cited; Ibid. = same work as immediately before.",
            "Abbreviations avoid full duplication when the same source is cited repeatedly.",
        ],
        [
            "Footnote numbers in text (e.g. after 'Recent studies suggest that…') correspond directly to the reference list ordered as cited.",
            "Individual citation formatting inside the bibliography mirrors the Harvard method described in the extract.",
        ],
        "The section should be titled ‘References’ instead of ‘Bibliography’, as indicated below.",
        compare="Footnotes (5.1.9) identify quoted materials and add supplementary notes; the reference list records the cited works.",
        related=["5.1.9", "5.3.4"],
    ),
    "5.1.9": C(
        "5.1.9",
        "Footnotes",
        "5.1.9",
        [140],
        "Footnotes identify quoted materials and add supplementary value (cross-refs, authorities, acknowledgements, elucidation); they are not a display of scholarship.",
        [
            "Two purposes: correct identification of quoted materials; supplementary value to the main body.",
            "Enable cross-references, citation of authorities/sources, acknowledgement, and explanation of a point of view.",
            "Recent trend is to avoid footnotes; they are neither an end nor a means of displaying scholarship.",
        ],
        [
            "Researchers insert footnotes at appropriate places. A numbered cue such as after 'Recent research indicates that…' points to the references.",
            "The extract cautions against treating footnotes as proof of scholarly display.",
        ],
        "The footnotes provide supplementary value to the main part(body) of the text.",
        related=["5.1.8"],
    ),
    "5.2.1": C(
        "5.2.1",
        "Oral Presentation",
        "5.2.1",
        [140, 141],
        "Oral presentation is harder than written reporting because of live audience interaction; plan content, delivery, volume, visuals, and Q&A.",
        [
            "Opening states project nature, how it arose, and what was attempted; conclusions backed by findings; recommendations supported by conclusions.",
            "Prefer expanding from concise notes (extempore) over memorisation or monotonous manuscript reading.",
            "Use simple language, strict time management, charts/graphs, circulated vital figures, audience knowledge, and purpose (decision vs information).",
        ],
        [
            "Any delay can leave a negative impression and undermine presenter confidence. Communication decisions — what/how/how much to say — and facing audience questions require substantial preparation.",
            "Method of presentation: use visuals when needed; tabular form helps statistical information. Logical sequencing is required.",
        ],
        "It’s more difficult to prepare as compared to the written report.",
        related=["5.1.4", "5.2.2", "5.2.3"],
    ),
    "5.2.2": C(
        "5.2.2",
        "Making Presentation",
        "5.2.2",
        [141, 142, 143],
        "Golden rule: human attention is limited — one idea per slide, clear intro and last-slide conclusions, rehearse aloud (≥5 times for important talks), never go overtime.",
        [
            "Organisation: strategic (non-technical) introduction; mention companion paper for details; periodic outline slides; sequential unifying thread; less is better.",
            "Mechanics: PowerPoint preferred (avoid LaTeX except formulas); humour only if natural; listen carefully to questions asked.",
            "Text: short titles, little text, no small fonts, few formulas/code; Illustrations: prefer pictures, restrained animation, strong vs pastel colour roles.",
        ],
        [
            "Do not put slides after the conclusion slide — that weakens impact. Do not expect the audience to remember colour-coding across slides; restate if needed.",
            "Give a high-level overview before details so listeners can relate details to the big picture and save attention for later important parts.",
            "Spell-check: a spelling mistake is an 'attention magnet'. Don't explain the completely obvious; don't treat the audience as impaired.",
        ],
        "Human attention is extremely limited. Don’t cram an excessive amount of information, either in each slide, or within the whole talk.",
        related=["5.2.1", "5.2.3"],
    ),
    "5.2.3": C(
        "5.2.3",
        "Use of Visual Aids",
        "5.2.3",
        [143, 144, 145, 146],
        "Visual aids (graphs, photos, video, slides, whiteboard, handouts, flip chart, posters) summarise, clarify, emphasise, engage — one key point per aid; ensure the talk still works without them.",
        [
            "Purposes: summarise/reduce spoken words, clarify with examples, emphasise, make memorable, enhance credibility, engage, ease understanding.",
            "During delivery: visible to all, don't read from the aid, explain immediately when shown, hide when unused.",
            "PowerPoint tips include ≥24pt font, simple background, purposeful animation only, avoid red/green text, one key point per slide.",
        ],
        [
            "Preparation: support the spoken message, avoid clutter, keep style consistent, use graphs/charts for data, moderate use for essential points only.",
            "Handouts: partially completed sheets force listening; giving full handouts too early causes reading instead of listening. Whiteboards suit process diagrams and persistent key definitions. Flip charts suit small audiences/brainstorming. Posters are portable but can be costly if complex. Videos: relevant, as short as needed, announce duration.",
        ],
        "One message per visual aid, for example, on a slide there should only be one key point.",
        related=["5.2.1", "5.2.2"],
    ),
    "5.2.4": C(
        "5.2.4",
        "Importance of Effective Communication",
        "5.2.4",
        [146, 147],
        "Effective communication (attentive listening, empathy, open-mindedness, helpful feedback, confident nonverbal cues) builds trust, prevents/resolves conflict, clarifies direction, and boosts engagement and productivity.",
        [
            "Benefits listed: building trust; preventing/resolving problems; providing clarity and direction; better relationships; increases engagement; improves productivity; promotes team building.",
            "Cited engagement study note: only 15% of adult employees engaged with employers — communication can raise engagement/satisfaction.",
            "Clarity includes constructive correction and clear roles to eliminate confusion.",
        ],
        [
            "Leaders who communicate well see better productivity and improved relationships at work and in personal life.",
            "Conflict resolution depends on remaining calm, ensuring all parties are heard, and finding an ideal solution for everyone involved.",
            "When roles and expectations are clear, people focus on work rather than workplace issues; conflicts resolve faster and distractions shrink.",
        ],
        "Effective communication involves knowing how to listen attentively. It’s the ability to offer empathy, open-mindedness, and helpful feedback.",
        related=["5.2.1", "5.2.5"],
    ),
    "5.2.5": C(
        "5.2.5",
        "Convention and Strategies of Authentication",
        "5.2.5",
        [147, 148],
        "Authenticate reports by interpreting tables (not dumping all cell numbers), using qualitative quotes with scientific value, and avoiding careless/outdated/unsupported content.",
        [
            "Pitfall: endless description without interpretation — tables need conclusions.",
            "Qualitative quotes illustrate findings and let readers draw conclusions (avoid biased selection).",
            "Avoid: inaccurate/conflicting data; outdated/irrelevant data; unseparated facts vs opinions; unsupported conclusions; careless proofreading; appearance over content.",
        ],
        [
            "Coding open opinions as mere counts without interpretation is called a serious maltreatment of data that needs correction — qualitative material can illustrate reasons and attitudes.",
            "Authentication here means making the report trustworthy: interpret evidence, separate fact from opinion, and support proposals.",
        ],
        "Tables need conclusions, not detailed presentation of all numbers or percentages within the cells which readers can see for themselves.",
        related=["5.1.6", "5.2.4"],
    ),
    "5.3.1": C(
        "5.3.1",
        "Preparing Research Papers for Journals",
        "5.3.1",
        [148, 149, 150, 151],
        "Journal preparation is a multi-step pipeline from authorship planning and early writing through peer review, proofs, and celebration of publication as completing the experiment.",
        [
            "Three peer-reviewed formats: full-length (IMRaD), short/brief (~≤3500 words, ≤2 tables/figures), rapid communications for 'hot' findings.",
            "Do not compromise on peer review when selecting a journal; consider language, focus, indexing, availability, reputation/IF, format, figures, time-to-print, charges.",
            "Build figures/tables before writing; revise in order: major alterations → polish style → format; answer every reviewer comment on resubmission.",
        ],
        [
            "Start writing before experiments finish — writing evokes new ideas for controls/experiments. Publish when findings form a complete, significant contribution.",
            "Stock Introduction/Methods/Results/Discussion folders; outline as a roadmap; assign co-author sections but edit to one voice.",
            "Robert Day: a spectacular experiment is not complete until results are published.",
        ],
        "The goal of scientific research is publication…. A particular experiment, no matter how spectacular the results, is not complete until the results are published.",
        related=["5.3.2", "5.3.3"],
    ),
    "5.3.2": C(
        "5.3.2",
        "Design of Paper Using Template",
        "5.3.2",
        [151, 152],
        "Use a hierarchical outline template: Introduction (background + thesis), sequenced main points with sub-points and supported examples, critical-thinking section, then conclusion affirming the thesis.",
        [
            "No fixed letter/number count — structure follows how many points the paper length requires.",
            "Never start a sentence with an unintroduced quotation.",
            "Critical thinking section: reactions to sources, insights, synthesise threads; conclusion affirms the thesis is proven.",
        ],
        [
            "First main point expands via sub-points, each with corresponding examples/details (insight or critic paraphrase/quote) plus supporting comments; continue alternating numerals and letters for further main points.",
            "The template keeps the argument operationally organised rather than free-form.",
        ],
        "Notice that no correct number of letters or numbers exists; the sole determining factor is the number of points we need to create for the specified length of our paper.",
        related=["5.3.1"],
    ),
    "5.3.3": C(
        "5.3.3",
        "Calculation of Impact Factor of a Journal",
        "5.3.3",
        [152, 153],
        "Journal impact factor (IF) for a year = citations in that year to items published in the prior two years, divided by the count of citable items in those two years.",
        [
            "IF measures how often the average article in a journal is cited in a given year — used to rank importance within a category.",
            "Example form: 2010 IF = A/B where A = 2010 cites to 2008–2009 articles; B = citable items published 2008–2009.",
            "Rule of thumb in extract: IF ≥10 excellent, ~3 good, average <1 — compare journals within the same category.",
        ],
        [
            "Calculation is based on a two-year period: divide times articles were cited by the number of citable articles.",
            "Cross-category IF comparisons are less meaningful than within-field comparisons.",
        ],
        "A/B = 2010 impact factor",
        example="If indexed journals cite 2008–2009 articles 500 times in 2010 and there were 100 citable items in 2008–2009, IF ≈ 5.0.",
        related=["5.3.1", "5.3.4"],
    ),
    "5.3.4": C(
        "5.3.4",
        "Citation Index",
        "5.3.4",
        [153, 154],
        "A citation index is a bibliographic database of citations between publications, showing which later documents cite earlier ones; citation count is how often an article is cited.",
        [
            "Major services: ISI/Thomson Reuters Web of Science (SCI, SSCI, A&HCI, etc.) and Elsevier Scopus.",
            "Other databases: CiteSeer, RePEc, Google Scholar, EBSCOhost, Compendex.",
            "Indian Citation Index (ICI) covers ~1000 Indian scholarly journals across disciplines and produces ISCI, ISSHCI, IJCR, ISTA, DOIJ.",
        ],
        [
            "A scientifically written article lists references serially; each reference is a citation. Citation indexes let users establish later→earlier citation links.",
            "Scopus is described as among the largest abstract/citation databases of peer-reviewed literature with tools to track citations.",
        ],
        "A citation index could be a kind of bibliographic database, an index of citations between publications, allowing the user to simply establish which later documents cite which earlier documents",
        related=["5.3.3", "5.1.8"],
    ),
    "5.3.5": C(
        "5.3.5",
        "ISBN and ISSN",
        "5.3.5",
        [154, 155],
        "ISBN identifies individual books/volumes (now 13-digit; mandatory where applicable); ISSN identifies serials/series (8-digit; optional) and stays the same across issues of a series.",
        [
            "ISBN = International Standard Book Number; ISSN = International Standard Serial Number.",
            "ISBN identifies publisher context for a monograph; ISSN does not identify the publisher the same way.",
            "ISSN drafted 1971; assigned by National Centres, coordinated by ISSN International Centre in Paris.",
        ],
        [
            "History: Gordon Foster's nine-digit code → ISO ten-digit → after 2007, 13-digit ISBN. Different formats (hardback, PDF, EPUB) get different ISBNs.",
            "When a series changes, another ISSN is allotted; all volumes of one series share the same ISSN.",
        ],
        "“ISBN” stands for “International Standard Book Number” whereas “ISSN” is “International Standard Serial Number.”",
        compare="ISBN differs per volume/issue; ISSN is identical across volumes of one series.",
        example="ISSN 0027-9633 (online); ISBN 978-951-45-9693-3 (hardback).",
        related=["5.3.1"],
    ),
    "5.4.1": C(
        "5.4.1",
        "Identifying and Defining Problem",
        "5.4.1",
        [159, 160],
        "Selecting and properly defining the research problem is the first step; a research problem is a situation needing description, explanation, or prediction of a solution.",
        [
            "Like a doctor, examine all symptoms before diagnosing the problem correctly.",
            "Components: a person/group with difficulty; objectives; alternative means; doubt about relative efficiency of alternatives; an environment of the difficulty.",
            "Problem selection often hard not from scarcity of topics but from finding socially relevant work without duplicating earlier studies; may identify a knowledge gap.",
        ],
        [
            "Identifying a research problem refers to difficulty in a theoretical or practical situation seeking a solution — the focus or reason for the research.",
            "Defining the problem drives the scientific process and underpins method and experimental design.",
        ],
        "Research problem: A situation or circumstances that require a solution to be described, explained or predicted.",
        related=["5.4.2", "5.4.3"],
    ),
    "5.4.2": C(
        "5.4.2",
        "Research Problem Aspects and Considerations",
        "5.4.2",
        [160, 161],
        "Define a problem by stating it within clear study bounds: statement, nature/origin, literature survey, deduction from theory, then rephrase into an operational working proposition.",
        [
            "Aspects: (i) statement of the problem (ii) understanding nature/origin (iii) surveying available literature (iv) deduction from theory (v) rephrasing into a working proposition.",
            "Broad general questions are usually unsuitable for testing until narrowed operationally.",
            "Considerations: identify concepts/terms in the topic; review related literature (incl. multidisciplinary databases); use additional sources to strengthen arguments.",
        ],
        [
            "Literature survey reveals available vs required materials, theory gaps, inconsistent theories, or findings that break theoretical expectations — enabling new strides from existing premises.",
            "Related studies flag likely difficulties and analytical shortcomings and may suggest new approaches. Do not define the problem hurriedly.",
            "A research guide can help consider problems carefully.",
        ],
        "Defining a research problem properly and clearly is a crucial part of a research study and must in no case be accomplished hurriedly.",
        related=["5.4.1", "5.4.3"],
    ),
    "5.4.3": C(
        "5.4.3",
        "Research Plan",
        "5.4.3",
        [158, 159, 162, 163],
        "A research plan is the blueprint for resolving the defined problem: design, collect, interpret, and report — alongside proposal planning (objectives, scope, feasibility, work plan, budget, risk, stakeholders, metrics).",
        [
            "Locate/define issues with purpose, background, needed information, and decision use.",
            "Design steps include secondary data, qualitative analysis, quantitative methods, data definition, measurement/scaling, questionnaire, sampling, analysis strategy.",
            "Collect via interviews, observation, questionnaires, focus groups, documents; interpret by ordering findings then drafting conclusions; report via formal paper, article, PowerPoint, A/V, spreadsheet — plus oral presentation with tables/figures/graphs.",
        ],
        [
            "Proposal planning also covers defining objectives, identifying scope (prevent creep), feasibility (technical/financial/operational), work plan/milestones/roles, budgeting, risk management, stakeholder engagement, evaluation metrics, documentation, and review/revision.",
            "Field collection examples: in-home/mall/CAPI, telephone/CATI, traditional mail and mail panels.",
        ],
        "A research plan or approach is a blueprint or framework for carrying out a marketing research project.",
        related=["5.4.1", "5.4.2", "5.1.5"],
    ),
}


QUESTIONS = [
    # 5.1.1
    Q("m5-5.1.1-a", "5.1.1",
      "Which is one of the three fundamental characteristics of report writing?",
      ["Personal opinion throughout", "Predefined structure", "Mandatory memorisation of findings", "Subjective conclusions only"],
      1, "The extract lists predefined structure, independent sections, and unbiased conclusions."),
    Q("m5-5.1.1-b", "5.1.1",
      "Why are report sections written independently?",
      ["To hide methodology from readers", "So readers can selectively read sections of interest", "Because conclusions must be subjective", "To avoid using a title page"],
      1, "Independent sections let readers jump to parts they need rather than reading top to bottom."),
    Q("m5-5.1.1-c", "5.1.1",
      "How does the module characterise workplace reports?",
      ["As informal emails", "As legal papers in all workplaces", "As optional marketing flyers", "As unedited brainstorm notes"],
      1, "The text states reports are regarded as legal papers in all workplaces."),
    # 5.1.2
    Q("m5-5.1.2-a", "5.1.2",
      "Which item belongs in the preliminaries of a scientific report?",
      ["Glossary definitions only", "Title page", "Full data analysis narrative", "Bibliography entries"],
      1, "Preliminaries include title page, preface/acknowledgements, visuals, and TOC."),
    Q("m5-5.1.2-b", "5.1.2",
      "Where do research aims and hypotheses appear in the scientific report structure?",
      ["Glossary", "Introduction", "Index only", "Technical appendices only"],
      1, "Introduction covers aims, problem characterisation, hypotheses, and key concepts."),
    Q("m5-5.1.2-c", "5.1.2",
      "Which belongs under reference materials?",
      ["Hypothesis formulation", "Sample selection methods narrative", "Appendices, glossary, and index", "Scope and assumptions only"],
      2, "Reference materials include references, appendices, glossary, and index."),
    # 5.1.3
    Q("m5-5.1.3-a", "5.1.3",
      "Who is the primary audience for a technical scientific report?",
      ["General newspaper readers", "Other academics in the field", "Only accountants", "Only school students"],
      1, "A technical report is primarily intended for other academics."),
    Q("m5-5.1.3-b", "5.1.3",
      "What do same-field colleagues mostly focus on in a technical report?",
      ["Cover design colours", "Techniques/methods employed", "Only the acknowledgements", "Marketing slogans"],
      1, "Colleagues are mostly focused on the techniques employed."),
    Q("m5-5.1.3-c", "5.1.3",
      "What do technical appendices typically encompass?",
      ["Only the title page", "Surveys, mathematical derivations, and detailed analytic methods", "Executive summary only", "Oral presentation jokes"],
      1, "Technical appendices hold surveys, derivations, and detailed analytic methodologies."),
    # 5.1.4
    Q("m5-5.1.4-a", "5.1.4",
      "Which report type requires direct audience interaction and careful live communication?",
      ["Written short report", "Oral report", "Bibliography", "Glossary"],
      1, "Oral reports involve direct interaction; delays can harm impression and confidence."),
    Q("m5-5.1.4-b", "5.1.4",
      "A monthly sales report of about five pages for a limited investigation is best classed as a:",
      ["Government five-year plan", "Short report", "Rapid journal communication", "Citation index"],
      1, "Short reports suit clearly identified issues with restricted extent; monthly sales ~five pages is the example."),
    Q("m5-5.1.4-c", "5.1.4",
      "A non-technical report is typically aimed at readers who:",
      ["Need full sample design detail", "Lack technical qualifications and may care mainly about outcomes like profit/sales", "Only want mathematical derivations", "Must memorise the manuscript"],
      1, "Example: finance head focused on financial ramifications, not the process."),
    # 5.1.5
    Q("m5-5.1.5-a", "5.1.5",
      "What should an executive summary mainly help top executives do?",
      ["Replace the bibliography", "Facilitate decision-making with a 1–2 page precise overview", "List every raw questionnaire", "Hide limitations"],
      1, "Executive summary emphasises key elements for busy executives and should aid decision-making."),
    Q("m5-5.1.5-b", "5.1.5",
      "Which sequence matches the report structure after the report type is chosen?",
      ["Appendix → Title → Body only", "Title page → Contents → Executive summary → Body → Conclusions → Bibliography → Appendix", "Only footnotes", "ISSN then ISBN"],
      1, "The extract lists those seven structural steps in order."),
    Q("m5-5.1.5-c", "5.1.5",
      "What belongs in the appendix?",
      ["Only the thesis statement", "Non-essential supporting items such as questionnaires, charts, and interviewer instructions", "The entire executive summary", "Impact factor formula only"],
      1, "Appendix provides non-essential but related materials including data-collection forms."),
    # 5.1.6
    Q("m5-5.1.6-a", "5.1.6",
      "Which writing rule does the extract emphasise for report style?",
      ["Impress with exaggeration", "Justify every statement with facts and data", "Always use passive voice", "Prefer vague words like 'large' over numbers"],
      1, "Rules include justify with facts/data; quantify when possible; inform not impress."),
    Q("m5-5.1.6-b", "5.1.6",
      "Why avoid passive voice when possible?",
      ["It shortens the TOC", "It can create vagueness and dull reading", "It is required by ISBN rules", "It increases impact factor"],
      1, "Example: 'patients were interviewed' leaves who interviewed them unclear."),
    Q("m5-5.1.6-c", "5.1.6",
      "What should physical layout help readers do promptly?",
      ["Memorise every table", "Decide which section to read first", "Skip peer review", "Avoid numbering figures"],
      1, "Layout motivates readers by clarifying organisation so they can choose sections first."),
    # 5.1.7
    Q("m5-5.1.7-a", "5.1.7",
      "Which numbering practice is correct?",
      ["Mix Table 1 with Figure 1.3 in the same thesis", "Use one consistent scheme for all numbered items", "Never number figures", "Number only copyrighted images"],
      1, "Use sequential or chapter.item consistently — never mix styles."),
    Q("m5-5.1.7-b", "5.1.7",
      "Minimum height recommended for text in tables/figures for legibility?",
      ["0.5 mm", "2 mm", "20 mm", "No minimum"],
      1, "Text in tables and figures should have a minimum height of 2 mm."),
    Q("m5-5.1.7-c", "5.1.7",
      "If a copyrighted figure is excluded, what should appear in its place?",
      ["Blank silence with no note", "A copyright-limitation assertion, description/link if available, and full original reference", "Only the author's joke", "An uncited screenshot"],
      1, "The extract requires assertion, description/link, and complete reference."),
    # 5.1.8
    Q("m5-5.1.8-a", "5.1.8",
      "What does 'Ibid.' mean in bibliographic abbreviations?",
      ["A new unrelated source", "The same work given immediately before", "Only online sources", "An ISBN code"],
      1, "Ibid. (ibidem) means the same work referenced immediately before."),
    Q("m5-5.1.8-b", "5.1.8",
      "When only cited works are listed, how should the section be titled?",
      ["Bibliography (always)", "References", "Appendix", "Glossary"],
      1, "If only referenced publications are included, title it 'References' instead of 'Bibliography'."),
    Q("m5-5.1.8-c", "5.1.8",
      "Loc. cit. refers to:",
      ["A brand-new book never cited", "The same page of a work previously referenced", "Impact factor calculation", "A flip-chart tip"],
      1, "Loc. cit. means in the place cited — same page of a previously referenced work."),
    # 5.1.9
    Q("m5-5.1.9-a", "5.1.9",
      "One primary purpose of footnotes is to:",
      ["Replace the need for any references", "Correctly identify materials used in quotations", "Increase ISSN length", "Hide unsupported conclusions"],
      1, "Footnotes identify quoted materials and add supplementary value to the body."),
    Q("m5-5.1.9-b", "5.1.9",
      "What does the extract say about using footnotes to display scholarship?",
      ["They are the best way to prove scholarship", "They are neither an end nor a means of displaying scholarship", "They are legally mandatory everywhere", "They replace peer review"],
      1, "Recent trend is to avoid footnotes; they are not for displaying scholarship."),
    Q("m5-5.1.9-c", "5.1.9",
      "Besides identifying quotations, footnotes can provide:",
      ["Only colour psychology survey results", "Cross-references, authorities, acknowledgements, and elucidation", "ISBN assignment in Paris", "ANOVA tables only"],
      1, "They support cross-references, citation of authorities/sources, acknowledgement, and explanation."),
    # 5.2.1
    Q("m5-5.2.1-a", "5.2.1",
      "Why is oral presentation often harder than a written report?",
      ["No planning is allowed", "The presenter interacts directly with the audience and must handle questions live", "Oral talks forbid visuals", "Oral talks never need conclusions"],
      1, "Direct interaction, timing pressure, and Q&A make oral reports more demanding."),
    Q("m5-5.2.1-b", "5.2.1",
      "Which delivery approach is recommended?",
      ["Rely entirely on memorisation", "Expand from concise notes in a logical extempore style", "Read the full manuscript in a monotone", "Skip the opening statement"],
      1, "Memorisation risks slips; manuscript reading is dull; notes-based extempore is best."),
    Q("m5-5.2.1-c", "5.2.1",
      "Every recommendation in an oral presentation should be:",
      ["Unsupported speculation", "Supported by a conclusion", "Hidden from the audience", "Longer than the findings"],
      1, "Every recommendation should have the support of a conclusion."),
    # 5.2.2
    Q("m5-5.2.2-a", "5.2.2",
      "According to the golden rule for presentations:",
      ["Cram maximum detail on every slide", "Human attention is limited — avoid cramming excess information", "Always end with extra slides after conclusions", "Never rehearse"],
      1, "Don't cram excessive information in each slide or the whole talk."),
    Q("m5-5.2.2-b", "5.2.2",
      "Where should the conclusion slide be placed?",
      ["First slide only", "As the last slide — nothing after it", "After a long appendix of formulas", "Hidden in handouts only"],
      1, "Putting other slides after conclusions weakens their impact."),
    Q("m5-5.2.2-c", "5.2.2",
      "For an important talk, the extract suggests a minimum of how many rehearsals?",
      ["One silent skim", "Five rehearsals (preferably aloud)", "Fifty memorised run-throughs", "Zero — improvisation only"],
      1, "Five rehearsals is a minimum; rehearsal aloud is most helpful."),
    # 5.2.3
    Q("m5-5.2.3-a", "5.2.3",
      "How many key points should each slide/visual aid carry?",
      ["As many as possible", "One key point", "Exactly ten", "None — text only"],
      1, "One message per visual aid; one key point per slide."),
    Q("m5-5.2.3-b", "5.2.3",
      "Recommended minimum PowerPoint font size in the tips?",
      ["8pt", "12pt", "24pt", "6pt"],
      2, "Use a large font size — a minimum of 24pt."),
    Q("m5-5.2.3-c", "5.2.3",
      "When a visual aid is shown, the presenter should:",
      ["Ignore it and keep reading notes", "Immediately explain it because attention shifts to it", "Leave it unexplained", "Use only red and green text"],
      1, "Audience attention is drawn to the aid, so explain it at once; avoid red/green text."),
    # 5.2.4
    Q("m5-5.2.4-a", "5.2.4",
      "Which is listed as a benefit of effective communication?",
      ["Guaranteed higher impact factor", "Building trust", "Eliminating the need for reports", "Avoiding all stakeholder contact"],
      1, "Benefits include building trust, resolving problems, clarity, relationships, engagement, productivity, team building."),
    Q("m5-5.2.4-b", "5.2.4",
      "Effective communication especially involves:",
      ["Ignoring other viewpoints", "Listening attentively and offering empathy and helpful feedback", "Speaking only in research jargon", "Never giving direction"],
      1, "Attentive listening, empathy, open-mindedness, and helpful feedback are central."),
    Q("m5-5.2.4-c", "5.2.4",
      "The engagement statistic cited in the extract is that only about what share of adult employees are engaged with their employers?",
      ["85%", "50%", "15%", "0%"],
      2, "According to the cited study note, only 15% of adult employees are engaged."),
    # 5.2.5
    Q("m5-5.2.5-a", "5.2.5",
      "What should accompany tables in a trustworthy report?",
      ["Every cell percentage restated in prose", "Conclusions/interpretation, not just raw cell dumps", "No numbers at all", "Only decorative borders"],
      1, "Tables need conclusions; readers can see the numbers themselves."),
    Q("m5-5.2.5-b", "5.2.5",
      "Using informant quotes as illustrations can have scientific value because they:",
      ["Replace all quantitative analysis", "Allow readers to draw their own conclusions from established knowledge (if not biased)", "Remove the need for proofreading", "Are dated automatically"],
      1, "Quotes make reports lively and let readers draw conclusions if representation is unbiased."),
    Q("m5-5.2.5-c", "5.2.5",
      "Which pitfall must be avoided when preparing a report?",
      ["Separating facts from opinions", "Unsupported conclusions and proposals", "Interpreting qualitative data", "Proofreading carefully"],
      1, "Avoid unsupported conclusions, careless data, outdated material, and appearance over content."),
    # 5.3.1
    Q("m5-5.3.1-a", "5.3.1",
      "Which journal feature should you not compromise on for research articles?",
      ["Colour plate fees", "Peer review for publication", "Page charges", "Fancy animations"],
      1, "Manuscripts must be peer reviewed to be considered research articles."),
    Q("m5-5.3.1-b", "5.3.1",
      "When should you ideally start writing the paper?",
      ["Only after dismantling all lab equipment", "Before experiments are complete", "After proofs arrive", "Never — only present orally"],
      1, "Start writing while experiments continue; writing evokes new ideas and needed controls."),
    Q("m5-5.3.1-c", "5.3.1",
      "Typical length guidance for short/brief communications in the extract?",
      ["Unlimited chapters", "Typically 3500 words or less with up to 2 tables/figures", "Exactly one sentence", "Only ISBN metadata"],
      1, "Short communications are typically ≤3500 words and up to 2 tables and figures."),
    # 5.3.2
    Q("m5-5.3.2-a", "5.3.2",
      "What determines how many outline letters/numbers a paper template uses?",
      ["A fixed universal count", "The number of points needed for the paper’s length", "The journal’s impact factor only", "ISSN digit rules"],
      1, "No correct fixed count — structure follows points required for the length."),
    Q("m5-5.3.2-b", "5.3.2",
      "How should quotations be introduced?",
      ["Start a sentence with an unintroduced quote", "Never start a sentence with a quote that hasn’t been introduced", "Only use quotes in footnotes", "Quotes replace the thesis"],
      1, "Never start a sentence with a quote that hasn’t been introduced."),
    Q("m5-5.3.2-c", "5.3.2",
      "The conclusion of the template should:",
      ["Introduce a new untested thesis", "Affirm that the thesis has been proven", "List only ISBNs", "Omit critical thinking"],
      1, "Conclusion: affirm that the thesis has been proven."),
    # 5.3.3
    Q("m5-5.3.3-a", "5.3.3",
      "Impact factor calculation is based on what citation window?",
      ["One week", "A two-year period of citable items", "Fifty years only", "The day of submission"],
      1, "IF uses a 2-year period: cites in year Y to items from Y-1 and Y-2, divided by citable items."),
    Q("m5-5.3.3-b", "5.3.3",
      "For 2010 IF, A represents:",
      ["Page charges", "Times 2008–2009 articles were cited by indexed journals during 2010", "Number of oral presentations", "ISSN check digits"],
      1, "A = citations in 2010 to articles published in 2008 and 2009."),
    Q("m5-5.3.3-c", "5.3.3",
      "Per the extract’s rule of thumb, an IF of 10 or higher is considered:",
      ["Poor", "Average (<1)", "Excellent", "Invalid"],
      2, "IF of 10+ is excellent; ~3 good; average score less than 1 — compare within category."),
    # 5.3.4
    Q("m5-5.3.4-a", "5.3.4",
      "A citation index primarily lets users:",
      ["Print only posters", "See which later documents cite earlier documents", "Assign ISBNs", "Skip literature review"],
      1, "It indexes citations between publications for later→earlier links."),
    Q("m5-5.3.4-b", "5.3.4",
      "Web of Science is associated in the extract with:",
      ["Only flip charts", "ISI / Thomson Reuters citation indexes (SCI, SSCI, A&HCI, etc.)", "Paris ISSN centre only", "Shift log books"],
      1, "ISI (now Thomson Reuters) publishes citation indexes accessed online as Web of Science."),
    Q("m5-5.3.4-c", "5.3.4",
      "Indian Citation Index (ICI) is described as covering about how many Indian scholarly journals?",
      ["10", "100", "1000", "1 million"],
      2, "ICI covers about 1000 Indian scholarly journals across disciplines."),
    # 5.3.5
    Q("m5-5.3.5-a", "5.3.5",
      "ISBN is primarily assigned to:",
      ["Serials/series only", "Individual monographs/books (volumes)", "Only conference jokes", "Oral Q&A sessions"],
      1, "ISBN is for monographs/books; ISSN for series of monographs/books."),
    Q("m5-5.3.5-b", "5.3.5",
      "After 2007, the standard ISBN length is:",
      ["8 digits", "9 digits", "13 digits", "2 digits"],
      2, "After 2007, ISBN incorporated a 13-digit standard code."),
    Q("m5-5.3.5-c", "5.3.5",
      "Which statement about ISSN is correct?",
      ["It must differ for every volume of a series", "It is identical across volumes/issues of a single series and is optional", "It always identifies the publisher like ISBN", "It replaced peer review in 1971"],
      1, "ISSN is the same across a series, optional for publishers, 8-digit, coordinated from Paris."),
    # 5.4.1
    Q("m5-5.4.1-a", "5.4.1",
      "In the research process, the first and foremost step is:",
      ["Printing colour plates", "Selecting and properly defining a research problem", "Celebrating publication", "Assigning ISSN codes"],
      1, "Selecting and properly defining the research problem comes first."),
    Q("m5-5.4.1-b", "5.4.1",
      "A research problem is defined as:",
      ["Any favourite hobby", "A situation/circumstances requiring a solution to be described, explained, or predicted", "Only a statistical formula", "A PowerPoint animation"],
      1, "The extract defines research problem in those terms."),
    Q("m5-5.4.1-c", "5.4.1",
      "Which is a required component of a research problem setup?",
      ["No objectives at all", "Alternative means for obtaining the objectives, with doubt about relative efficiency", "Guaranteed single solution with no alternatives", "No environmental context"],
      1, "Components include person/group with difficulty, objectives, alternatives, doubt about efficiency, and environment."),
    # 5.4.2
    Q("m5-5.4.2-a", "5.4.2",
      "Defining a research problem mainly involves:",
      ["Leaving boundaries undefined", "Laying down bounds within which the problem will be studied with a predetermined objective", "Skipping literature", "Rushing the statement"],
      1, "Definition states the problem along with bounds of study."),
    Q("m5-5.4.2-b", "5.4.2",
      "Which is one of the five aspects listed for defining a problem?",
      ["Ignoring theory", "Surveying the available literature", "Deleting all related studies", "Avoiding rephrasing"],
      1, "Aspects include statement, nature, literature survey, deduction from theory, rephrasing."),
    Q("m5-5.4.2-c", "5.4.2",
      "Rephrasing the research problem into a working proposition makes it:",
      ["Broader and ambiguous", "Operationally viable and helpful for developing the research", "Unfit for testing", "Independent of literature"],
      1, "Rephrasing puts the problem in specific, operationally viable terms."),
    # 5.4.3
    Q("m5-5.4.3-a", "5.4.3",
      "A research plan/approach is described as:",
      ["A random set of unconnected slides", "A blueprint/framework for carrying out the research project", "Only an ISSN application", "A memorised speech"],
      1, "It is a blueprint to test hypotheses, answer questions, and inform decisions."),
    Q("m5-5.4.3-b", "5.4.3",
      "Which is a step in the research design list?",
      ["Skip sampling entirely", "Designing a questionnaire and defining sampling/sample size", "Publish without data", "Avoid secondary data analysis"],
      1, "Design steps include secondary data, qualitative/quantitative methods, measurement, questionnaire, sampling, analysis strategy."),
    Q("m5-5.4.3-c", "5.4.3",
      "The final reporting step should present findings so decision-makers can:",
      ["Never use them", "Understand and use them quickly — often with tables/figures/graphs and an oral presentation", "Only hear unsupported opinions", "Ignore metrics and risk"],
      1, "Report findings in an understandable format for decision-making; oral presentation with visuals improves clarity."),
]


def main() -> None:
    merge_module(
        module_id=MODULE_ID,
        module_title=MODULE_TITLE,
        tree_children=TREE_CHILDREN,
        concepts=CONCEPTS,
        questions=QUESTIONS,
        status="approved",
    )
    print(f"Leaves covered: {len(CONCEPTS)}")
    print(f"MCQs: {len(QUESTIONS)}")
    by_c = {}
    for q in QUESTIONS:
        by_c.setdefault(q["conceptId"], 0)
        by_c[q["conceptId"]] += 1
    missing = [c for c in CONCEPTS if by_c.get(c, 0) < 2]
    if missing:
        raise SystemExit(f"Concepts with <2 MCQs: {missing}")
    print("OK: every concept has >=2 MCQs")


if __name__ == "__main__":
    main()
