"""CSIT745 v2 — Module II (Sampling) content pack.

Merges Module II into knowledge_tree / concepts / mcq_bank / coverage
without wiping other modules. Source: subjects/csit745/v2/source/module_2.txt
(PDF pages 32–56).
"""
from __future__ import annotations

from merge_util import merge_module

MODULE_ID = "m2"
MODULE_TITLE = "Module II: Sampling"


def cid(section: str) -> str:
    return section


TREE_CHILDREN = [
    {
        "id": "2.1",
        "title": "2.1 Data Collection",
        "children": [
            {"id": "2.1.1", "title": "2.1.1 Introduction to Data Collection", "conceptId": "2.1.1"},
            {"id": "2.1.2", "title": "2.1.2 Data Collection Methods", "conceptId": "2.1.2"},
            {"id": "2.1.3", "title": "2.1.3 Tabulating and Validating Data", "conceptId": "2.1.3"},
        ],
    },
    {
        "id": "2.2",
        "title": "2.2 Questionnaire Designing",
        "children": [
            {"id": "2.2.1", "title": "2.2.1 Steps in Constructing a Questionnaire", "conceptId": "2.2.1"},
            {"id": "2.2.2", "title": "2.2.2 Types of Questions", "conceptId": "2.2.2"},
            {"id": "2.2.3", "title": "2.2.3 Format of Questionnaire", "conceptId": "2.2.3"},
        ],
    },
    {
        "id": "2.3",
        "title": "2.3 Sampling",
        "children": [
            {"id": "2.3.1", "title": "2.3.1 Sampling Plan", "conceptId": "2.3.1"},
            {"id": "2.3.2", "title": "2.3.2 Sampling Frame", "conceptId": "2.3.2"},
            {"id": "2.3.3", "title": "2.3.3 Sample Selection Methods", "conceptId": "2.3.3"},
            {"id": "2.3.4", "title": "2.3.4 Probability Sampling Techniques", "conceptId": "2.3.4"},
            {"id": "2.3.5", "title": "2.3.5 Non-Probability Sampling Techniques", "conceptId": "2.3.5"},
            {"id": "2.3.6", "title": "2.3.6 Sampling and Non-Sampling Errors", "conceptId": "2.3.6"},
        ],
    },
]

CONCEPTS = {
    "2.1.1": {
        "id": "2.1.1",
        "title": "Introduction to Data Collection",
        "module": 2,
        "pages": [33],
        "section": "2.1.1",
        "quick": "Primary data is information gathered through original or first-hand research; secondary data is information already gathered by someone else.",
        "keyIdeas": [
            "Primary examples: surveys and focus group discussions.",
            "Secondary examples: internet research, newspaper articles, and company reports.",
            "Whether primary or secondary data is collected depends on the study’s goal.",
            "Primary collection is usually more expensive and time-consuming than secondary, but serves a specific purpose and helps eliminate biases.",
        ],
        "detail": [
            "Section 2.1.1 contrasts first-hand (primary) versus already-collected (secondary) information.",
            "A firm entering India’s women’s apparel market can use secondary sources (industry reports, newspaper articles) to estimate market size, but must use primary research to learn consumer preferences for a new fabric or style.",
        ],
        "sourceQuote": "Information gathered through original or first-hand research is referred to as primary data.",
        "example": "Market size for women’s apparel in India → secondary reports; preferences for a new fabric/style → primary research.",
        "related": ["2.1.2", "2.1.3", "2.2.1"],
    },
    "2.1.2": {
        "id": "2.1.2",
        "title": "Data Collection Methods",
        "module": 2,
        "pages": [33, 34, 35, 36, 37, 38, 39, 40],
        "section": "2.1.2",
        "quick": "Primary data is first-hand information gathered for a specific goal; secondary data has already been gathered and evaluated by someone other than the user.",
        "keyIdeas": [
            "Primary methods include observation, interviews (personal/telephonic), questionnaires, and schedules.",
            "Observation types: structured/unstructured; participant/non-participant/disguised; controlled/uncontrolled.",
            "Secondary sources are published (government, journals, research institutes) or unpublished (agency records, academic work).",
            "Before using secondary data, check reliability, appropriateness/suitability, and adequacy (Bowley: do not accept at face value).",
            "Primary collection also splits into quantitative (time series, smoothing, barometric) and qualitative (surveys, polls, interviews, Delphi, focus groups, questionnaires) methods.",
        ],
        "detail": [
            "Primary data is culled from unprocessed first-hand sources such as surveys, experiments, and experimental results; it is described as more trustworthy, genuine, and impartial when carefully gathered at source for a specific goal.",
            "Observation becomes a scientific tool when methodical, goal-directed, and subject to checks and controls. Benefits include eliminating subjective bias and capturing natural behaviour; drawbacks include cost, limited information, and unforeseen interference.",
            "Interview methods present oral-verbal stimuli and record oral-verbal answers: personal (direct investigation, indirect oral examination), structured/unstructured, focused, clinical, and non-directive; telephonic interviews call respondents and ask questions by phone.",
            "In the questionnaire approach respondents complete forms independently; a pilot study can surface problems before the main survey. Schedules differ because enumerators fill them in; good enumerators are skilled, trustworthy, and patient.",
            "Published secondary sources include international bodies (IMF, IBRD, UNO), central/state government publications (e.g. RBI Bulletin, Census of India), semi-official bodies, research institutes (ISI, ICAR), commercial/financial reports, committees, and journals/newspapers. Unpublished sources include agency records and university research.",
            "Precautions: suitability (match scope/nature—e.g. wholesale vs retail prices), adequacy (geography/time fit), and reliability (consistent methods/replicable results).",
        ],
        "sourceQuote": "Secondary data should not be accepted at their face value,",
        "compare": "Questionnaire: respondents complete the form themselves. Schedule: enumerators designated for the purpose fill out the schedules and clarify study goals.",
        "example": "Suitability check: retail-price trends cannot use data meant only for wholesale prices; adequacy check: UP-only data is useless for all-India retail trends.",
        "related": ["2.1.1", "2.1.3", "2.2.1", "2.2.2"],
    },
    "2.1.3": {
        "id": "2.1.3",
        "title": "Tabulating and Validating Data",
        "module": 2,
        "pages": [40, 41, 42],
        "section": "2.1.3",
        "quick": "Tabulation arranges structured numerical data into rows and columns; data validation verifies whether a data item’s value comes from an acceptable set of values.",
        "keyIdeas": [
            "Tabulation objectives include orderly arrangement, bringing out essential features, simplification, conserving space, ease of comparison, summation, error detection, and facilitating statistical computation.",
            "UNECE (2013): validation checks whether a value belongs to the given set of acceptable values; it is a form of data cleansing.",
            "Validation reasons include cost-effectiveness, removing duplicates, business improvement via better information, and a cleaned standard dataset.",
            "Validity types covered: construct (convergent/discriminant), internal, external (population/ecological), criterion (concurrent/predictive), content, face, and statistical conclusion validity.",
        ],
        "detail": [
            "Tabulation’s complexity depends on the kind of classification; it supports further statistical analysis and interpretation by bringing relevant data together.",
            "Internal validity concerns establishing causal relationships and ruling out alternatives (threats: confounding, selection bias, measurement errors). External validity concerns generalisation to other settings, populations, or times.",
            "Criterion validity evaluates how well one measure predicts an outcome based on another measure. Face validity is often considered the weakest form but can matter for stakeholder acceptance.",
            "Statistical conclusion validity concerns whether conclusions about relationships among variables are correct and reliable (appropriate tests and met assumptions).",
            "When altering primary data, keep it comprehensive, precise, consistent, and constant; editing forms are required for those qualities.",
        ],
        "sourceQuote": "data validation is an activity aimed at verifying whether the value of a data item comes from the given (finite or infinite) set of acceptable values.",
        "example": "An email query can automatically verify address validity; a phone-number query can use country code to check whether the number is valid.",
        "related": ["2.1.1", "2.1.2", "2.3.6"],
    },
    "2.2.1": {
        "id": "2.2.1",
        "title": "Steps in Constructing a Questionnaire",
        "module": 2,
        "pages": [42, 43, 44],
        "section": "2.2.1",
        "quick": "Questionnaire design is a multi-step process aimed at collecting usable data with a survey that is easy to understand and complete, reducing dropout and inaccurate answers from confusion.",
        "keyIdeas": [
            "A questionnaire collects data through a series of questions or prompts; open-ended yield qualitative detail, closed-ended yield quantitative data.",
            "A questionnaire is often mistaken for a survey: a survey is the entire data-collection process; a questionnaire is one tool within it.",
            "Eight design steps: identify scope; keep it simple; ask only one question at a time; be flexible with options; choose open- vs closed-ended; know your audience; choose the right tool; save personal questions for last.",
            "Avoid double-barrelled questions that address multiple issues at once.",
        ],
        "detail": [
            "Identify the Scope of Your Research: clearly define purpose and topics—this guides the whole design.",
            "Keep It Simple and Know Your Audience: clear language without jargon, tailored to respondents’ comprehension and experience.",
            "Be Flexible with Your Options: include an “other” option when predefined answers may not fit.",
            "Choose Between Open-Ended and Closed-Ended based on whether you need detailed responses or specific, easily analysable data.",
            "Choose the Right Tool (e.g. a reliable survey platform with templates) and place sensitive/demographic questions last so respondents are more comfortable completing the survey.",
        ],
        "sourceQuote": "Avoid double-barrelled questions that address multiple issues at once. Each question should focus on a single topic to ensure clarity and accurate responses.",
        "compare": "Questionnaire vs survey: many people use the terms interchangeably, but a survey refers to the entire process of data collection, which may include a questionnaire as one of its tools.",
        "related": ["2.1.2", "2.2.2", "2.2.3"],
    },
    "2.2.2": {
        "id": "2.2.2",
        "title": "Types of Questions",
        "module": 2,
        "pages": [44],
        "section": "2.2.2",
        "quick": "Common questionnaire question types include open-ended, dichotomous, multiple-choice, scaling (rank order, Likert, semantic differential, Stapel), and pictorial questions.",
        "keyIdeas": [
            "Open-ended: answer in own words; qualitative, detailed, nuanced.",
            "Dichotomous: two choices such as yes/no; binary validation.",
            "Multiple-choice: single- or multi-select from a list (stem, correct answers, incorrect answers, close alternatives, distractors).",
            "Scaling questions use nominal, ordinal, interval, or ratio scales to quantify intensity/frequency.",
            "Pictorial questions use images as choices to boost engagement and reduce overthinking.",
        ],
        "detail": [
            "Scaling subtypes: Rank Order (order items); Likert (attitudes/opinions on a scale, e.g. 1–5); Semantic Differential (bipolar adjectives); Stapel (rate items on a single adjective).",
            "Using varied question types can enhance engagement and yield more comprehensive data.",
        ],
        "sourceQuote": "Utilising various question types in a questionnaire can enhance respondent engagement and yield more comprehensive data.",
        "related": ["2.2.1", "2.2.3", "2.1.2"],
    },
    "2.2.3": {
        "id": "2.2.3",
        "title": "Format of Questionnaire",
        "module": 2,
        "pages": [44, 45],
        "section": "2.2.3",
        "quick": "Questionnaire format covers size, appearance, clarity, sequence, communicability, and span so the instrument stays compact, clear, and engaging.",
        "keyIdeas": [
            "Size: more compact than a schedule; suitable dimensions; ideally not more than two or three pages depending on the research.",
            "Appearance: high-quality paper/printing and an attractive organised layout.",
            "Clarity: short, clear questions; concise precise language without ambiguity.",
            "Sequence: logical order by importance; smooth progression.",
            "Communicability: keep respondents interested and motivated to finish.",
            "Span: brief questions and overall length that minimise dropout.",
        ],
        "detail": [
            "Format rules support the earlier fundamentals of a good questionnaire (brief/uncomplicated, logical order, avoid jargon, control questions, room for answers, brief instructions, good physical appearance).",
        ],
        "sourceQuote": "Ideally, it should not exceed two or three pages, depending on the nature of the research.",
        "compare": "The questionnaire should be smaller than a schedule in size.",
        "related": ["2.2.1", "2.2.2", "2.1.2"],
    },
    "2.3.1": {
        "id": "2.3.1",
        "title": "Sampling Plan",
        "module": 2,
        "pages": [45, 46],
        "section": "2.3.1",
        "quick": "A sampling plan is the framework research projects use to select a representative sample, set sample size, and decide whom/what to question.",
        "keyIdeas": [
            "A sample is a group of people, objects, or items selected for measurement from a larger population and should be representative to support generalisation.",
            "Definitions cited: Bryman & Bell — “Segment of population that is selected for investigation”; Cooper & Schindler — “Some of the elements of population.”",
            "Three plan decisions: choose the population; determine the sample size; decide the sampling procedure.",
            "In general, “the larger the sample size, the more is the reliability”; probability sampling is commonly used so every object has an equal chance of being picked.",
        ],
        "detail": [
            "Purpose of sampling: apply inferential statistics to a subset to learn about and extrapolate to the whole population—because studying entire populations is rarely practical or cost-effective.",
            "Reasons to sample include large populations, inaccessibility (e.g. prisoners, severe mental illness, disaster survivors), destructiveness of observation (e.g. testing all fuses would destroy them), and sometimes greater accuracy from a carefully selected sample than a poorly identified census.",
        ],
        "sourceQuote": "The phrase “sampling plan” describes the framework that research projects rely on to carry out their investigations.",
        "example": "Destructiveness: a fuse must be destroyed to determine whether it is defective—testing every fuse would destroy the entire stock.",
        "related": ["2.3.2", "2.3.3", "2.3.4"],
    },
    "2.3.2": {
        "id": "2.3.2",
        "title": "Sampling Frame",
        "module": 2,
        "pages": [46, 47],
        "section": "2.3.2",
        "quick": "A sampling frame is a list or database from which a sample can be drawn—in market research, a database of potential respondents who can be invited to a project.",
        "keyIdeas": [
            "The sampling process steps listed: classify the people; ascertain the sample interval; choose sampling strategy; pick a number for the sample; complete the sampling procedure.",
            "Earlier module steps also stress defining the population and choosing a sampling frame (list/database of population members) before selecting method and size.",
        ],
        "detail": [
            "Choosing the sampling frame is a core early step after defining the population: create a list or database of population members from which units are selected.",
        ],
        "sourceQuote": "A sampling frame is a list or database from which a sample can be used.",
        "related": ["2.3.1", "2.3.3", "2.3.4"],
    },
    "2.3.3": {
        "id": "2.3.3",
        "title": "Sample Selection Methods",
        "module": 2,
        "pages": [47, 48, 49],
        "section": "2.3.3",
        "quick": "Sample selection methods are broadly probability sampling (known chance of selection) and non-probability sampling (used for convenience/simplicity but without the same bias-reduction advantages).",
        "keyIdeas": [
            "Probability methods: simple random, systematic, stratified, and cluster sampling.",
            "Simple random: each element has equitable probability of selection; eliminates bias but may chance-select unrepresentative categories.",
            "Systematic: randomise first item then take every nth thereafter; researcher sets the interval.",
            "Stratified: random selection within pre-established groups relevant to the research; division into strata can raise bias risk.",
            "Cluster: randomly select groupings (e.g. postal codes, academic years); may study whole cluster or two-stage select within cluster.",
            "Non-probability: convenience, quota, purposive/judgement, snowball/referral—convenient but introduce considerable bias risks.",
        ],
        "detail": [
            "Convenience sampling selects accessible willing participants (e.g. students on campus)—useful preliminarily but biased.",
            "Quota sampling seeks proportional subgroup representation (like stratified aims) but selection/volunteer bias can skew results.",
            "Purposive/judgement sampling selects based on researcher expertise/objectives—fast variety of replies but unlikely to represent the whole population.",
            "Snowball/referral: participants recruit acquaintances—useful when the target group is hard to reach, but excludes isolates and favours networked interest groups.",
        ],
        "sourceQuote": "The sample selection methods can be broadly classified into:",
        "example": "Stratified travel-pattern study: distinguish those with car access from those who rely on public transportation.",
        "compare": "Probability methods give known (often equal) selection chances and better bias control; non-probability methods trade that for convenience or purposive reach.",
        "related": ["2.3.4", "2.3.5", "2.3.1"],
    },
    "2.3.4": {
        "id": "2.3.4",
        "title": "Probability Sampling Techniques",
        "module": 2,
        "pages": [49, 50, 51],
        "section": "2.3.4",
        "quick": "Probability sampling techniques include simple random, systematic, stratified, cluster, and multistage sampling, each giving population members a known chance of selection.",
        "keyIdeas": [
            "Simple random: known and equal probability of selection for each constituent; P = sample size / population size.",
            "Systematic: use a predetermined skip interval on a sample frame; k = N/n.",
            "Stratified: split population into distinct strata and draw random samples from each.",
            "Cluster: divide into small subgroups and randomly select some groups for study.",
            "Multistage sampling is listed among the probability methods.",
        ],
        "detail": [
            "AMITY example for simple random: population 591 students, sample 25 → probability of selection = 25/591 ≈ 0.042 or 4.2%.",
            "Same population/sample for systematic: skip interval k = 591/25 ≈ 23.64 → 23; pick a random start between 1–23, then every 23rd remaining unit.",
            "Stratified example uses programme subgroups (MBA, MMM, MPM, DBM, DIEM, MCA, MCM) within a 591-student population for a sample of 25.",
            "Cluster example randomly selects whole programme groups (e.g. MCM = 30 and MMM = 42) rather than individuals across all groups.",
        ],
        "sourceQuote": "There is a known and equal probability of selection for each constituent of the population in this probability sample.",
        "example": "Population = 591 AMITY students, sample size = 25 → selection probability 25/591 = 4.2%; systematic skip interval ≈ 23.",
        "related": ["2.3.3", "2.3.5", "2.3.2"],
    },
    "2.3.5": {
        "id": "2.3.5",
        "title": "Non-Probability Sampling Techniques",
        "module": 2,
        "pages": [52],
        "section": "2.3.5",
        "quick": "Non-probability sampling (also called deliberate, purposeful, or judgement sampling) selects elements by the researcher’s choice with no guarantee of equal chance of inclusion.",
        "keyIdeas": [
            "Convenience: any readily available individuals; cheapest and easiest; least reliable.",
            "Purposive/judgmental: units purposely selected to criteria/objectives; suitable for constrained groups but not wider representation.",
            "Quota: purposive sampling stratified by relevant characteristics to increase representativeness (illustrated with programme quotas summing to sample 25 of 591).",
            "Snowball: subsequent participants referred by current sample elements—initial cases refer similar others, accumulating like a snowball.",
        ],
        "detail": [
            "There is no guarantee each element gets an equal chance to be chosen.",
            "Quota illustration assigns counts by programme share (e.g. MBA 46% → 12 of 25) across MBA/MMM/MPM/DBM/DIEM/MCA/MCM totaling 591.",
        ],
        "sourceQuote": "Also known as ‘deliberate,’ ‘purposeful,’ or ‘judgement’ sampling. The items have been chosen with care.",
        "example": "Snowball: initial individuals are identified, then refer others similar to them, and so on.",
        "compare": "Unlike probability techniques, non-probability methods do not guarantee equal selection chance and are generally less reliable for population inference.",
        "related": ["2.3.3", "2.3.4", "2.3.6"],
    },
    "2.3.6": {
        "id": "2.3.6",
        "title": "Sampling and Non-Sampling Errors",
        "module": 2,
        "pages": [53],
        "section": "2.3.6",
        "quick": "Sampling error is discrepancy between sample and population due only to which observations were chosen; non-sampling errors arise from data-acquisition mistakes or incorrect sample observation selection and are more serious.",
        "keyIdeas": [
            "Expanding sample size diminishes sampling error.",
            "Non-sample errors classify as non-response error and response error.",
            "Non-response: selected units fail to provide a complete or partial answer.",
            "Response/data error: consistent bias in collection, analysis, or interpretation.",
            "Response-error sources: respondent error (lying, forgetting), interviewer errors, recording errors, poorly designed questionnaires, measurement errors.",
        ],
        "detail": [
            "Module introduction also flags sampling bias (systematic exclusion/overrepresentation), non-response skew, and sampling error as gaps between sample results and population characteristics.",
        ],
        "sourceQuote": "Sampling error pertains to discrepancies between the sample and the population only due to the particular observations chosen for the sample.",
        "compare": "Sampling error shrinks with larger samples; non-sampling errors are more serious and stem from acquisition/process problems rather than chance selection alone.",
        "related": ["2.3.1", "2.3.3", "2.1.3"],
    },
}


def _q(qid, concept_id, stem, options, correct, explanation, pages=None):
    return {
        "id": qid,
        "conceptId": concept_id,
        "module": 2,
        "stem": stem,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "pages": pages or CONCEPTS[concept_id]["pages"],
    }


QUESTIONS = [
    _q(
        "m2-2.1.1-q1",
        "2.1.1",
        "Which of the following is a primary source of data?",
        ["Internet research", "Company reports", "Surveys", "Newspaper articles"],
        2,
        "Surveys are listed as first-hand/primary data; internet research, company reports, and newspaper articles are secondary examples.",
        [33, 54],
    ),
    _q(
        "m2-2.1.1-q2",
        "2.1.1",
        "What is a key characteristic of primary data?",
        [
            "It is always free to access",
            "It is collected specifically for the current research purpose",
            "It is usually less reliable than secondary data",
            "It is always quantitative",
        ],
        1,
        "Primary data is gathered with a specific goal for the current study; the material notes it is usually more expensive/time-consuming but purpose-specific.",
        [33, 54],
    ),
    _q(
        "m2-2.1.1-q3",
        "2.1.1",
        "A company wants market size for women’s apparel in India. According to the material, which approach fits?",
        [
            "Only primary focus groups are acceptable",
            "Secondary data such as industry reports and newspaper articles",
            "Only schedules filled by enumerators",
            "Only cluster sampling of retail stores",
        ],
        1,
        "The text says market size can be estimated from secondary industry reports and newspaper articles, while new fabric/style preferences need primary research.",
    ),
    _q(
        "m2-2.1.2-q1",
        "2.1.2",
        "How does the schedule method differ from the questionnaire method?",
        [
            "Schedules are always mailed; questionnaires never are",
            "Enumerators fill out schedules, whereas respondents complete questionnaires independently",
            "Schedules use only open-ended items",
            "Questionnaires must be completed face-to-face by an interviewer",
        ],
        1,
        "The material states enumerators designated for the purpose fill out schedules—a key distinction from questionnaires completed by respondents.",
    ),
    _q(
        "m2-2.1.2-q2",
        "2.1.2",
        "According to Prof. Bowley (as cited), how should secondary data be treated?",
        [
            "Always preferred over primary data",
            "Accepted at face value if issued by government",
            "Not accepted at face value without scrutiny",
            "Used only when primary data is quantitative",
        ],
        2,
        "Bowley is quoted: secondary data should not be accepted at their face value; reliability, suitability, and adequacy must be checked.",
    ),
    _q(
        "m2-2.1.2-q3",
        "2.1.2",
        "In participant observation, what does the observer do?",
        [
            "Remains completely detached from the group",
            "Becomes more or less a member of the group being observed",
            "Only uses laboratory controls",
            "Never records behaviour",
        ],
        1,
        "Participant observation: the observer becomes more or less a member of the observed group; non-participant remains detached.",
    ),
    _q(
        "m2-2.1.3-q1",
        "2.1.3",
        "What is tabulation of data primarily described as?",
        [
            "Deleting all incomplete cases from a survey",
            "Arranging structured data into a tabular format of rows and columns",
            "Interviewing experts until consensus is reached",
            "Drawing every nth unit from a list",
        ],
        1,
        "Tabulation is arranging structured numerical data in rows and columns to ease comparison and statistical analysis.",
    ),
    _q(
        "m2-2.1.3-q2",
        "2.1.3",
        "As defined via UNECE 2013 in the material, data validation aims to verify that:",
        [
            "Every respondent completed an interview",
            "A data item’s value comes from the set of acceptable values",
            "The sample equals the population",
            "Only qualitative data were collected",
        ],
        1,
        "Validation checks whether a data item’s value belongs to the given (finite or infinite) set of acceptable values.",
    ),
    _q(
        "m2-2.1.3-q3",
        "2.1.3",
        "Which type of validity concerns whether study findings can be generalised to other settings, populations, or times?",
        ["Internal validity", "Construct validity", "External validity", "Face validity"],
        2,
        "External validity is the extent to which findings generalise to other settings, populations, or times (including population and ecological validity).",
    ),
    _q(
        "m2-2.2.1-q1",
        "2.2.1",
        "Which step in constructing a questionnaire involves defining the purpose and topics?",
        [
            "Keep It Simple",
            "Identify the Scope of Your Research",
            "Be Flexible with Your Options",
            "Know Your Audience",
        ],
        1,
        "Identify the Scope of Your Research means clearly defining purpose and topics to guide the whole design.",
        [43, 54],
    ),
    _q(
        "m2-2.2.1-q2",
        "2.2.1",
        "When designing a questionnaire, why is it important to avoid double-barrelled questions?",
        [
            "They require complex language",
            "They are too short",
            "They address multiple issues at once",
            "They only offer open-ended responses",
        ],
        2,
        "Double-barrelled questions address multiple issues at once; each question should focus on a single topic.",
        [43, 54],
    ),
    _q(
        "m2-2.2.1-q3",
        "2.2.1",
        "Why should sensitive or demographic questions be placed at the end of a questionnaire?",
        [
            "To ensure the survey is concise",
            "To make respondents more comfortable completing the survey",
            "To prioritize the most important questions",
            "To allow for better statistical analysis",
        ],
        1,
        "Saving personal questions for last increases completion likelihood because respondents are more comfortable by the end.",
        [44, 55],
    ),
    _q(
        "m2-2.2.2-q1",
        "2.2.2",
        "Which question type typically offers only two choices such as “yes” or “no”?",
        ["Open-ended", "Dichotomous", "Likert scale", "Pictorial"],
        1,
        "Dichotomous questions are close-ended with two choices (e.g. yes/no) for binary responses.",
    ),
    _q(
        "m2-2.2.2-q2",
        "2.2.2",
        "Likert scale questions are classified in the material under which broader type?",
        ["Open-ended only", "Dichotomous only", "Scaling questions", "Pictorial questions"],
        2,
        "Scaling questions include Rank Order, Likert, Semantic Differential, and Stapel scales.",
    ),
    _q(
        "m2-2.2.2-q3",
        "2.2.2",
        "What is distinctive about pictorial questions?",
        [
            "They must be filled by enumerators",
            "Answer choices are images instead of text",
            "They always use bipolar adjectives",
            "They forbid multiple selection",
        ],
        1,
        "Pictorial questions are like multiple-choice but use images as answer choices to enhance engagement.",
    ),
    _q(
        "m2-2.2.3-q1",
        "2.2.3",
        "Regarding size, how should a questionnaire ideally compare to a schedule?",
        [
            "It should be larger than a schedule",
            "It should be smaller/more compact than a schedule",
            "Size rules are identical",
            "It must always exceed ten pages",
        ],
        1,
        "Under Size/Compactness, the questionnaire should be smaller than a schedule.",
    ),
    _q(
        "m2-2.2.3-q2",
        "2.2.3",
        "What page limit does the material suggest for a questionnaire, depending on the research?",
        [
            "One page only in all cases",
            "Ideally not more than two or three pages",
            "At least ten pages for validity",
            "No limit is mentioned",
        ],
        1,
        "Page Limit: ideally it should not exceed two or three pages, depending on the nature of the research.",
    ),
    _q(
        "m2-2.2.3-q3",
        "2.2.3",
        "Which format principle addresses keeping respondents interested and motivated to finish?",
        ["Span only", "Communicability", "Skip interval", "Cluster selection"],
        1,
        "Communicability: design questions to keep respondents interested and motivated to complete the questionnaire.",
    ),
    _q(
        "m2-2.3.1-q1",
        "2.3.1",
        "Which decisions does the sampling plan encompass, in order emphasised by the material?",
        [
            "Only statistical software choice",
            "Choose population, determine sample size, decide sampling procedure",
            "Only tabulation and validation",
            "Only open- vs closed-ended wording",
        ],
        1,
        "The plan covers choosing the population, determining sample size, and deciding the sampling procedure.",
    ),
    _q(
        "m2-2.3.1-q2",
        "2.3.1",
        "Why might quality-control testing of fuses require sampling rather than a full census?",
        [
            "Fuses cannot be listed in a sampling frame",
            "Observing the desired characteristic destroys the product for its intended use",
            "Probability sampling is illegal for manufactured goods",
            "Secondary data cannot describe products",
        ],
        1,
        "Destructiveness of observation: a fuse must be destroyed to test quality—testing all would destroy all.",
    ),
    _q(
        "m2-2.3.1-q3",
        "2.3.1",
        "According to the material’s general rule about sample size and reliability:",
        [
            "Smaller samples are always more reliable",
            "Sample size is unrelated to reliability",
            "The larger the sample size, the more is the reliability",
            "Only quota samples are reliable",
        ],
        2,
        "Researchers endeavour to cover a wide number of samples because generally “the larger the sample size, the more is the reliability.”",
    ),
    _q(
        "m2-2.3.2-q1",
        "2.3.2",
        "What is a sampling frame?",
        [
            "The final published research report",
            "A list or database from which a sample can be drawn",
            "Only the non-response rate",
            "A type of Likert scale",
        ],
        1,
        "A sampling frame is a list or database from which a sample can be used / potential respondents invited.",
    ),
    _q(
        "m2-2.3.2-q2",
        "2.3.2",
        "Which of the following appears among the listed steps in the sampling process?",
        [
            "Calculate impact factor of a journal",
            "Ascertain the sample interval",
            "Write footnotes only",
            "Run ANOVA for random effects",
        ],
        1,
        "Listed steps include classify the people, ascertain the sample interval, choose sampling strategy, pick sample number, and complete the procedure.",
    ),
    _q(
        "m2-2.3.2-q3",
        "2.3.2",
        "In market research terms, a sampling frame is described as:",
        [
            "The final consensus forecast from Delphi experts",
            "A database of potential respondents that can be drawn from to invite participation",
            "Only unpublished biographies",
            "The skip interval k alone",
        ],
        1,
        "In market research terms, a sampling frame is a database of potential respondents that can be drawn from to invite to a given research project.",
    ),
    _q(
        "m2-2.3.3-q1",
        "2.3.3",
        "Simple random sampling is best described as ensuring:",
        [
            "Only volunteers are included",
            "Each element has an equitable probability of being chosen",
            "Every nth unit after a fixed start with no random start",
            "Researchers pick experts by judgement only",
        ],
        1,
        "Simple random sampling gives each population element an equitable probability of selection (e.g. drawing names/numbers).",
    ),
    _q(
        "m2-2.3.3-q2",
        "2.3.3",
        "In systematic sampling, after randomly selecting the first item, what happens next?",
        [
            "All remaining items are chosen by convenience",
            "Subsequent items are picked using a predetermined interval (every nth)",
            "Only strata leaders are interviewed",
            "Respondents recruit their acquaintances",
        ],
        1,
        "Systematic sampling randomly selects the first item, then applies a rule to choose every nth thereafter.",
    ),
    _q(
        "m2-2.3.3-q3",
        "2.3.3",
        "Snowball (referral) sampling is especially advantageous when:",
        [
            "Every population member has a known equal selection probability",
            "The researcher has limited knowledge of / access to the target group",
            "Skip intervals must be calculated from N/n",
            "Only laboratory observation is allowed",
        ],
        1,
        "Snowball helps when the researcher knows little about the target group and lacks convenient means to reach them—while introducing network bias.",
    ),
    _q(
        "m2-2.3.4-q1",
        "2.3.4",
        "If population size is 591 and sample size is 25 under simple random sampling, selection probability is:",
        ["591/25", "25/591 (about 4.2%)", "Always 50%", "n − 1"],
        1,
        "Probability of selection = sample size / population size = 25/591 ≈ 0.042 or 4.2%.",
    ),
    _q(
        "m2-2.3.4-q2",
        "2.3.4",
        "For systematic sampling with N = 591 and n = 25, the material’s skip interval k is approximately:",
        ["5", "23", "591", "25/591"],
        1,
        "Skip interval k = N/n = 591/25 ≈ 23.64, taken as 23; then random start 1–23 and every 23rd thereafter.",
    ),
    _q(
        "m2-2.3.4-q3",
        "2.3.4",
        "Cluster sampling, as illustrated, selects:",
        [
            "Only one demographic question at the end",
            "Entire subgroups/groups randomly (e.g. programme groups) rather than individuals across all units",
            "Only yes/no items",
            "Secondary data exclusively",
        ],
        1,
        "Cluster sampling divides the population into subgroups and randomly selects some groups (example: MCM and MMM selected from programme groups).",
    ),
    _q(
        "m2-2.3.5-q1",
        "2.3.5",
        "Convenience sampling is characterised in the material as:",
        [
            "Most expensive and most reliable",
            "Cheapest and easiest to conduct, but least reliable",
            "Guaranteeing equal selection probability",
            "Identical to stratified random sampling",
        ],
        1,
        "Convenience sampling uses readily available individuals: cheapest & easiest, least reliable.",
    ),
    _q(
        "m2-2.3.5-q2",
        "2.3.5",
        "Quota sampling is described as a purposive approach that:",
        [
            "Destroys every sampled unit",
            "Uses relevant characteristics to stratify samples and increase representativeness",
            "Requires skip interval k = N/n",
            "Only uses pictorial questions",
        ],
        1,
        "Quota sampling is purposive sampling where relevant characteristics stratify the sample to increase representativeness.",
    ),
    _q(
        "m2-2.3.5-q3",
        "2.3.5",
        "Non-probability sampling is also known in the material as:",
        [
            "Simple random sampling only",
            "Deliberate, purposeful, or judgement sampling",
            "Multistage cluster with equal probability",
            "Time-series smoothing",
        ],
        1,
        "Also known as ‘deliberate,’ ‘purposeful,’ or ‘judgement’ sampling—items chosen with care by the researcher.",
    ),
    _q(
        "m2-2.3.6-q1",
        "2.3.6",
        "How can sampling error be diminished, according to the material?",
        [
            "By using only snowball sampling",
            "By expanding the sample size",
            "By never using a sampling frame",
            "By accepting secondary data at face value",
        ],
        1,
        "Expanding the sample size will diminish sampling error (discrepancy due to which observations were chosen).",
    ),
    _q(
        "m2-2.3.6-q2",
        "2.3.6",
        "Non-sampling errors are classified into:",
        [
            "Only Type I and Type II errors",
            "Non-response error and response error",
            "Only construct and face validity",
            "Open-ended and closed-ended error",
        ],
        1,
        "Non-sample errors classify into non-response error and response error.",
    ),
    _q(
        "m2-2.3.6-q3",
        "2.3.6",
        "Which is listed as a source of response error?",
        [
            "Skip interval calculation only",
            "Respondent error such as lying or forgetting",
            "Choosing IMF publications",
            "Using high-quality paper for questionnaires",
        ],
        1,
        "Response errors arise from respondent error (lying, forgetting, etc.), interviewer/recording errors, poor questionnaires, and measurement errors.",
    ),
]


def main() -> None:
    merge_module(
        module_id=MODULE_ID,
        module_title=MODULE_TITLE,
        tree_children=TREE_CHILDREN,
        concepts=CONCEPTS,
        questions=QUESTIONS,
        status="approved",
    )
    print(f"Module 2 concepts: {len(CONCEPTS)}")
    print(f"Module 2 questions: {len(QUESTIONS)}")


if __name__ == "__main__":
    main()
