"""Build/merge CSIT745 v2 Module III (Design of Experiments, Data Collection, Basic Principles)."""
from __future__ import annotations

from merge_util import merge_module

MODULE_ID = "m3"
MODULE_TITLE = "Module III: Data Collection and Experiments"


def C(
    cid: str,
    title: str,
    pages: list[int],
    section: str,
    quick: str,
    key_ideas: list[str],
    detail: list[str],
    source_quote: str,
    related: list[str] | None = None,
    compare: str | None = None,
    example: str | None = None,
) -> dict:
    out = {
        "id": cid,
        "title": title,
        "module": 3,
        "pages": pages,
        "section": section,
        "quick": quick,
        "keyIdeas": key_ideas,
        "detail": detail,
        "sourceQuote": source_quote,
        "related": related or [],
    }
    if compare:
        out["compare"] = compare
    if example:
        out["example"] = example
    return out


def Q(
    qid: str,
    concept_id: str,
    stem: str,
    options: list[str],
    correct: int,
    explanation: str,
    difficulty: str = "medium",
) -> dict:
    assert len(options) == 4 and 0 <= correct <= 3
    return {
        "id": qid,
        "conceptId": concept_id,
        "module": 3,
        "stem": stem,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "difficulty": difficulty,
    }


CONCEPTS = {
    "3.1.1": C(
        "3.1.1",
        "Design of Experiment: Objectives and Strategies",
        [57, 58, 59],
        "3.1.1",
        "Experimental design aims to maximise knowledge in the least time by establishing a causal link between independent and dependent variables under control, randomisation, and careful factor planning.",
        [
            "Success means a change in the dependent variable is wholly due to a change in the independent variable.",
            "Drivers of success: control group, experimental group, manipulable variable, and random allocation.",
            "Strategy steps include defining the problem, listing factors, identifying major factors, quantifying effects, estimating effect size D vs measurement precision s, checking linearity and interactions, setting limits, and choosing a design matrix.",
            "Type 1 error: claiming an effect that does not exist; Type 2 error: missing a genuine effect.",
            "Rule of thumb for trials per level: n = 16 · s²/D², then compare means with a significance test.",
        ],
        [
            "Experimental research keeps one set of variables constant while measuring another, and is used when information is insufficient to draw conclusions without testing. The text stresses control vs experimental groups, researcher-controlled manipulable variables, and random allocation.",
            "Experts design experiments by defining the problem and desired characteristics, listing all potential factors (illustrated with glass-bottle manufacture), identifying major factors without oversimplifying, quantifying effects numerically (e.g. experience levels 1–3), estimating anticipated impacts D relative to measurement accuracy s, assessing linearity, spotting variable interactions, setting feasible limits, and applying an appropriate design matrix.",
            "Averages of several measurements are more reliable than few; more information up front reduces final design effort. The glass annealing example shows that a 1°C/min cooling-rate change may shift strength 5–20%, and interactions with cullet/alumina can reverse the direction of that effect.",
        ],
        "The objective of experimental design is to get a maximum amount of knowledge in the least amount of time.",
        related=["3.1.4", "3.1.5", "3.3.2"],
        example="To detect a 10°C annealing-point drop (D=10) with precision s=5°C, the text calculates 4 experiments per glass composition before comparing means.",
    ),
    "3.1.2": C(
        "3.1.2",
        "Pre-Experimental Research Design",
        [59],
        "3.1.2",
        "Pre-experimental design is the most basic experimental study form: after positing cause and effect, one or more groups are monitored continuously, often to decide whether further inquiry is needed.",
        [
            "Most basic sort of experimental study design.",
            "Used after establishing a cause–effect link to continuously monitor group(s).",
            "Typically performed to decide if more inquiry is necessary.",
            "Described as cost-effective.",
        ],
        [
            "Pre-experimental designs sit at the simple end of the experimental spectrum in the module. They monitor groups continuously after a cause–effect framing and are often a cheap screen for whether deeper study is warranted.",
            "The extract’s example is a teacher using a new instructional method for their class—exposure without the full apparatus of true experiments.",
        ],
        "The most basic sort of experimental study design",
        related=["3.1.3", "3.1.4"],
        compare="Unlike true experimental design, pre-experimental work is not presented as establishing a precise cause–effect link via statistical hypothesis tests and random assignment.",
        example="A teacher using a new instructional method for their class.",
    ),
    "3.1.3": C(
        "3.1.3",
        "Quasi-Experimental Research Design",
        [60],
        "3.1.3",
        "Quasi-experimental design resembles true experiments but lacks a control group and/or random assignment; it is used when random assignment is not relevant or unnecessary.",
        [
            "Resembles true experimental research but is not the same.",
            "The control group is missing (as characterised in the extract).",
            "Participants are not assigned randomly.",
            "Employed when random assignment is not relevant or unnecessary.",
        ],
        [
            "Quasi-experiments look like experiments but omit key true-experiment features. The module highlights missing control groups and non-random assignment as defining gaps.",
            "Example: two homogeneous cohorts in separate schools—one exposed to a new programme, the other serving as a comparison group without random allocation within a shared pool.",
        ],
        "This method is employed when random assignment is either not relevant or unnecessary.",
        related=["3.1.2", "3.1.4"],
        compare="True experimental design can establish cause–effect and relies on statistical analysis; quasi-experimental designs are used when random assignment is not feasible.",
        example="Two homogeneous cohorts at separate schools: one gets a new programme, the other acts as control without random assignment.",
    ),
    "3.1.4": C(
        "3.1.4",
        "True Experimental Research Design",
        [60],
        "3.1.4",
        "True experimental design is the most precise experimental form: it uses statistical analysis to test hypotheses and is the only type said here to establish a cause–effect link within a group or few groups.",
        [
            "Most precise kind of experimental research design.",
            "Relies on statistical analysis to validate or invalidate a hypothesis.",
            "Only type capable of establishing a cause–effect link within a group or few groups (per the extract).",
            "Commonly used in the physical sciences.",
        ],
        [
            "Among pre-, quasi-, and true experimental designs, the module positions true experiments as the precise, statistics-backed route to causal claims inside studied groups.",
            "It contrasts with pre-experimental (basic monitoring) and quasi-experimental (no random assignment / missing control) designs earlier in §3.1.",
        ],
        "The most precise kind of experimental research design",
        related=["3.1.2", "3.1.3", "3.1.1"],
    ),
    "3.1.5": C(
        "3.1.5",
        "Factorial Experimental Design",
        [60, 61],
        "3.1.5",
        "Factorial design examines several factors at once, estimating each factor’s main effect and their combined (interaction) effects.",
        [
            "Simultaneously examines several factors.",
            "Measures individual-factor impact and combined effects of variables.",
            "Department-store example: price levels × POP display locations yield 2×3 = 6 treatment combinations.",
            "Random allocation of combinations to store groups supports reading main effects and interactions from sales outcomes.",
        ],
        [
            "A chain considering price cuts and point-of-purchase (POP) placement (entrance vs usual place, plus a third POP type in the combinatorial setup) creates six combinations (R1P1…R3P2). With 120 stores in groups of 20, combinations are assigned randomly and sales S1–S6 are compared.",
            "The design answers whether discounted price beats standard price, whether entrance display beats customary location, and what the interaction of price and display does to sales.",
        ],
        "Factorial design allows the researcher to simultaneously examine several factors.",
        related=["3.1.1", "3.1.6"],
        example="Price (usual vs lowered) × three POP placements → six combinations randomly assigned across store groups.",
    ),
    "3.1.6": C(
        "3.1.6",
        "Designing Engineering Experiments",
        [61, 62],
        "3.1.6",
        "Engineering experiments use statistically designed tests—often sequential screening, refinement, then optimisation—to improve processes and products while analysing data impartially.",
        [
            "Concrete-curing example: compare techniques on compressive strength; two levels → two-sample methods/t-test; more levels need single-factor designs.",
            "Structured experiments identify which process variables (temperature, pressure, rate) most affect performance.",
            "Outcomes: enhanced procedures, reduced variation, shorter development, lower operating cost.",
            "Typical sequence: screening → refine critical variables → optimise levels.",
            "Activity cycle: conjecture → experiment → analysis → conclusion (often leading to a revised hypothesis).",
        ],
        [
            "The civil-engineer curing study shows how specimen tests and OC curves guide sample size, with t-tests for two methods and broader single-factor designs for five curing techniques.",
            "Statistically based designs improve manufacturing processes and new-product engineering (materials, design parameters, critical characteristics). Sequential experiments start with many controllable variables, then focus, then optimise.",
            "Poorly designed trials waste resources; planned experiments plus statistical analysis support efficiency and scientific impartiality in conclusions.",
        ],
        "Every experiment involves a sequence of activities like as:",
        related=["3.1.1", "3.1.5", "3.3.2"],
    ),
    "3.1.7": C(
        "3.1.7",
        "Causal Attributions",
        [62, 63, 64, 65],
        "3.1.7",
        "Causal attribution (causal contribution/inference) ascribes observed changes to a specific intervention; OECD-DAC impact evaluation requires identifying causes without claiming the programme is the sole cause.",
        [
            "OECD-DAC: ascription of a causal link between observed (or expected) changes and a specific intervention.",
            "Need not be exclusive causation—other programmes or contextual ‘external factors’ may contribute.",
            "Modes: sole attribution (necessary and sufficient—rarely realistic); joint attribution with other programmes/context; alternative/multiple causal paths.",
            "Three approaches: estimate the counterfactual; check coherence of theory-of-change evidence while ruling out rivals; combine methods.",
            "Synthesising multiple impact evaluations strengthens generalisability beyond a single study.",
        ],
        [
            "Impact evaluation must go beyond describing change to attributing how programmes/policies contributed. Joint attribution is the typical practical case: effects appear only with favourable conditions (e.g. funding transparency).",
            "Alternative paths appear when other providers can achieve the same outcome (nutrition, waterborne-disease control, immunisation all targeting infant mortality). Counterfactual designs then need data on services non-participants use.",
            "Key highlights: attribution examines causal connections; methods improve when grounded in a robust theory of causality; choice depends on assessment environment and subject.",
        ],
        "Causal attribution, as defined by the OECD-DAC, refers to the process of determining the cause or causes of a certain event or outcome: \u201cAscription of a causal link between observed (or expected to be observed) changes and a specific intervention.\u201d",
        related=["3.1.1", "3.1.4"],
        compare="Sole causal attribution treats the programme as necessary and sufficient; joint attribution and alternative paths allow other programmes or contexts to share or replace the causal role.",
    ),
    "3.1.8": C(
        "3.1.8",
        "Statistical Control",
        [65, 66, 67, 68],
        "3.1.8",
        "Statistical control is exercised mainly through control charts that plot process data over time so decision-makers can act on common vs special cause signals.",
        [
            "Charts are useful only if decision-makers act on what they show.",
            "Variable charts: X̄–R, median–R, X̄–S, individuals–moving range; attribute charts: p, np, c, u.",
            "Prerequisites: management support, process understanding, critical characteristics (Pareto), defined measurement system, chart-type choice, sample size/frequency.",
            "Attributes suit visual/impossible measurement, costly tests, many characteristics, or 100% inspection; variables when critical precision is needed (common n=5).",
            "In control if only common causes; out of control if special causes present. Control limits are ±3σ for the sample statistic.",
        ],
        [
            "A control chart is a monitoring plot: vertical scale for the statistic, horizontal for time/sequence. Efficacy depends on correct use, not the chart alone.",
            "Before charting: understand the process, pick characteristics that matter (Pareto), calibrate the measurement system, choose chart type for cost/risk, and set economically sensible subgroup sizes (attributes often n=30–hundreds).",
            "Development steps include headers, sample logging, computed statistics, scales, plotting centre lines (solid) and control limits (dashed), then interpretation. Population-based limits for averages mislead—limits follow sampling distributions of averages.",
        ],
        "Statistical control mostly occurs through the use of several control charts, which give essential information that acts as a foundation for taking appropriate actions.",
        related=["3.1.6", "3.3.2"],
    ),
    "3.2.1": C(
        "3.2.1",
        "Collection of Data via Observation and Interview",
        [68, 69],
        "3.2.1",
        "Observation becomes scientific when it serves a research purpose, is systematically planned and recorded, and is checked for validity and reliability; interviewing gathers oral-verbal responses, usually face-to-face.",
        [
            "Participant observation: observer joins the group with defined units, standardised conditions, systematic recording, and selection of pertinent data.",
            "Non-participant observation: no involvement in group activities; lacks the systematic traits of participant observation.",
            "Interview types: structured, unstructured, clinical, non-directive, and focused.",
            "Structured interviews use predetermined questions and standardised recording for consistency/comparability.",
        ],
        [
            "Data collection is framed as obtaining precise information from varied sources to assess outcomes, trends, and probabilities. Observation and interview are two primary primary-collection routes in this section.",
            "Structured vs unstructured interviewing trades standardisation for conversational flexibility. Clinical interviews probe underlying motivations/life course; non-directive interviews minimise direct questioning; focused interviews confine talk to a given experience and its effects.",
        ],
        "Observation becomes a scientific tool and method of data collection when it serves a formulated research purpose, is systematically planned and recorded, and is subjected to checks and controls for validity and reliability.",
        related=["3.2.2", "3.2.3", "3.3.1"],
        compare="Participant observation embeds the observer in the group with systematic controls; non-participant observation stays outside and lacks those systematic characteristics.",
    ),
    "3.2.2": C(
        "3.2.2",
        "Collection of Data through Cases",
        [69, 70],
        "3.2.2",
        "Case-study data collection follows a rigorous sequence: define questions, select cases, gather multi-source evidence, analyse, and present corroborated results.",
        [
            "Identify/define research questions and the research object (person, programme, event, entity).",
            "Select single vs multiple, unique vs typical cases; plan collection, storage, analysis.",
            "Collect from multiple sources; store systematically; seek converging patterns.",
            "Analyse qualitative and quantitative data; address initial propositions; use graphics; involve multiple investigators.",
            "Present with evidence, new insights/conflicts, and structure that lets readers evaluate findings.",
        ],
        [
            "The module insists case researchers use a rigorous approach for neutrality and clarity. Evidence should support converging lines of inquiry rather than a single anecdote.",
            "Presentation must corroborate that all aspects of the problem were explored and highlight conflicting propositions as well as new insights.",
        ],
        "A researcher doing case studies should use a rigorous approach to guarantee neutrality and clarity.",
        related=["3.2.1", "3.2.3"],
    ),
    "3.2.3": C(
        "3.2.3",
        "Collection of Data through Questionnaires",
        [70, 71],
        "3.2.3",
        "Questionnaires are standardised survey items collected mainly by mailing (self-completion with return envelope) or by enumerator (schedule filled by a trained interviewer).",
        [
            "Mailing: questionnaire posted with blank answer space, self-addressed stamped envelope, confidentiality assurance.",
            "Mailing suits large geographic fields and educated, cooperative respondents.",
            "Enumerator method: trained visitor asks questions and records replies (a schedule).",
            "Enumerators should be well-trained, tactful, hard-working, and unbiased; method suits adequate resources and illiterate respondents needing help.",
        ],
        [
            "Questionnaires are fundamental survey instruments of standardised items. The mailing method is common among research workers and agencies when coverage is wide and literacy/cooperation exist.",
            "The enumerator/schedule method trades cost for assistance clarifying questions and accurate recording—typical of government and research institutions with trained staff.",
        ],
        "There are two primary methods for collecting data through questionnaires:",
        related=["3.2.4", "3.2.1"],
        compare="Mailing relies on self-completion by educated respondents over a large field; the enumerator method uses trained staff and suits illiterate respondents when resources allow.",
    ),
    "3.2.4": C(
        "3.2.4",
        "Guidelines for Preparing Questionnaire",
        [71, 72],
        "3.2.4",
        "Questionnaire preparation follows aims → target respondents → clear questions → question types → sequence/layout → pilot testing.",
        [
            "Define research aims and questionnaire goal; reuse or adapt validated instruments when possible.",
            "Define target groups; choose longitudinal vs cross-sectional designs.",
            "Write clear, audience-appropriate, simple-language items.",
            "Choose open (explorative) vs closed/Likert (quantitative) types thoughtfully.",
            "Order questions logically, allow skips, keep layout navigable; run a pilot and analyse pilot data.",
        ],
        [
            "Guidelines stress starting from aims and checking for existing validated tools (especially in psychology) before inventing items.",
            "Targeting includes deciding whether to track change over time or compare groups once. Piloting checks readability, phrasing, arrangement, and whether analytic procedures will work on the resulting data.",
        ],
        "Identify Your Research Aims and the Goal of Your Questionnaire",
        related=["3.2.3", "3.2.5", "3.3.1"],
    ),
    "3.2.5": C(
        "3.2.5",
        "Data Editing",
        [72, 73],
        "3.2.5",
        "Data editing checks and corrects errors, inconsistencies, and omissions so findings rest on accurate, high-quality, credible data.",
        [
            "Techniques: visual inspection, computer verification, double data entry.",
            "Visual inspection catches context errors but is slow and human-error prone.",
            "Computer verification is fast/accurate on volume but needs programming and may miss contextual mistakes.",
            "Double entry compares two independent entries—highly accurate but labour-intensive/costly.",
            "Importance: accuracy, quality (complete/consistent), and research credibility.",
        ],
        [
            "Editing is framed as essential to validity: correcting errors so data reflect research variables, enhancing completeness/consistency, and building stakeholder trust.",
            "Choosing a technique balances cost, scale, and the need for human contextual judgement versus automation.",
        ],
        "Data editing is a critical step in the research process that involves checking and correcting errors, inconsistencies, and omissions in collected data.",
        related=["3.2.6", "3.2.8"],
    ),
    "3.2.6": C(
        "3.2.6",
        "Data Coding Rules",
        [73, 74],
        "3.2.6",
        "Data coding transforms raw data into a structured format so researchers can organise, analyse, and spot patterns, themes, and relationships.",
        [
            "Supports data reduction, organisation, pattern recognition, interpretation/analysis, and comparative analysis.",
            "Qualitative example: theme codes such as product quality, service, pricing, delivery.",
            "Survey example: Likert codes (strongly agree=5 … strongly disagree=1).",
            "Also illustrated for content analysis, medical diagnostic groups, and historical themes/periods.",
        ],
        [
            "Coding condenses large volumes into manageable categories and supplies the foundation for statistical tests and cross-case comparison.",
            "Examples span qualitative themes, numeric survey scales, media stance coding, clinical groupings, and historical document themes—showing coding as a general structuring step, not only a qualitative craft.",
        ],
        "Data coding is a critical step in the research process, involving the transformation of raw data into a structured format.",
        related=["3.2.5", "3.2.7"],
        example="Likert responses coded 5=strongly agree through 1=strongly disagree for quantitative analysis.",
    ),
    "3.2.7": C(
        "3.2.7",
        "Don\u2019t Know Responses",
        [74],
        "3.2.7",
        "“Don’t know” options let uncertain respondents abstain but may become avoidance routes that hurt reliability; use them sparingly and consider “other” or follow-ups instead.",
        [
            "Intent: allow abstention when uncertain.",
            "Risk: respondents choose DK to avoid engaging, compromising reliability.",
            "Mitigations: remove DK, or add follow-ups for richer data.",
            "“Other” helps respondents elaborate (useful for product/service feedback).",
            "DK may suit sensitive topics; for brands/products ensure familiarity before opinion items.",
        ],
        [
            "The section balances response options for survey quality: DK can help on sensitive topics but can distort brand/product ratings if respondents lack experience.",
            "Offering “other” is presented as empowering elaboration and surfacing negative opinions that closed lists might hide.",
        ],
        "The intention behind incorporating \u201cdon\u2019t know\u201d options in surveys is to provide respondents with an opportunity to abstain from questions they\u2019re uncertain about.",
        related=["3.2.4", "3.2.8"],
    ),
    "3.2.8": C(
        "3.2.8",
        "Missing Data",
        [75],
        "3.2.8",
        "Missing data are classified as MCAR, MAR, or MNAR; MNAR biases are non-ignorable, so prevention and secure storage are emphasised.",
        [
            "MCAR: missingness random, unrelated to other factors (e.g. random survey dropouts).",
            "MAR: systematic but explained by observed variables (e.g. age-related privacy non-response).",
            "MNAR: missingness depends on the unobserved values themselves (e.g. low-income respondents omit spending).",
            "MCAR/MAR may be ignorable; MNAR can distort conclusions.",
            "Strategies: user-friendly forms, validation, incentives, limit follow-ups/volume; secure multi-backup storage.",
        ],
        [
            "Missingness threatens representativeness and generalisability. Distinguishing random vs value-dependent mechanisms decides whether bias is ignorable.",
            "The extract’s practical focus is preventing missingness and protecting stored data rather than detailing imputation algorithms.",
        ],
        "While MCAR and MAR data may be considered ignorable, MNAR data introduce non-ignorable biases that can potentially distort conclusions.",
        related=["3.2.5", "3.2.7"],
        compare="MCAR/MAR can be treated as ignorable under the text’s framing; MNAR is non-ignorable because missingness depends on the missing values themselves.",
    ),
    "3.3.1": C(
        "3.3.1",
        "Validity and Reliability",
        [76, 77, 78],
        "3.3.1",
        "Validity is how accurately a technique measures what it should; reliability is stability/consistency—and reliability alone does not guarantee validity.",
        [
            "High validity: results align with real traits/fluctuations; unreliable methods are probably not valid (thermometer analogy).",
            "Construct, content, and criterion validity illustrated; discriminant vs convergent validity as construct subtypes.",
            "Internal reliability/consistency vs external reliability (generalisability beyond the immediate use).",
            "Cronbach’s α: ≥0.9 excellent; 0.7–<0.9 good; 0.6–<0.7 acceptable; 0.5–<0.6 poor; <0.5 unacceptable.",
            "Also: test–retest, parallel forms, Spearman-Brown (split-half), Cohen’s kappa (inter-rater); high-stakes preferred >0.85, low-stakes >0.70.",
        ],
        [
            "Validity types in the extract: construct (ties to theory; self-esteem correlating with social skills/optimism), content (covers all aspects—Bengali test missing listening lacks content validity), criterion (exit poll predicting election). Discriminant validity expects low correlations with unrelated constructs; convergent expects high correlations with similar measures.",
            "Reliability is repeatability (thermometer; math test). Internal consistency asks whether the test measures the intended construct; external reliability asks whether findings generalise (tutoring claim across subjects; depression test across ages/SES).",
            "Coefficient reliability is the proportion of observed-score variance attributable to true scores; Cronbach’s alpha is the most widely used internal-consistency coefficient.",
        ],
        "Validity pertains to the degree of accuracy with which a technique assesses the desired measurement.",
        related=["3.2.4", "3.3.2", "3.3.3"],
        compare="A measure can be reliable yet invalid if it consistently misses the real construct; without reliability, validity is unlikely.",
        example="If a thermometer gives different readings under controlled constant temperature, it is unreliable and its measurements are not valid.",
    ),
    "3.3.2": C(
        "3.3.2",
        "Replication, Randomisation and Blocking",
        [78, 79, 80],
        "3.3.2",
        "Replication judges whether differences exceed chance; randomisation balances unmeasured confounders; blocking groups homogeneous units to cut noise and clarify treatment contrasts.",
        [
            "Without replication you cannot tell chance from real differences (one plant height vs many).",
            "Randomisation assigns units non-deterministically to equalise confounders (e.g. chamber temperature gradient, compost, watering).",
            "Blocks are homogeneous groups that reduce within-block variability and strengthen condition contrasts.",
            "Measuring all controls one day and all treatments another confounds day with treatment—include common conditions to estimate block/batch effects.",
            "Cage example: shared treatments estimate cage effect so unmatched treatments can be adjusted (E − F − cage effect).",
        ],
        [
            "Replication makes differences meaningful relative to within-group fluctuation. Randomisation addresses residual variables after blocks are set (age, sex, genetics in the mouse framing).",
            "Blocking and batch-effect correction keep day/cage structure from masquerading as treatment effects—central to credible experimental design in the module.",
        ],
        "Without replication, it is impossible to judge whether there is an actual difference when comparing situations",
        related=["3.1.1", "3.1.6", "3.3.3"],
        compare="Replication estimates variability; randomisation balances unknown confounders across conditions; blocking deliberately controls known sources of homogeneity.",
    ),
    "3.3.3": C(
        "3.3.3",
        "Orthogonality and False Positives",
        [80, 81, 82],
        "3.3.3",
        "Orthogonality means predictors are uncorrelated (balanced ANOVA cells); a false positive is a positive test result when the true state is negative.",
        [
            "Orthogonal model: independent variables uncorrelated; correlation ⇒ non-orthogonal.",
            "Orthogonal ANOVA: categorical factors with equal cell counts (balanced); near-balance may be treated as effectively orthogonal.",
            "Orthogonal models have a single estimation/testing path; non-orthogonal models need careful interpretation.",
            "Matrix view: vectors orthogonal if sum of element-wise products is zero.",
            "False positive (“false alarm”); related false negative; medical/software examples; false-positive paradox when base rates are low.",
        ],
        [
            "The extract links orthogonality to classical ANOVA balance and contrasts it with general linear models that include continuous covariates. Mild imbalance (10,10,10,9) is technically non-orthogonal but practically minor.",
            "False positives are illustrated with COVID, cancer, prenatal, and antivirus examples; false negatives with pregnancy tests. Design guidelines later stress planning/conducting/analysis loops and interdisciplinary teams, but the leaf’s core definitions are orthogonality and false positives.",
        ],
        "Orthogonality means \u201cuncorrelated.\u201d That means in an orthogonal model; all the independent variables are uncorrelated.",
        related=["3.3.1", "3.3.2", "3.1.5"],
        example="False positive: COVID-19 test positive though the patient is not infected.",
    ),
}


QUESTIONS = [
    # 3.1.1
    Q("m3-3.1.1-q1", "3.1.1",
      "According to the module, experimental research is considered successful when:",
      ["All variables are changed simultaneously",
       "A change in the dependent variable is wholly due to a change in the independent variable",
       "Only qualitative interviews are used",
       "No control group is present"],
      1, "Success requires attributing dependent-variable change wholly to the independent variable.", "easy"),
    Q("m3-3.1.1-q2", "3.1.1",
      "Which set lists factors the extract says drive experimental-research success?",
      ["Literature review, meta-analysis, citation index",
       "Control group, experimental group, manipulable variable, random allocation",
       "Cronbach’s alpha, Cohen’s kappa, Spearman-Brown",
       "Mailing method and enumerator method only"],
      1, "The text lists control/experimental groups, a manipulable variable, and random allocation.", "easy"),
    Q("m3-3.1.1-q3", "3.1.1",
      "In the design strategies, a Type 1 error means:",
      ["Failing to recognise a genuine effect",
       "Mistakenly identifying an effect that does not exist",
       "Using too large a sample",
       "Ignoring measurement precision"],
      1, "Type 1 = false claim of an effect; Type 2 = missing a real effect.", "medium"),
    # 3.1.2
    Q("m3-3.1.2-q1", "3.1.2",
      "Pre-experimental research design is described as:",
      ["The most precise experimental design",
       "The most basic sort of experimental study design",
       "Always requiring random assignment",
       "Identical to factorial design"],
      1, "The extract calls it the most basic experimental study design.", "easy"),
    Q("m3-3.1.2-q2", "3.1.2",
      "A typical reason given for using a pre-experimental design is to:",
      ["Prove causality with full statistical control",
       "Determine whether more inquiry is necessary for the group(s)",
       "Replace all surveys",
       "Estimate Cronbach’s alpha"],
      1, "It is typically performed to see if further inquiry is needed; also called cost-effective.", "easy"),
    # 3.1.3
    Q("m3-3.1.3-q1", "3.1.3",
      "Which statement matches the module’s characterisation of quasi-experimental design?",
      ["It always includes random assignment of participants",
       "It is identical to true experimental design",
       "Participants are not assigned randomly; it is used when random assignment is not relevant or unnecessary",
       "It never uses any comparison group"],
      2, "Quasi-experiments lack random assignment (and the extract notes a missing control group) and are used when randomisation is not relevant/unnecessary.", "medium"),
    Q("m3-3.1.3-q2", "3.1.3",
      "Which example illustrates a quasi-experimental setup in the extract?",
      ["Randomly assigning students within one school to treatment/control",
       "Two homogeneous cohorts in separate schools, one exposed to a new programme",
       "A mailed questionnaire only",
       "An X̄–R control chart"],
      1, "Separate-school cohorts with one programme exposure exemplify quasi-experimental comparison without random assignment.", "easy"),
    Q("m3-3.1.3-q3", "3.1.3",
      "Check-your-understanding in the module: which design is typically used when random assignment is not feasible?",
      ["True experimental", "Pre-experimental only", "Quasi-experimental", "Factorial only"],
      2, "Answer key: quasi-experimental when random assignment is not feasible.", "easy"),
    # 3.1.4
    Q("m3-3.1.4-q1", "3.1.4",
      "True experimental research design is described as:",
      ["Unable to test hypotheses statistically",
       "The most precise kind of experimental research design",
       "Lacking any cause–effect ambition",
       "Limited to questionnaire mailing"],
      1, "It is called the most precise experimental design and relies on statistical analysis.", "easy"),
    Q("m3-3.1.4-q2", "3.1.4",
      "Per the extract, which design alone can establish a cause–effect link within a group or few groups?",
      ["Pre-experimental", "Quasi-experimental", "True experimental", "Purely observational"],
      2, "True experimental design is stated as the only type capable of establishing that cause–effect link.", "medium"),
    # 3.1.5
    Q("m3-3.1.5-q1", "3.1.5",
      "Factorial experimental design primarily allows the researcher to:",
      ["Study only one factor at a time",
       "Simultaneously examine several factors and their combined effects",
       "Avoid measuring sales outcomes",
       "Eliminate the need for any randomisation"],
      1, "Factorial design examines several factors at once, including interactions.", "easy"),
    Q("m3-3.1.5-q2", "3.1.5",
      "In the department-store example with 2 price levels and 3 POP types, how many treatment combinations are listed?",
      ["2", "3", "5", "6"],
      3, "2 × 3 = 6 combinations (R1P1 … R3P2).", "medium"),
    Q("m3-3.1.5-q3", "3.1.5",
      "Besides main effects of price and display, the factorial store trial is said to provide insight into:",
      ["Cronbach’s alpha only",
       "The interaction impact of the two factors",
       "ISBN registration",
       "MCAR missingness only"],
      1, "The research addresses interaction of price and POP placement as well as main effects.", "medium"),
    # 3.1.6
    Q("m3-3.1.6-q1", "3.1.6",
      "The engineering experiment activity sequence listed is:",
      ["Coding → editing → mailing → pilot",
       "Conjecture → experiment → analysis → conclusion",
       "Blocking → orthogonality → false positive",
       "Observation → interview → case only"],
      1, "Conjecture, experiment, analysis, conclusion form the listed cycle.", "easy"),
    Q("m3-3.1.6-q2", "3.1.6",
      "A typical sequential use of designed experiments in engineering is:",
      ["Optimise first, then never screen",
       "Screen many variables, refine critical ones, then optimise levels",
       "Skip analysis after data collection",
       "Use only attribute control charts"],
      1, "Screening → refinement on critical variables → optimisation of levels.", "medium"),
    Q("m3-3.1.6-q3", "3.1.6",
      "If a civil engineer compares only two curing methods on compressive strength, the extract suggests analysis via:",
      ["Only Cronbach’s alpha",
       "Statistical hypothesis methods for two samples / t-test",
       "Snowball sampling only",
       "Sole causal attribution by OECD definition alone"],
      1, "Two curing procedures can use two-sample hypothesis methods and a t-test.", "medium"),
    # 3.1.7
    Q("m3-3.1.7-q1", "3.1.7",
      "OECD-DAC causal attribution is defined as:",
      ["Ignoring all external factors by rule",
       "Ascription of a causal link between observed (or expected) changes and a specific intervention",
       "Computing only Cronbach’s alpha",
       "Plotting an X̄–R chart"],
      1, "Attribution is ascribing a causal link between changes and an intervention.", "easy"),
    Q("m3-3.1.7-q2", "3.1.7",
      "“Joint causal attribution” means:",
      ["The programme alone is always necessary and sufficient",
       "Impacts arise in concert with other programmes/policies or contextual conditions",
       "No theory of change is allowed",
       "Only false positives are studied"],
      1, "Joint attribution covers programme effects together with other programmes or context.", "medium"),
    Q("m3-3.1.7-q3", "3.1.7",
      "Which is NOT listed among the three primary approaches for determining cause of an effect?",
      ["Estimating the counterfactual",
       "Examining coherence of theory-based cause–effect evidence while excluding rivals",
       "Using a combination of those strategies",
       "Relying solely on Cronbach’s alpha thresholds"],
      3, "The three approaches are counterfactual estimation, theory/coherence checking, and combining them—not alpha cutoffs.", "medium"),
    # 3.1.8
    Q("m3-3.1.8-q1", "3.1.8",
      "Statistical control in this module mostly occurs through:",
      ["Only mailing questionnaires",
       "Control charts that inform appropriate actions",
       "Sole causal attribution statements",
       "Removing all “don’t know” options"],
      1, "Statistical control is tied to control charts as a basis for action.", "easy"),
    Q("m3-3.1.8-q2", "3.1.8",
      "Which pair correctly matches chart families in the extract?",
      ["Variables: p, np, c, u; Attributes: X̄–R only",
       "Variables: X̄–R, X̄–S, etc.; Attributes: p, np, c, u",
       "Both families use only individuals–moving range",
       "Attribute charts never use sample size > 20"],
      1, "Variable charts include X̄–R/S and related; attribute charts are p, np, c, u.", "medium"),
    Q("m3-3.1.8-q3", "3.1.8",
      "If only common-cause variability is present, the process is said to be:",
      ["Out of control", "In control", "Non-orthogonal", "MNAR"],
      1, "Common causes only ⇒ in control; special causes ⇒ out of control.", "easy"),
    # 3.2.1
    Q("m3-3.2.1-q1", "3.2.1",
      "Observation becomes a scientific data-collection tool when it:",
      ["Is informal and unrecorded",
       "Serves a formulated purpose, is systematically planned/recorded, and checked for validity and reliability",
       "Always uses mailed questionnaires",
       "Avoids any standardised conditions"],
      1, "Purpose, systematic planning/recording, and validity/reliability checks define scientific observation.", "easy"),
    Q("m3-3.2.1-q2", "3.2.1",
      "A structured interview is characterised by:",
      ["No predetermined questions",
       "Predetermined questions and highly standardised response recording",
       "Only clinical life-history probing",
       "Observer participation in the group"],
      1, "Structured interviews use predetermined questions and standardised recording for consistency.", "easy"),
    Q("m3-3.2.1-q3", "3.2.1",
      "Non-participant observation differs from participant observation in that the observer:",
      ["Always uses predetermined interview schedules",
       "Does not become involved in group activities and lacks participant observation’s systematic characteristics",
       "Must join the group as a full member",
       "Only codes Likert items"],
      1, "Non-participant observation stays outside group activities and lacks those systematic traits.", "medium"),
    # 3.2.2
    Q("m3-3.2.2-q1", "3.2.2",
      "Which is the first step listed for rigorous case-study work?",
      ["Presentation of results only",
       "Identify and define the research questions",
       "Compute control limits",
       "Choose Cronbach’s alpha cutoffs"],
      1, "Case studies begin by identifying/defining research questions and focus.", "easy"),
    Q("m3-3.2.2-q2", "3.2.2",
      "When presenting case-study results, the extract emphasises:",
      ["Hiding conflicting propositions",
       "Corroborating findings with evidence and enabling reader evaluation",
       "Using only one investigator’s private notes",
       "Skipping storage of evidence"],
      1, "Results should be corroborated, show new insights/conflicts, and let readers evaluate evidence.", "medium"),
    # 3.2.3
    Q("m3-3.2.3-q1", "3.2.3",
      "The mailing method of questionnaire collection typically includes:",
      ["A trained enumerator filling a schedule in person only",
       "A posted questionnaire, answer space, self-addressed stamped envelope, and confidentiality assurance",
       "Only participant observation",
       "X̄–R charting of each reply"],
      1, "Mailing uses self-completion with return envelope and confidentiality assurance.", "easy"),
    Q("m3-3.2.3-q2", "3.2.3",
      "The enumerator method is especially suitable when:",
      ["Respondents are educated and the field is huge with no staff",
       "Adequate finance/trained enumerators exist and respondents may be illiterate",
       "Only email attachments are allowed",
       "Randomisation of plants in a growth chamber is required"],
      1, "Enumerator/schedule method suits resourced studies and illiterate respondents needing help.", "medium"),
    Q("m3-3.2.3-q3", "3.2.3",
      "A questionnaire filled out by the enumerator is known as a:",
      ["Control chart", "Schedule", "Block", "False positive"],
      1, "The extract calls the enumerator-completed instrument a schedule.", "easy"),
    # 3.2.4
    Q("m3-3.2.4-q1", "3.2.4",
      "Which guideline comes first in preparing a questionnaire?",
      ["Run a pilot before defining aims",
       "Identify research aims and the questionnaire’s goal",
       "Compute ANOVA orthogonality",
       "Plot attribute control charts"],
      1, "Start by identifying aims/goals (and checking for existing validated tools).", "easy"),
    Q("m3-3.2.4-q2", "3.2.4",
      "A pilot of the questionnaire is used to:",
      ["Skip readability checks",
       "Find issues in understanding/phrasing/layout and see if analytic procedures work",
       "Replace all open questions with DK options",
       "Prove sole causal attribution"],
      1, "Pilots check readability, phrasing, arrangement, feedback, and analytic usability.", "medium"),
    Q("m3-3.2.4-q3", "3.2.4",
      "Choosing longitudinal vs cross-sectional design appears under which guideline step?",
      ["Define your target respondents",
       "Orthogonality testing",
       "Statistical control charting",
       "MNAR classification only"],
      0, "Target-respondent guidance includes longitudinal vs cross-sectional choices.", "medium"),
    # 3.2.5
    Q("m3-3.2.5-q1", "3.2.5",
      "Data editing primarily involves:",
      ["Inventing missing theoretical frameworks",
       "Checking and correcting errors, inconsistencies, and omissions",
       "Randomising mice to cages",
       "Computing false-positive paradoxes only"],
      1, "Editing checks/corrects errors, inconsistencies, and omissions.", "easy"),
    Q("m3-3.2.5-q2", "3.2.5",
      "Double data entry improves accuracy by:",
      ["Entering data once and trusting it",
       "Having two people enter data and comparing the sets for discrepancies",
       "Deleting half the sample",
       "Using only visual inspection forever"],
      1, "Two independent entries are compared to find discrepancies.", "easy"),
    Q("m3-3.2.5-q3", "3.2.5",
      "A listed disadvantage of visual inspection is that it is:",
      ["Always faster than computers on huge datasets",
       "Time-consuming and prone to human error on large datasets",
       "Impossible to use at all",
       "Identical to Cronbach’s alpha"],
      1, "Visual inspection is slow and human-error prone for large data.", "medium"),
    # 3.2.6
    Q("m3-3.2.6-q1", "3.2.6",
      "Data coding is described as:",
      ["Deleting all qualitative comments",
       "Transforming raw data into a structured format for organisation and analysis",
       "Plotting only c-charts",
       "Estimating counterfactuals for impact evaluation"],
      1, "Coding structures raw data for organisation, analysis, and pattern finding.", "easy"),
    Q("m3-3.2.6-q2", "3.2.6",
      "In the survey Likert example, “strongly agree” is coded as:",
      ["1", "3", "5", "0"],
      2, "Strongly agree = 5 down to strongly disagree = 1.", "easy"),
    Q("m3-3.2.6-q3", "3.2.6",
      "Which is listed as a benefit of coding?",
      ["Preventing all missing data automatically",
       "Data reduction and pattern recognition",
       "Guaranteeing orthogonality",
       "Replacing replication"],
      1, "Coding supports reduction, organisation, pattern recognition, analysis, and comparison.", "medium"),
    # 3.2.7
    Q("m3-3.2.7-q1", "3.2.7",
      "A risk of offering “don’t know” options is that respondents may:",
      ["Always give richer explanations",
       "Use them to avoid engaging, compromising response reliability",
       "Increase Cronbach’s alpha automatically",
       "Create orthogonal ANOVA cells"],
      1, "DK can become an avoidance route that harms reliability.", "easy"),
    Q("m3-3.2.7-q2", "3.2.7",
      "Providing an “other” option is said to help because it:",
      ["Forces binary yes/no answers only",
       "Lets respondents furnish additional information or explain perspectives",
       "Removes the need for pilot testing",
       "Defines MCAR missingness"],
      1, "“Other” empowers elaboration beyond closed lists.", "easy"),
    Q("m3-3.2.7-q3", "3.2.7",
      "For brand/product surveys, before soliciting opinions the extract says to ensure:",
      ["Respondents lack any familiarity",
       "Respondents possess adequate familiarity with the subject",
       "Only MNAR mechanisms apply",
       "Control charts replace questionnaires"],
      1, "Ensure familiarity so respondents are not rating unknown items.", "medium"),
    # 3.2.8
    Q("m3-3.2.8-q1", "3.2.8",
      "Missing Completely at Random (MCAR) means missingness is:",
      ["Caused by the missing values themselves",
       "Random across variables and unrelated to other factors",
       "Always non-ignorable",
       "Identical to a false positive"],
      1, "MCAR: random, unrelated to other factors (e.g. random dropouts).", "easy"),
    Q("m3-3.2.8-q2", "3.2.8",
      "Which missing-data type introduces non-ignorable biases in the extract’s framing?",
      ["MCAR only", "MAR only", "MNAR", "None of them"],
      2, "MNAR is non-ignorable; MCAR/MAR may be considered ignorable.", "medium"),
    Q("m3-3.2.8-q3", "3.2.8",
      "An example given for MNAR is:",
      ["Random survey dropouts unrelated to anything",
       "Lower-income respondents intentionally omitting holiday spending amounts",
       "Age-related privacy non-response explained by observed age",
       "Balanced ANOVA cells"],
      1, "MNAR: missingness tied to the values themselves (low income → omit spending).", "medium"),
    # 3.3.1
    Q("m3-3.3.1-q1", "3.3.1",
      "Validity pertains to:",
      ["Only the speed of data entry",
       "The degree of accuracy with which a technique assesses the desired measurement",
       "Whether vectors multiply to zero",
       "Sample size on attribute charts only"],
      1, "Validity = accuracy of measuring what is intended.", "easy"),
    Q("m3-3.3.1-q2", "3.3.1",
      "If Cronbach’s alpha is 0.75, the extract’s interpretation band is:",
      ["Excellent (α ≥ 0.9)", "Good (0.7 ≤ α < 0.9)", "Poor (0.5 ≤ α < 0.6)", "Unacceptable (α < 0.5)"],
      1, "0.7 ≤ α < 0.9 is labelled Good.", "medium"),
    Q("m3-3.3.1-q3", "3.3.1",
      "A Bengali language test with reading, writing, and speaking but no listening is said to lack:",
      ["Criterion validity only", "Content validity for overall ability", "Orthogonality", "MCAR status"],
      1, "Experts say listening is essential, so omitting it harms content validity.", "medium"),
    # 3.3.2
    Q("m3-3.3.2-q1", "3.3.2",
      "Without replication, the extract argues it is impossible to:",
      ["Mail questionnaires",
       "Judge whether an observed difference is real or due to chance",
       "Define validity",
       "Code Likert items"],
      1, "Replication is needed to separate chance from real differences.", "easy"),
    Q("m3-3.3.2-q2", "3.3.2",
      "Randomisation mitigates confounding by:",
      ["Fixing every variable to one value forever",
       "Equalising unaccounted influences across experimental units via non-deterministic assignment",
       "Removing the need for blocks",
       "Guaranteeing Cronbach’s α > 0.9"],
      1, "Random assignment balances confounders across conditions.", "medium"),
    Q("m3-3.3.2-q3", "3.3.2",
      "Blocks are described as:",
      ["Heterogeneous groups that maximise noise",
       "Homogeneous groups of units that reduce variability and clarify condition differences",
       "Only mailing envelopes",
       "False-positive medical tests"],
      1, "Blocks are homogeneous groups used to reduce variability between units.", "easy"),
    # 3.3.3
    Q("m3-3.3.3-q1", "3.3.3",
      "In this module, orthogonality means:",
      ["All dependent variables are binary",
       "Independent variables are uncorrelated",
       "Missing data are MNAR",
       "Only interviews are used"],
      1, "Orthogonality = uncorrelated independents in the model.", "easy"),
    Q("m3-3.3.3-q2", "3.3.3",
      "A false positive occurs when:",
      ["A test is negative though the condition is present",
       "A test yields a positive result instead of the expected negative",
       "ANOVA cells are perfectly balanced",
       "Replication is increased"],
      1, "False positive = positive result when truth is negative (false alarm).", "easy"),
    Q("m3-3.3.3-q3", "3.3.3",
      "An orthogonal ANOVA (as described) typically has:",
      ["Unequal empty cells by design always",
       "Categorical independents with equal observations per cell (balanced data)",
       "Only continuous covariates",
       "No statistical tests"],
      1, "Orthogonal ANOVA is tied to balanced cells with equal counts.", "medium"),
]


TREE_CHILDREN = [
    {
        "id": "3.1",
        "title": "3.1 Design of Experiments",
        "children": [
            {"id": "3.1.1", "title": "3.1.1 Objectives and Strategies", "conceptId": "3.1.1"},
            {"id": "3.1.2", "title": "3.1.2 Pre-Experimental Design", "conceptId": "3.1.2"},
            {"id": "3.1.3", "title": "3.1.3 Quasi-Experimental Design", "conceptId": "3.1.3"},
            {"id": "3.1.4", "title": "3.1.4 True Experimental Design", "conceptId": "3.1.4"},
            {"id": "3.1.5", "title": "3.1.5 Factorial Experimental Design", "conceptId": "3.1.5"},
            {"id": "3.1.6", "title": "3.1.6 Designing Engineering Experiments", "conceptId": "3.1.6"},
            {"id": "3.1.7", "title": "3.1.7 Causal Attributions", "conceptId": "3.1.7"},
            {"id": "3.1.8", "title": "3.1.8 Statistical Control", "conceptId": "3.1.8"},
        ],
    },
    {
        "id": "3.2",
        "title": "3.2 Data Collection",
        "children": [
            {"id": "3.2.1", "title": "3.2.1 Observation and Interview", "conceptId": "3.2.1"},
            {"id": "3.2.2", "title": "3.2.2 Data through Cases", "conceptId": "3.2.2"},
            {"id": "3.2.3", "title": "3.2.3 Data through Questionnaires", "conceptId": "3.2.3"},
            {"id": "3.2.4", "title": "3.2.4 Questionnaire Guidelines", "conceptId": "3.2.4"},
            {"id": "3.2.5", "title": "3.2.5 Data Editing", "conceptId": "3.2.5"},
            {"id": "3.2.6", "title": "3.2.6 Data Coding Rules", "conceptId": "3.2.6"},
            {"id": "3.2.7", "title": "3.2.7 Don’t Know Responses", "conceptId": "3.2.7"},
            {"id": "3.2.8", "title": "3.2.8 Missing Data", "conceptId": "3.2.8"},
        ],
    },
    {
        "id": "3.3",
        "title": "3.3 Basic Principles",
        "children": [
            {"id": "3.3.1", "title": "3.3.1 Validity and Reliability", "conceptId": "3.3.1"},
            {"id": "3.3.2", "title": "3.3.2 Replication, Randomisation, Blocking", "conceptId": "3.3.2"},
            {"id": "3.3.3", "title": "3.3.3 Orthogonality and False Positives", "conceptId": "3.3.3"},
        ],
    },
]


def main() -> None:
    assert len(CONCEPTS) == 19
    for cid in CONCEPTS:
        n = sum(1 for q in QUESTIONS if q["conceptId"] == cid)
        assert n >= 2, f"{cid} has only {n} MCQs"
    merge_module(
        module_id=MODULE_ID,
        module_title=MODULE_TITLE,
        tree_children=TREE_CHILDREN,
        concepts=CONCEPTS,
        questions=QUESTIONS,
        status="approved",
    )


if __name__ == "__main__":
    main()
