"""Handcrafted extra MCQs — 2 per CSIT654 topic (55×2=110). Append via merge_extra_mcqs.py."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "subjects" / "csit654" / "v3" / "data"


def Q(cid: str, n: int, stem: str, options: list[str], correct: int, explanation: str, difficulty: str = "medium"):
    mid = int(cid.split(".")[0])
    assert len(options) == 4 and correct in (0, 1, 2, 3)
    return {
        "id": f"hand-{cid}-q{n}",
        "module": mid,
        "conceptId": cid,
        "source": "handcrafted",
        "stem": stem,
        "options": options,
        "correct": correct,
        "explanation": explanation,
        "answerSource": "slm",
        "difficulty": difficulty,
    }


QUESTIONS = [
    # —— Module 1 ——
    Q("1.1.1", 1, "An attacker records packet timings between two hosts but never changes any packet. This is best classified as:",
      ["An active modification attack", "A passive traffic-analysis attack", "A fabrication attack", "An interruption (DoS) attack"], 1,
      "Observing traffic without altering resources is passive; traffic analysis is the classic case.", "easy"),
    Q("1.1.1", 2, "Which attack primarily threatens availability by destroying or blocking access to an asset?",
      ["Interception", "Modification", "Interruption", "Fabrication"], 2,
      "Interruption is the availability-oriented attack (DoS flavour).", "easy"),
    Q("1.1.2", 1, "In security terminology, confidentiality, authentication, and non-repudiation are examples of:",
      ["Security mechanisms", "Security services", "Cryptanalytic models", "Key schedules"], 1,
      "Services are the abstract goals; mechanisms are the concrete techniques that achieve them.", "easy"),
    Q("1.1.2", 2, "Encryption used to keep message contents secret is best described as a:",
      ["Security service named AES", "Security mechanism supporting confidentiality", "Form of steganography", "Non-repudiation service by itself"], 1,
      "Encryption is a mechanism; the service it mainly supports is confidentiality.", "medium"),
    Q("1.1.3", 1, "Classical encryption techniques are built mainly from which two families of operations?",
      ["Hashing and MACs", "Substitution and transposition", "Public-key and hybrid wrapping", "Tunneling and filtering"], 1,
      "Classical ciphers rearrange (transpose) and/or replace (substitute) symbols under a key.", "easy"),
    Q("1.1.3", 2, "Kerckhoffs’ modern design assumption treats which item as public knowledge?",
      ["The encryption key", "The algorithm / cipher design", "The plaintext language", "The IV only"], 1,
      "Assume the adversary knows the algorithm; secrecy lives in the key.", "medium"),
    Q("1.1.4", 1, "A cipher that uses one fixed substitution alphabet for the entire message is:",
      ["Polyalphabetic", "Monoalphabetic", "A transposition cipher", "A Feistel network"], 1,
      "Monoalphabetic = one mapping for all positions; polyalphabetic varies the alphabet.", "easy"),
    Q("1.1.4", 2, "Why is the Caesar cipher especially weak against brute force?",
      ["It uses 128-bit blocks", "Its nontrivial key space is only 25 letter shifts", "It requires an IV", "It is a stream cipher"], 1,
      "Only 25 nontrivial shifts of the alphabet — exhaustive search is trivial.", "easy"),
    Q("1.1.5", 1, "A scheme that keeps the same letters but changes only their order is a:",
      ["Substitution cipher", "Transposition cipher", "One-time pad", "Message digest"], 1,
      "Transposition permutes positions; symbol identities stay the same.", "easy"),
    Q("1.1.5", 2, "In columnar transposition, a keyword is typically used to:",
      ["Substitute each letter with another", "Order the columns when reading out ciphertext", "Generate an RSA modulus", "Pad the final block"], 1,
      "The keyword (or its alphabetical order) selects the column read order.", "medium"),
    Q("1.1.6", 1, "An adversary who already has several matching plaintext–ciphertext pairs is using which attack model?",
      ["Ciphertext-only", "Known-plaintext", "Traffic analysis only", "Steganalysis"], 1,
      "Known-plaintext assumes the attacker has pairs; ciphertext-only has none.", "easy"),
    Q("1.1.6", 2, "Trying every key until decryption yields readable text is called:",
      ["Frequency analysis", "Differential cryptanalysis", "Brute-force (exhaustive) search", "Chosen-ciphertext forgery"], 2,
      "Brute force enumerates the key space.", "easy"),
    Q("1.1.7", 1, "Steganography primarily aims to hide:",
      ["The mathematical structure of AES", "The existence of a secret message in cover media", "Only the MAC tag length", "DNS query names"], 1,
      "Stego hides presence; cryptography hides meaning.", "easy"),
    Q("1.1.7", 2, "Altering least-significant bits of image pixels to embed a secret is an example of:",
      ["Rail-fence transposition", "LSB steganographic embedding", "CBC mode chaining", "Kerberos ticket granting"], 1,
      "LSB embedding is a common image steganography method.", "easy"),
    Q("1.1.8", 1, "Encrypting a continuous bit stream by XOR with a running keystream describes a:",
      ["Block cipher in ECB only", "Stream cipher", "Digital signature", "Hash function"], 1,
      "Stream ciphers typically combine plaintext with a keystream (often XOR).", "easy"),
    Q("1.1.8", 2, "Reusing the same stream-cipher keystream for two different messages is dangerous because:",
      ["Blocks become 256 bits", "XOR of the two ciphertexts can leak plaintext relationship", "RSA moduli collide", "IVs become public"], 1,
      "C1⊕C2 = P1⊕P2 when the same keystream is reused — catastrophic.", "medium"),
    Q("1.1.9", 1, "Recovering a key by measuring power consumption of a chip during AES is an example of:",
      ["Ciphertext-only frequency analysis", "A side-channel attack", "A chosen-plaintext algebraic attack only", "Steganography"], 1,
      "Side channels exploit physical leakage (power, timing, EM), not only the cipher maths.", "medium"),
    Q("1.1.9", 2, "A TPM or secure element is best described as:",
      ["A software-only password manager", "Dedicated hardware that isolates keys and crypto operations", "An email compression format", "A transposition cipher"], 1,
      "Hardware roots of trust store keys and perform crypto in isolation.", "easy"),

    # —— Module 2 ——
    Q("2.1.1", 1, "A product cipher in Shannon’s sense typically combines:",
      ["Only hashing rounds", "Substitutions and permutations across rounds", "Only public-key wrapping", "DNS and DHCP"], 1,
      "Product ciphers compose substitution (confusion) and permutation (diffusion).", "easy"),
    Q("2.1.1", 2, "The key schedule of a block cipher is responsible for:",
      ["Padding the plaintext", "Deriving round keys from the master key", "Choosing the IV randomly each year", "Compressing ciphertext"], 1,
      "Key schedule expands/derives per-round keys from the master key.", "easy"),
    Q("2.1.2", 1, "Shannon’s confusion primarily aims to:",
      ["Spread one plaintext bit across many ciphertext bits", "Hide the relationship between key and ciphertext", "Remove the need for an IV", "Guarantee non-repudiation"], 1,
      "Confusion obscures key–ciphertext dependence (often via S-boxes).", "easy"),
    Q("2.1.2", 2, "Diffusion in a block cipher means:",
      ["Using a public key for encryption", "Spreading the influence of plaintext bits widely in the ciphertext", "Hiding the algorithm", "Replacing crypto with steganography"], 1,
      "Diffusion spreads plaintext influence; confusion hides key linkage.", "easy"),
    Q("2.1.3", 1, "In a Feistel structure, decryption is performed by:",
      ["Inverting every S-box algebraically", "Running the same structure with round keys in reverse order", "Using a different block size", "Hashing the ciphertext"], 1,
      "Feistel decryption = same round structure, reverse key order.", "medium"),
    Q("2.1.3", 2, "A Feistel round typically splits the block into halves and:",
      ["Encrypts only the left half with RSA", "Applies a round function to one half and XORs into the other, then swaps", "Discards the right half", "Requires an odd number of bits only"], 1,
      "Classic Feistel: F(right, Ki) XORed into left, then swap.", "medium"),
    Q("2.1.4", 1, "DES encrypts data in blocks of:",
      ["128 bits with a 256-bit key", "64 bits using a 56-bit effective key", "32 bits with no key schedule", "256-bit blocks only"], 1,
      "DES: 64-bit blocks, 56-bit effective key (64 with parity bits).", "easy"),
    Q("2.1.4", 2, "DES is structurally best described as:",
      ["An SPN like AES", "A Feistel cipher", "A pure stream cipher", "A hash-only construction"], 1,
      "DES is the classic Feistel block cipher.", "easy"),
    Q("2.1.5", 1, "The main practical weakness that retired single-DES for bulk encryption is:",
      ["Too many rounds for hardware", "56-bit key space is searchable by modern brute force", "It cannot use CBC mode", "It has no S-boxes"], 1,
      "56-bit keys are within reach of exhaustive search.", "easy"),
    Q("2.1.5", 2, "Complementarity and weak/semi-weak keys are discussed mainly under:",
      ["Strength and structural properties of DES", "RSA padding only", "Kerberos realms", "LSB steganography"], 0,
      "DES strength topics include key size, weak keys, and related structural issues.", "medium"),
    Q("2.1.6", 1, "Differential cryptanalysis studies how:",
      ["DNS caches poison", "Input differences propagate to output differences through cipher rounds", "Passwords are salted", "Certificates expire"], 1,
      "It tracks difference propagation to recover key material.", "medium"),
    Q("2.1.6", 2, "Differential cryptanalysis is primarily a concern for designers of:",
      ["SMTP headers", "Symmetric block ciphers and their S-boxes/rounds", "HTML forms", "RAID arrays"], 1,
      "It targets iterative block-cipher structure (historically DES).", "medium"),
    Q("2.1.7", 1, "Which mode encrypts each plaintext block independently under the same key?",
      ["CBC", "ECB", "CFB", "CTR only as a hash"], 1,
      "ECB has no chaining — identical blocks → identical ciphertext.", "easy"),
    Q("2.1.7", 2, "CBC mode needs an IV mainly to:",
      ["Replace the secret key", "Randomise the first block so identical messages don’t start the same", "Compress ciphertext", "Create digital signatures"], 1,
      "IV (and chaining) hide patterns across messages/blocks.", "medium"),
    Q("2.1.8", 1, "Triple DES (3DES) typically applies DES:",
      ["Once with a 256-bit key", "Three times (EDE) with two or three keys to stretch effective strength", "As a hash only", "Inside RSA modulus generation"], 1,
      "EDE with 2 or 3 keys is the standard 3DES construction.", "easy"),
    Q("2.1.8", 2, "Compared with AES, 3DES is generally:",
      ["Faster and preferred for new designs", "Slower and retained mainly for legacy interoperability", "A public-key algorithm", "Immune to all attacks by definition"], 1,
      "3DES is legacy; AES is the modern standard block cipher.", "medium"),
    Q("2.2.1", 1, "AES (Rijndael) is best classified as:",
      ["A Feistel cipher like DES", "A substitution–permutation (SPN) network", "A stream-only XOR cipher", "A signature standard"], 1,
      "AES is an SPN (SubBytes, ShiftRows, MixColumns, AddRoundKey).", "easy"),
    Q("2.2.1", 2, "Which AES step provides the main byte-level nonlinear confusion?",
      ["ShiftRows", "SubBytes (S-box)", "AddRoundKey alone", "PKCS padding"], 1,
      "SubBytes is the nonlinear S-box layer.", "medium"),
    Q("2.2.2", 1, "Fermat’s Little Theorem is useful in RSA-related number theory because it relates:",
      ["a^(p-1) ≡ 1 (mod p) for prime p not dividing a", "Only matrix inverses", "DNS TTLs", "Block cipher IVs"], 0,
      "Fermat: a^(p-1) ≡ 1 mod p under the stated conditions.", "medium"),
    Q("2.2.2", 2, "Euler’s totient φ(n) counts:",
      ["AES rounds", "Integers in 1..n-1 that are coprime to n", "DES S-box rows only", "Kerberos ticket lifetimes"], 1,
      "φ(n) is central to RSA exponents.", "easy"),
    Q("2.2.3", 1, "The Chinese Remainder Theorem helps when you have:",
      ["A single congruence only", "A system of congruences with pairwise coprime moduli", "Only floating-point keys", "Hash collisions"], 1,
      "CRT combines residues modulo coprime moduli into a unique class mod product.", "medium"),
    Q("2.2.3", 2, "In RSA implementations, CRT is often used to:",
      ["Replace the public key", "Speed private-key operations using factors p and q", "Generate AES S-boxes", "Compress certificates"], 1,
      "CRT speeds decryption/signing with p,q.", "medium"),
    Q("2.2.4", 1, "A defining feature of public-key cryptography is:",
      ["One shared secret for both directions only", "Separate public and private keys with hard inversion without the private key", "No need for any algorithms", "Only transposition"], 1,
      "Asymmetric: public encrypt / verify; private decrypt / sign.", "easy"),
    Q("2.2.4", 2, "Public-key encryption is commonly used to:",
      ["Encrypt multi-gigabyte files directly for speed", "Exchange or wrap symmetric session keys", "Replace hashing entirely", "Hide packets inside images only"], 1,
      "Hybrid crypto: public-key wraps a fast symmetric session key.", "medium"),
    Q("2.2.5", 1, "In RSA, the public key typically includes:",
      ["Only the private exponent d", "Modulus n and public exponent e", "Only prime p", "The AES round keys"], 1,
      "Public key is (n,e); private includes d (and often p,q).", "easy"),
    Q("2.2.5", 2, "RSA encryption of message representative m is conceptually:",
      ["c = m XOR e", "c = m^e mod n", "c = m + n", "c = SHA(m)"], 1,
      "Textbook RSA: c ≡ m^e (mod n).", "easy"),
    Q("2.2.6", 1, "RSA security fundamentally relies on the difficulty of:",
      ["Sorting arrays", "Factoring the modulus n (or equivalent RSA problems)", "Drawing rail fences", "Counting TCP ports"], 1,
      "Factoring n (or related hard problems) underpins RSA.", "easy"),
    Q("2.2.6", 2, "Using RSA without proper padding on short/guessable messages is risky because:",
      ["AES becomes Feistel", "Algebraic and guessing attacks become practical", "CRT stops working forever", "IVs collide with DES"], 1,
      "Padding (e.g. OAEP) is required for real RSA security.", "medium"),

    # —— Module 3 ——
    Q("3.1.1", 1, "Message authentication is primarily about assuring:",
      ["Only confidentiality of bulk data", "Integrity and origin authenticity of a message", "Only availability of DNS", "Pixel LSB capacity"], 1,
      "Authentication/MAC goals centre on integrity and who sent it — not secrecy alone.", "easy"),
    Q("3.1.1", 2, "A common exam trap is treating authentication as identical to:",
      ["Encryption for confidentiality", "Disk partitioning", "Rail-fence keys", "BGP"], 0,
      "Authentication ≠ encryption; you can have one without the other.", "easy"),
    Q("3.1.2", 1, "Which family of techniques can provide message authentication?",
      ["Only steganography", "Message encryption, MACs, and hash-based constructions (as taught)", "Only rail-fence ciphers", "Only DHCP"], 1,
      "Authentication functions include encryption-based, MAC, and hash approaches.", "medium"),
    Q("3.1.2", 2, "A plain cryptographic hash without a secret key by itself does not provide:",
      ["A fixed-size digest", "Origin authentication against an active forger who can recompute the hash", "Collision resistance goals", "Integrity checking when the digest is protected separately"], 1,
      "Without a key (or signature), anyone can recompute a hash for a forged message.", "medium"),
    Q("3.1.3", 1, "Core authentication requirements for a MAC-style service include:",
      ["Only faster AES rounds", "Protecting integrity and verifying message origin", "Hiding stego payloads", "Factoring n"], 1,
      "Integrity + authenticity (origin) are the headline requirements.", "easy"),
    Q("3.1.3", 2, "If an adversary can modify a message in transit without detection, which requirement failed?",
      ["Only key length of DES", "Data integrity (and usually authenticity)", "Only steganographic capacity", "CRT uniqueness"], 1,
      "Undetected modification is an integrity failure.", "easy"),
    Q("3.1.4", 1, "A MAC differs from a bare hash because a MAC:",
      ["Never uses hashing inside", "Involves a shared secret key", "Always uses RSA moduli", "Only compresses files"], 1,
      "MAC = keyed authentication tag.", "easy"),
    Q("3.1.4", 2, "To verify a MAC, the receiver typically:",
      ["Factors the sender’s modulus", "Recomputes the MAC with the shared key and compares", "Runs ECB on the tag alone", "Publishes the private key"], 1,
      "Shared-key verify: recompute and compare.", "easy"),
    Q("3.1.5", 1, "SHA family algorithms are primarily:",
      ["Public-key encryption schemes", "Cryptographic hash functions producing fixed-length digests", "Stream ciphers with IVs only", "Kerberos realms"], 1,
      "SHA is a hash algorithm family.", "easy"),
    Q("3.1.5", 2, "Compared with MD5 in modern practice, SHA-2/SHA-3 are preferred because:",
      ["They encrypt with two keys", "Older MD hashes are considered broken/weak for collision resistance", "They remove the need for keys in TLS forever", "They are transposition ciphers"], 1,
      "MD5/SHA-1 collision weaknesses pushed migration to stronger SHA variants.", "medium"),
    Q("3.1.6", 1, "A message digest is best described as:",
      ["A fixed-size fingerprint of arbitrary-length input", "A 3DES round key", "An X.509 private key", "A rail-fence width"], 0,
      "Digest = hash output fingerprint.", "easy"),
    Q("3.1.6", 2, "If two different messages produce the same digest, that is a:",
      ["Certificate pin", "Collision", "Feistel swap", "Passive eavesdrop"], 1,
      "Collision = distinct inputs, same hash.", "easy"),
    Q("3.2.1", 1, "A digital signature primarily provides:",
      ["Only bulk confidentiality", "Integrity, authenticity, and non-repudiation using asymmetric keys", "Only steganographic hiding", "Symmetric MAC without keys"], 1,
      "Signatures: integrity + origin + non-repudiation.", "easy"),
    Q("3.2.1", 2, "Verifying a digital signature uses:",
      ["The signer’s private key", "The signer’s public key", "Only ECB mode", "A shared MAC key exclusively"], 1,
      "Verify with public key; sign with private key.", "easy"),
    Q("3.2.2", 1, "DSS (Digital Signature Standard) standardises:",
      ["A hash-only password file", "Digital signature algorithms (historically DSA family) for US federal use", "Columnar transposition", "SMTP compression"], 1,
      "DSS is the signature standard (DSA/related).", "medium"),
    Q("3.2.2", 2, "DSS/DSA signatures are designed for:",
      ["Encrypting multi-gigabyte video directly", "Authentication of origin/integrity, not bulk encryption", "Replacing AES S-boxes", "Hiding LSB payloads"], 1,
      "Signatures authenticate; they are not bulk ciphers.", "easy"),
    Q("3.2.3", 1, "DSA-style signature schemes rely on hard problems in:",
      ["Sorting networks only", "Discrete logarithms in appropriate groups (as taught for DSA)", "Rail-fence anagrams", "DHCP leases"], 1,
      "DSA security is tied to discrete-log hardness.", "medium"),
    Q("3.2.3", 2, "A correct mental model for DSA is:",
      ["Encrypt with e, decrypt with d like textbook RSA encryption", "Sign with private parameters; verify with public parameters", "MAC with a public key only", "Hash then discard the digest"], 1,
      "Asymmetric sign/verify roles — not RSA encryption mechanics.", "medium"),

    # —— Module 4 ——
    Q("4.1.1", 1, "In Kerberos, a client first contacts the Authentication Server (AS) mainly to obtain a:",
      ["Service ticket for every host at once", "Ticket-Granting Ticket (TGT)", "TLS certificate for the web", "PGP web-of-trust signature"], 1,
      "AS issues a TGT; TGS later issues service tickets.", "medium"),
    Q("4.1.1", 2, "Kerberos is best characterised as:",
      ["A hash algorithm", "A trusted third-party authentication protocol using tickets", "A steganography tool", "An SPN round function"], 1,
      "Kerberos = ticket-based TTP authentication.", "easy"),
    Q("4.1.2", 1, "An Access Control List (ACL) typically associates:",
      ["A hash with a modulus", "Subjects and their permitted rights on an object", "Only AES round counts", "DNS MX records"], 1,
      "ACL: per-object list of subject→rights.", "easy"),
    Q("4.1.2", 2, "Compared with authentication, authorisation via ACLs decides:",
      ["Whether the password hash is SHA-1", "What an identified subject is allowed to do", "How to pad RSA", "Which Feistel half to swap"], 1,
      "AuthN = who; AuthZ/ACL = what rights.", "easy"),
    Q("4.1.3", 1, "PGP email security commonly combines:",
      ["Only columnar transposition", "Hybrid encryption plus signatures and a web of trust for keys", "Kerberos TGTs for every SMTP hop", "ECB-only disk encryption"], 1,
      "PGP: hybrid crypto + signatures; trust via web of trust.", "medium"),
    Q("4.1.3", 2, "In PGP, bulk message data is typically encrypted with:",
      ["Only the recipient’s RSA private key directly on the whole file", "A symmetric session key, which is then public-key wrapped", "Rail-fence alone", "A MAC without encryption always"], 1,
      "Hybrid: fast symmetric for data; public-key wraps the session key.", "medium"),
    Q("4.1.4", 1, "S/MIME secures email primarily using:",
      ["Only plaintext SMTP", "MIME + PKI/certificates (CMS) for encryption and signatures", "Kerberos AS exchanges only", "LSB image embedding"], 1,
      "S/MIME = secure MIME with certificate-based crypto.", "medium"),
    Q("4.1.4", 2, "A practical difference often cited between PGP and S/MIME trust models is:",
      ["S/MIME never encrypts", "PGP emphasises web of trust; S/MIME leans on hierarchical CA/PKI", "PGP forbids signatures", "S/MIME is a block cipher mode"], 1,
      "Trust model contrast is a standard exam point.", "medium"),
    Q("4.2.1", 1, "IPsec AH primarily provides:",
      ["Confidentiality of payload only", "Integrity/authentication of IP packets (no encryption of payload by AH itself)", "Email MIME framing", "Password salting"], 1,
      "AH = auth/integrity; ESP can encrypt (and optionally auth).", "medium"),
    Q("4.2.2", 1, "SSL/TLS is designed mainly to secure:",
      ["Only layer-3 routing headers", "End-to-end application sessions (commonly HTTP) with crypto and handshake", "Disk partition tables", "Rail-fence keys"], 1,
      "TLS protects session data above transport for apps like HTTPS.", "easy"),
    Q("4.2.2", 2, "During a TLS handshake, parties typically negotiate:",
      ["Only the DES complementarity property", "Cipher suites, keys/secrets, and authenticate via certificates (as configured)", "Column order for transposition", "BGP AS numbers"], 1,
      "Handshake negotiates algorithms and establishes keys; certs authenticate.", "medium"),
    Q("4.2.3", 1, "SET (Secure Electronic Transaction) was aimed at:",
      ["Securing card-payment messages among customer, merchant, and bank roles", "Replacing AES S-boxes", "Hiding files in images", "Kerberos TGT renewal only"], 0,
      "SET targets payment-card e-commerce security roles.", "medium"),
    Q("4.2.1", 2, "IPsec ESP is the component typically used when you need:",
      ["Only DNSSEC", "Confidentiality (encryption) of packet payloads, optionally with auth", "PGP web of trust", "Message digests without keys"], 1,
      "ESP provides encryption (and can provide integrity).", "medium"),
    Q("4.2.3", 2, "Relative to ordinary SSL web checkout, SET emphasised:",
      ["Removing all cryptography", "Payment-specific dual signatures / role separation for card data", "Only steganography", "Feistel decryption order"], 1,
      "SET’s design focus was payment authorisation privacy among parties.", "medium"),

    # —— Module 5 ——
    Q("5.1.1", 1, "A masquerader in intrusion terminology is typically:",
      ["A legitimate user exceeding authority", "An outsider posing as a legitimate user", "A TPM chip", "A hash collision"], 1,
      "Masquerader = outsider impersonation; misfeasor = insider abuse.", "easy"),
    Q("5.1.1", 2, "A misfeasor is best described as:",
      ["An outsider with no account", "A legitimate user who misuses privileges", "A firewall rule", "An AES round"], 1,
      "Misfeasor already has legitimate access but abuses it.", "easy"),
    Q("5.1.2", 1, "Signature-based IDS detects attacks mainly by:",
      ["Learning only normal baselines with no patterns", "Matching known malicious patterns/signatures", "Encrypting all packets with ESP", "Factoring RSA moduli"], 1,
      "Signature/misuse detection matches known attack patterns.", "easy"),
    Q("5.1.2", 2, "Anomaly-based detection flags:",
      ["Only MD5 collisions", "Behaviour that deviates from a learned normal profile", "Only failed Kerberos AS requests always as safe", "Stego LSB capacity"], 1,
      "Anomaly IDS: deviation from normal — may false-positive on unusual legit use.", "medium"),
    Q("5.1.3", 1, "A worm differs from a classic virus primarily because a worm:",
      ["Needs a host file and user execution always", "Self-propagates over networks without needing a host program in the classic sense", "Is only a firewall", "Is a hash function"], 1,
      "Worm = self-propagating; virus needs a host to hitch to.", "easy"),
    Q("5.1.3", 2, "A virus typically spreads by:",
      ["Only rewriting BGP", "Infecting host programs/files that then get executed or shared", "Issuing Kerberos TGTs", "Running CRT"], 1,
      "Virus attaches to hosts; execution/sharing spreads it.", "easy"),
    Q("5.1.4", 1, "A packet-filtering firewall makes decisions mainly using:",
      ["Only email MIME structure", "Header fields such as addresses/ports/protocol", "PGP web of trust scores", "SHA collision lists"], 1,
      "Packet filters use network/transport header criteria.", "easy"),
    Q("5.1.4", 2, "A stateful firewall improves on simple packet filters by tracking:",
      ["Only disk inodes", "Connection/session state across packets", "RSA private keys in cleartext", "Rail-fence rails"], 1,
      "Stateful inspection remembers connection state.", "medium"),
    Q("5.1.5", 1, "IT Acts / cyber laws in the syllabus context mainly address:",
      ["AES MixColumns maths only", "Legal frameworks for cyber offences, evidence, and intermediary duties", "Feistel swaps", "ECB pattern leakage proofs"], 1,
      "Cyber law = legal obligations and offences in cyberspace.", "easy"),
    Q("5.1.5", 2, "For exams, cyber-law questions often test:",
      ["Only DES weak keys", "Which activities are offences / what authorities may demand", "How to compute φ(n) by hand always", "LSB capacity formulas"], 1,
      "Focus on offences, jurisdiction, and compliance themes from the SLM.", "medium"),
    Q("5.1.6", 1, "A VPN primarily provides:",
      ["A steganographic cover image", "A protected tunnel for remote/site traffic over an untrusted network", "A message digest only", "An ACL without crypto"], 1,
      "VPN = confidential/authenticated tunnel across public networks.", "easy"),
    Q("5.1.6", 2, "IPsec and SSL/TLS VPNs differ mainly in:",
      ["Whether maths exists", "Layer/scope (network vs application/session oriented designs)", "Whether keys can exist", "Whether firewalls exist"], 1,
      "Classic contrast: IPsec at IP layer vs SSL VPN at session/app gateway styles.", "medium"),
    Q("5.1.7", 1, "Defence against phishing is primarily about:",
      ["Longer AES keys only", "User awareness plus technical controls on mail/web identity", "Disabling all hashing", "Removing IVs"], 1,
      "Phishing is social + technical; awareness and mail/web controls matter.", "easy"),
    Q("5.1.7", 2, "A DDoS attack primarily targets:",
      ["Confidentiality of one ciphertext block", "Availability by overwhelming resources", "Non-repudiation of signatures", "CRT uniqueness"], 1,
      "DDoS = availability attack via volume/resource exhaustion.", "easy"),
    Q("5.1.8", 1, "A blockchain’s ledger integrity relies heavily on:",
      ["ECB mode graphics", "Cryptographic hashing and chained blocks (plus consensus as taught)", "Rail-fence keys", "SMTP VRFY"], 1,
      "Hash chaining (+ consensus) underpins tamper evidence.", "easy"),
    Q("5.1.8", 2, "Changing a past block’s data in a hash-chained ledger typically:",
      ["Leaves all later hashes valid", "Invalidates subsequent hash links", "Removes the need for keys in TLS", "Converts AES to Feistel"], 1,
      "Cascade: one change breaks the chain of digests.", "easy"),
    Q("5.1.9", 1, "Internet privacy controls often emphasise:",
      ["Publishing private keys", "Limiting unnecessary data collection/tracking and protecting personal data", "Disabling all MACs", "Using only ECB"], 1,
      "Privacy = control over personal data and tracking exposure.", "easy"),
    Q("5.1.9", 2, "Software piracy prevention techniques include:",
      ["Only columnar transposition of source", "Licensing, activation, watermarking/DRM-style controls (as taught)", "Removing HTTPS", "Disabling firewalls"], 1,
      "Piracy prevention uses licensing/DRM/watermark themes from the SLM.", "medium"),
    Q("5.2.1", 1, "Cyber forensics is primarily the discipline of:",
      ["Designing AES S-boxes", "Collecting and analysing digital evidence for investigation", "Writing BGP policies", "Drawing rail fences"], 1,
      "Forensics = investigative evidence handling.", "easy"),
    Q("5.2.1", 2, "A core principle so evidence remains useful in court is:",
      ["Editing logs freely", "Preserving integrity/chain of custody of digital evidence", "Deleting original disks always", "Publishing private keys"], 1,
      "Integrity and custody make evidence admissible/trustworthy.", "easy"),
    Q("5.2.2", 1, "A typical high-level cyber-forensic process order starts with:",
      ["Court testimony before collection", "Identification/collection, then preservation, analysis, presentation", "Only installing games", "Rebooting to destroy volatile data intentionally"], 1,
      "Collect/preserve before deep analysis; present findings last.", "medium"),
    Q("5.2.2", 2, "Preserving volatile memory early matters because:",
      ["AES keys never exist in RAM", "Power-off can lose live evidence in memory", "Hashes cannot be computed on disks", "Kerberos forbids memory capture"], 1,
      "RAM content disappears when power is lost.", "medium"),
    Q("5.2.3", 1, "Cyber forensic applications commonly include:",
      ["Only designing Feistel ciphers", "Investigating intrusions, fraud, and policy violations using digital evidence", "Replacing TLS handshakes", "Generating φ(n) tables"], 1,
      "Applications = investigative use-cases for digital evidence.", "easy"),
    Q("5.2.3", 2, "Forensic analysis may recover:",
      ["Only printed paper", "Deleted files, logs, and artefacts supporting a timeline", "Only public DNSSEC keys", "Rail-fence widths from RSA"], 1,
      "Recovery of artefacts/timelines is a core application.", "easy"),
    Q("5.2.4", 1, "Forensic imaging tools are used to:",
      ["Encrypt email with PGP only", "Create bit-for-bit copies of media for analysis without altering originals", "Configure BGP", "Compute only DES parity"], 1,
      "Imaging preserves originals via verified duplicates.", "easy"),
    Q("5.2.4", 2, "Hashing a disk image before and after analysis helps prove:",
      ["That AES is Feistel", "The image was not altered (integrity)", "That CRT failed", "That stego capacity increased"], 1,
      "Matching hashes support integrity of the evidence copy.", "easy"),
    Q("5.2.5", 1, "Digital evidence can include:",
      ["Only handwritten paper", "Logs, files, emails, memory dumps, and other electronically stored info", "Only TPM manufacturer logos", "Only rail-fence diagrams"], 1,
      "Broad ESI/artefacts count as digital evidence.", "easy"),
    Q("5.2.5", 2, "Admissibility of digital evidence is threatened if:",
      ["Hashes were recorded", "Chain of custody is broken or evidence was altered", "Write-blockers were used", "Images were verified"], 1,
      "Broken custody / tampering undermines admissibility.", "medium"),
    Q("5.2.6", 1, "Investigating Windows systems often examines:",
      ["Only /etc/shadow on Windows", "Event logs, registry, and filesystem artefacts", "Only AES MixColumns tables", "Only PGP trust packets"], 1,
      "Windows artefacts: logs, registry, FS metadata.", "medium"),
    Q("5.2.6", 2, "On Unix/Linux, useful forensic sources commonly include:",
      ["Only the Windows Registry", "System logs, user homes, and process/file metadata", "Only Outlook .pst by default", "Only DES weak-key lists"], 1,
      "Unix: syslog/auth logs, home dirs, permissions/timestamps.", "medium"),
    Q("5.2.7", 1, "Tracing an email’s path relies heavily on:",
      ["Ignoring all headers", "Analysing Received and related header fields", "Only the visible From: display name", "Rail-fence decryption"], 1,
      "Received: headers show relay path (with spoofing caveats).", "easy"),
    Q("5.2.7", 2, "A spoofed From: address means investigators should:",
      ["Trust it as conclusive origin", "Corroborate with Received headers, server logs, and authentication results", "Delete the message immediately as useless", "Assume AES failed"], 1,
      "Display From: is weak; headers/logs/auth results matter more.", "medium"),
]


def main() -> None:
    assert len(QUESTIONS) == 110, len(QUESTIONS)
    from collections import Counter
    c = Counter(q["conceptId"] for q in QUESTIONS)
    assert all(v == 2 for v in c.values()), {k: v for k, v in c.items() if v != 2}
    assert len(c) == 55, len(c)

    # split packs for clarity
    m1m2 = [q for q in QUESTIONS if q["module"] in (1, 2)]
    m3m5 = [q for q in QUESTIONS if q["module"] in (3, 4, 5)]
    (OUT / "extra_mcq_m1m2.json").write_text(
        json.dumps({"questions": m1m2}, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (OUT / "extra_mcq_m3m5.json").write_text(
        json.dumps({"questions": m3m5}, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"wrote m1m2={len(m1m2)} m3m5={len(m3m5)}")


if __name__ == "__main__":
    main()
